// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xamarin-ios-test (2.4.0)

package step

// XamarinIosTestV2Builder builds a xamarin-ios-test step with typed input methods.
//
// Deprecated: The Xamarin development platform is not officially supported. [More info](https://blog.bitrise.io/post/xamarin-support-ends-in-2022-on-bitrise)
type XamarinIosTestV2Builder struct{ *Builder }

// XamarinIosTestV2 creates a xamarin-ios-test step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.XamarinIosTestV2("2")  // explicit default
//	step.XamarinIosTestV2("1")                  // older major
//
// Deprecated: The Xamarin development platform is not officially supported. [More info](https://blog.bitrise.io/post/xamarin-support-ends-in-2022-on-bitrise)
func XamarinIosTestV2(version ...string) *XamarinIosTestV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &XamarinIosTestV2Builder{Builder: From("xamarin-ios-test", v)}
}

// WithSimulatorDevice sets device.
func (b *XamarinIosTestV2Builder) WithSimulatorDevice(value string) *XamarinIosTestV2Builder {
	b.Builder.WithInput("simulator_device", value)
	return b
}

// WithSimulatorOsVersion sets oS version.
func (b *XamarinIosTestV2Builder) WithSimulatorOsVersion(value string) *XamarinIosTestV2Builder {
	b.Builder.WithInput("simulator_os_version", value)
	return b
}

// WithTestToRun sets test name to run.
func (b *XamarinIosTestV2Builder) WithTestToRun(value string) *XamarinIosTestV2Builder {
	b.Builder.WithInput("test_to_run", value)
	return b
}

// WithXamarinProject sets path to Xamarin Solution.
func (b *XamarinIosTestV2Builder) WithXamarinProject(value string) *XamarinIosTestV2Builder {
	b.Builder.WithInput("xamarin_project", value)
	return b
}

// WithXamarinConfiguration sets xamarin solution configuration.
func (b *XamarinIosTestV2Builder) WithXamarinConfiguration(value string) *XamarinIosTestV2Builder {
	b.Builder.WithInput("xamarin_configuration", value)
	return b
}

// WithXamarinPlatform sets xamarin solution platform.
func (b *XamarinIosTestV2Builder) WithXamarinPlatform(value string) *XamarinIosTestV2Builder {
	b.Builder.WithInput("xamarin_platform", value)
	return b
}

// WithBuildTool sets which tool to use for building?.
func (b *XamarinIosTestV2Builder) WithBuildTool(value string) *XamarinIosTestV2Builder {
	b.Builder.WithInput("build_tool", value)
	return b
}
