// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: ionic-prepare (1.2.1)

package step

// IonicPrepareBuilder is a type alias for IonicPrepareV1Builder,
// always pointing to the latest supported major version.
// To target a specific major version use IonicPrepareV{N}() directly.
type IonicPrepareBuilder = IonicPrepareV1Builder

// IonicPrepare creates a ionic-prepare step builder at the latest major version (v1).
// To target a specific major version use IonicPrepareV{N}() directly.
func IonicPrepare(version ...string) *IonicPrepareV1Builder {
	return IonicPrepareV1(version...)
}
