// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: steps-app-gallery-reports (0.9.0)

package step

// StepsAppGalleryReportsDownloadInstallationExportType enumerates the valid values for the download_installation_export_type input.
type StepsAppGalleryReportsDownloadInstallationExportType string

const (
	StepsAppGalleryReportsDownloadInstallationExportTypeCSV   StepsAppGalleryReportsDownloadInstallationExportType = "CSV"
	StepsAppGalleryReportsDownloadInstallationExportTypeEXCEL StepsAppGalleryReportsDownloadInstallationExportType = "EXCEL"
)

// StepsAppGalleryReportsInAppPaymentExportType enumerates the valid values for the in_app_payment_export_type input.
type StepsAppGalleryReportsInAppPaymentExportType string

const (
	StepsAppGalleryReportsInAppPaymentExportTypeCSV   StepsAppGalleryReportsInAppPaymentExportType = "CSV"
	StepsAppGalleryReportsInAppPaymentExportTypeEXCEL StepsAppGalleryReportsInAppPaymentExportType = "EXCEL"
)

// StepsAppGalleryReportsInAppPaymentCurrency enumerates the valid values for the in_app_payment_currency input.
type StepsAppGalleryReportsInAppPaymentCurrency string

const (
	StepsAppGalleryReportsInAppPaymentCurrencyCNY StepsAppGalleryReportsInAppPaymentCurrency = "CNY"
	StepsAppGalleryReportsInAppPaymentCurrencyEUR StepsAppGalleryReportsInAppPaymentCurrency = "EUR"
	StepsAppGalleryReportsInAppPaymentCurrencyUSD StepsAppGalleryReportsInAppPaymentCurrency = "USD"
	StepsAppGalleryReportsInAppPaymentCurrencyGBP StepsAppGalleryReportsInAppPaymentCurrency = "GBP"
	StepsAppGalleryReportsInAppPaymentCurrencyJPY StepsAppGalleryReportsInAppPaymentCurrency = "JPY"
)

// StepsAppGalleryReportsPaidDownloadDomain enumerates the valid values for the paid_download_domain input.
type StepsAppGalleryReportsPaidDownloadDomain string

const (
	StepsAppGalleryReportsPaidDownloadDomainChina       StepsAppGalleryReportsPaidDownloadDomain = "China"
	StepsAppGalleryReportsPaidDownloadDomainEurope      StepsAppGalleryReportsPaidDownloadDomain = "Europe"
	StepsAppGalleryReportsPaidDownloadDomainAsiaPacific StepsAppGalleryReportsPaidDownloadDomain = "Asia Pacific"
	StepsAppGalleryReportsPaidDownloadDomainRussia      StepsAppGalleryReportsPaidDownloadDomain = "Russia"
)

// StepsAppGalleryReportsShowDebugLogs enumerates the valid values for the show_debug_logs input.
type StepsAppGalleryReportsShowDebugLogs string

const (
	StepsAppGalleryReportsShowDebugLogsNo  StepsAppGalleryReportsShowDebugLogs = "no"
	StepsAppGalleryReportsShowDebugLogsYes StepsAppGalleryReportsShowDebugLogs = "yes"
)

// StepsAppGalleryReportsBuilder builds a steps-app-gallery-reports step with typed input methods.
type StepsAppGalleryReportsBuilder struct{ *Builder }

// StepsAppGalleryReports creates a steps-app-gallery-reports step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.StepsAppGalleryReports("0")  // explicit default
//	step.StepsAppGalleryReports("1")                  // older major
func StepsAppGalleryReports(version ...string) *StepsAppGalleryReportsBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &StepsAppGalleryReportsBuilder{Builder: From("steps-app-gallery-reports", v)}
}

// WithHuaweiAppId sets app ID.
func (b *StepsAppGalleryReportsBuilder) WithHuaweiAppId(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("huawei_app_id", value)
	return b
}

// WithHuaweiClientId sets client ID.
func (b *StepsAppGalleryReportsBuilder) WithHuaweiClientId(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("huawei_client_id", value)
	return b
}

// WithHuaweiClientSecret sets key.
func (b *StepsAppGalleryReportsBuilder) WithHuaweiClientSecret(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("huawei_client_secret", value)
	return b
}

// WithDownloadInstallationLanguage sets language.
func (b *StepsAppGalleryReportsBuilder) WithDownloadInstallationLanguage(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("download_installation_language", value)
	return b
}

// WithDownloadInstallationStartTime sets start Time.
func (b *StepsAppGalleryReportsBuilder) WithDownloadInstallationStartTime(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("download_installation_start_time", value)
	return b
}

// WithDownloadInstallationEndTime sets end Time.
func (b *StepsAppGalleryReportsBuilder) WithDownloadInstallationEndTime(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("download_installation_end_time", value)
	return b
}

// WithDownloadInstallationExportType sets export Type.
func (b *StepsAppGalleryReportsBuilder) WithDownloadInstallationExportType(value StepsAppGalleryReportsDownloadInstallationExportType) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("download_installation_export_type", string(value))
	return b
}

// WithInAppPaymentLanguage sets language.
func (b *StepsAppGalleryReportsBuilder) WithInAppPaymentLanguage(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("in_app_payment_language", value)
	return b
}

// WithInAppPaymentStartTime sets start Time.
func (b *StepsAppGalleryReportsBuilder) WithInAppPaymentStartTime(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("in_app_payment_start_time", value)
	return b
}

// WithInAppPaymentEndTime sets end Time.
func (b *StepsAppGalleryReportsBuilder) WithInAppPaymentEndTime(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("in_app_payment_end_time", value)
	return b
}

// WithInAppPaymentExportType sets export Type.
func (b *StepsAppGalleryReportsBuilder) WithInAppPaymentExportType(value StepsAppGalleryReportsInAppPaymentExportType) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("in_app_payment_export_type", string(value))
	return b
}

// WithInAppPaymentCurrency sets currency.
func (b *StepsAppGalleryReportsBuilder) WithInAppPaymentCurrency(value StepsAppGalleryReportsInAppPaymentCurrency) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("in_app_payment_currency", string(value))
	return b
}

// WithPaidDownloadDomain sets domain.
func (b *StepsAppGalleryReportsBuilder) WithPaidDownloadDomain(value StepsAppGalleryReportsPaidDownloadDomain) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("paid_download_domain", string(value))
	return b
}

// WithPaidDownloadLanguage sets language.
func (b *StepsAppGalleryReportsBuilder) WithPaidDownloadLanguage(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("paid_download_language", value)
	return b
}

// WithPaidDownloadStartTime sets start Time.
func (b *StepsAppGalleryReportsBuilder) WithPaidDownloadStartTime(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("paid_download_start_time", value)
	return b
}

// WithPaidDownloadEndTime sets end Time.
func (b *StepsAppGalleryReportsBuilder) WithPaidDownloadEndTime(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("paid_download_end_time", value)
	return b
}

// WithPaidDownloadCountryId sets country Id.
func (b *StepsAppGalleryReportsBuilder) WithPaidDownloadCountryId(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("paid_download_country_id", value)
	return b
}

// WithInstallationFailureDataLanguage sets language.
func (b *StepsAppGalleryReportsBuilder) WithInstallationFailureDataLanguage(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("installation_failure_data_language", value)
	return b
}

// WithInstallationFailureDataStartTime sets start Time.
func (b *StepsAppGalleryReportsBuilder) WithInstallationFailureDataStartTime(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("installation_failure_data_start_time", value)
	return b
}

// WithInstallationFailureDataEndTime sets end Time.
func (b *StepsAppGalleryReportsBuilder) WithInstallationFailureDataEndTime(value string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("installation_failure_data_end_time", value)
	return b
}

// WithShowDebugLogs sets show debug logs?.
func (b *StepsAppGalleryReportsBuilder) WithShowDebugLogs(value StepsAppGalleryReportsShowDebugLogs) *StepsAppGalleryReportsBuilder {
	b.Builder.WithInput("show_debug_logs", string(value))
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *StepsAppGalleryReportsBuilder) WithRunIf(expr string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *StepsAppGalleryReportsBuilder) WithIsAlwaysRun(v bool) *StepsAppGalleryReportsBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *StepsAppGalleryReportsBuilder) WithIsSkippable(v bool) *StepsAppGalleryReportsBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *StepsAppGalleryReportsBuilder) WithTitle(title string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *StepsAppGalleryReportsBuilder) WithTimeout(seconds int) *StepsAppGalleryReportsBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *StepsAppGalleryReportsBuilder) WithNoOutputTimeout(seconds int) *StepsAppGalleryReportsBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *StepsAppGalleryReportsBuilder) WithExecutionContainer(containerID string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *StepsAppGalleryReportsBuilder) WithServiceContainers(containerIDs ...string) *StepsAppGalleryReportsBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// stepsAppGalleryReportsOutputs holds the names of environment variables published
// by the steps-app-gallery-reports step (v0) at run time.
type stepsAppGalleryReportsOutputs struct {
	// DownloadInstallationReportLink is the "Download and Installation Report Link" output env var.
	DownloadInstallationReportLink string
	// InAppPaymentReportReportLink is the "In-App Payment Report Link" output env var.
	InAppPaymentReportReportLink string
	// PaidDownloadReportLink is the "Paid Download Report Link" output env var.
	PaidDownloadReportLink string
	// InstallationFailureDataReportLink is the "Installation Failure Data Report Link" output env var.
	InstallationFailureDataReportLink string
}

// StepsAppGalleryReportsOutputs provides typed access to the environment variable names
// that steps-app-gallery-reports (v0) exports after a successful run.
var StepsAppGalleryReportsOutputs = stepsAppGalleryReportsOutputs{
	DownloadInstallationReportLink:    "DOWNLOAD_INSTALLATION_REPORT_LINK",
	InAppPaymentReportReportLink:      "IN_APP_PAYMENT_REPORT_REPORT_LINK",
	PaidDownloadReportLink:            "PAID_DOWNLOAD_REPORT_LINK",
	InstallationFailureDataReportLink: "INSTALLATION_FAILURE_DATA_REPORT_LINK",
}
