// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: versionbox-deploy (0.0.3)

package step

import "time"

// VersionboxDeployVbMarkLive enumerates the valid values for the vb_mark_live input.
type VersionboxDeployVbMarkLive string

const (
	VersionboxDeployVbMarkLiveYes VersionboxDeployVbMarkLive = "yes"
	VersionboxDeployVbMarkLiveNo  VersionboxDeployVbMarkLive = "no"
)

// VersionboxDeployVbAutoPublish enumerates the valid values for the vb_auto_publish input.
type VersionboxDeployVbAutoPublish string

const (
	VersionboxDeployVbAutoPublishNo  VersionboxDeployVbAutoPublish = "no"
	VersionboxDeployVbAutoPublishYes VersionboxDeployVbAutoPublish = "yes"
)

// VersionboxDeployVbDescriptionFromCommit enumerates the valid values for the vb_description_from_commit input.
type VersionboxDeployVbDescriptionFromCommit string

const (
	VersionboxDeployVbDescriptionFromCommitYes VersionboxDeployVbDescriptionFromCommit = "yes"
	VersionboxDeployVbDescriptionFromCommitNo  VersionboxDeployVbDescriptionFromCommit = "no"
)

// VersionboxDeployBuilder builds a versionbox-deploy step with typed input methods.
type VersionboxDeployBuilder struct{ *Builder }

// VersionboxDeploy creates a versionbox-deploy step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.VersionboxDeploy("0")  // explicit default
//	step.VersionboxDeploy("1")                  // older major
func VersionboxDeploy(version ...string) *VersionboxDeployBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &VersionboxDeployBuilder{Builder: From("versionbox-deploy", v)}
}

// WithVbAppKey sets versionBox Application Key.
func (b *VersionboxDeployBuilder) WithVbAppKey(value string) *VersionboxDeployBuilder {
	b.Builder.WithInput("vb_app_key", value)
	return b
}

// WithVbApiToken sets versionBox User API Token.
func (b *VersionboxDeployBuilder) WithVbApiToken(value string) *VersionboxDeployBuilder {
	b.Builder.WithInput("vb_api_token", value)
	return b
}

// WithVbFilePath sets file Path.
func (b *VersionboxDeployBuilder) WithVbFilePath(value string) *VersionboxDeployBuilder {
	b.Builder.WithInput("vb_file_path", value)
	return b
}

// WithVbMarkLive sets mark as Live.
func (b *VersionboxDeployBuilder) WithVbMarkLive(value VersionboxDeployVbMarkLive) *VersionboxDeployBuilder {
	b.Builder.WithInput("vb_mark_live", string(value))
	return b
}

// WithVbAutoPublish sets publish the Version.
func (b *VersionboxDeployBuilder) WithVbAutoPublish(value VersionboxDeployVbAutoPublish) *VersionboxDeployBuilder {
	b.Builder.WithInput("vb_auto_publish", string(value))
	return b
}

// WithVbVersionDescription sets version Description.
func (b *VersionboxDeployBuilder) WithVbVersionDescription(value string) *VersionboxDeployBuilder {
	b.Builder.WithInput("vb_version_description", value)
	return b
}

// WithVbDescriptionFromCommit sets copy Description From Tag Commits.
func (b *VersionboxDeployBuilder) WithVbDescriptionFromCommit(value VersionboxDeployVbDescriptionFromCommit) *VersionboxDeployBuilder {
	b.Builder.WithInput("vb_description_from_commit", string(value))
	return b
}

// WithVbClonedRepositoryPath sets cloned Repository Path.
func (b *VersionboxDeployBuilder) WithVbClonedRepositoryPath(value string) *VersionboxDeployBuilder {
	b.Builder.WithInput("vb_cloned_repository_path", value)
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *VersionboxDeployBuilder) WithVersion(version string) *VersionboxDeployBuilder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *VersionboxDeployBuilder) WithInput(key, value string) *VersionboxDeployBuilder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *VersionboxDeployBuilder) WithRunIf(expr string) *VersionboxDeployBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *VersionboxDeployBuilder) WithIsAlwaysRun(v bool) *VersionboxDeployBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *VersionboxDeployBuilder) WithIsSkippable(v bool) *VersionboxDeployBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *VersionboxDeployBuilder) WithTitle(title string) *VersionboxDeployBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *VersionboxDeployBuilder) WithTimeout(seconds int) *VersionboxDeployBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *VersionboxDeployBuilder) WithNoOutputTimeout(seconds int) *VersionboxDeployBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *VersionboxDeployBuilder) WithTimeoutDuration(d time.Duration) *VersionboxDeployBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *VersionboxDeployBuilder) WithNoOutputTimeoutDuration(d time.Duration) *VersionboxDeployBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *VersionboxDeployBuilder) WithExecutionContainer(containerID string) *VersionboxDeployBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *VersionboxDeployBuilder) WithServiceContainers(containerIDs ...string) *VersionboxDeployBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
