// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: bitrise-step-export-universal-apk (0.1.4)

package step

// BitriseStepExportUniversalApkBuilder builds a bitrise-step-export-universal-apk step with typed input methods.
type BitriseStepExportUniversalApkBuilder struct{ *Builder }

// BitriseStepExportUniversalApk creates a bitrise-step-export-universal-apk step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.BitriseStepExportUniversalApk("0")  // explicit default
//	step.BitriseStepExportUniversalApk("1")                  // older major
func BitriseStepExportUniversalApk(version ...string) *BitriseStepExportUniversalApkBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &BitriseStepExportUniversalApkBuilder{Builder: From("bitrise-step-export-universal-apk", v)}
}

// WithAabPath sets android App Bundle path.
func (b *BitriseStepExportUniversalApkBuilder) WithAabPath(value string) *BitriseStepExportUniversalApkBuilder {
	b.Builder.WithInput("aab_path", value)
	return b
}

// WithKeystoreUrl sets keystore URL.
func (b *BitriseStepExportUniversalApkBuilder) WithKeystoreUrl(value string) *BitriseStepExportUniversalApkBuilder {
	b.Builder.WithInput("keystore_url", value)
	return b
}

// WithKeystorePassword sets keystore password.
func (b *BitriseStepExportUniversalApkBuilder) WithKeystorePassword(value string) *BitriseStepExportUniversalApkBuilder {
	b.Builder.WithInput("keystore_password", value)
	return b
}

// WithKeystoreAlias sets keystore alias.
func (b *BitriseStepExportUniversalApkBuilder) WithKeystoreAlias(value string) *BitriseStepExportUniversalApkBuilder {
	b.Builder.WithInput("keystore_alias", value)
	return b
}

// WithPrivateKeyPassword sets private key password.
func (b *BitriseStepExportUniversalApkBuilder) WithPrivateKeyPassword(value string) *BitriseStepExportUniversalApkBuilder {
	b.Builder.WithInput("private_key_password", value)
	return b
}

// WithBundletoolVersion sets bundletool version.
func (b *BitriseStepExportUniversalApkBuilder) WithBundletoolVersion(value string) *BitriseStepExportUniversalApkBuilder {
	b.Builder.WithInput("bundletool_version", value)
	return b
}
