// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: jira-issue-field-add-or-update (0.0.2)

package step

import "time"

// JiraIssueFieldAddOrUpdateJiraIssueFieldType enumerates the valid values for the jira_issue_field_type input.
type JiraIssueFieldAddOrUpdateJiraIssueFieldType string

const (
	JiraIssueFieldAddOrUpdateJiraIssueFieldTypeSingle JiraIssueFieldAddOrUpdateJiraIssueFieldType = "single"
	JiraIssueFieldAddOrUpdateJiraIssueFieldTypeArray  JiraIssueFieldAddOrUpdateJiraIssueFieldType = "array"
)

// JiraIssueFieldAddOrUpdateJiraShouldArrayAddOrSet enumerates the valid values for the jira_should_array_add_or_set input.
type JiraIssueFieldAddOrUpdateJiraShouldArrayAddOrSet string

const (
	JiraIssueFieldAddOrUpdateJiraShouldArrayAddOrSetAdd JiraIssueFieldAddOrUpdateJiraShouldArrayAddOrSet = "add"
	JiraIssueFieldAddOrUpdateJiraShouldArrayAddOrSetSet JiraIssueFieldAddOrUpdateJiraShouldArrayAddOrSet = "set"
)

// JiraIssueFieldAddOrUpdateBuilder builds a jira-issue-field-add-or-update step with typed input methods.
type JiraIssueFieldAddOrUpdateBuilder struct{ *Builder }

// JiraIssueFieldAddOrUpdate creates a jira-issue-field-add-or-update step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.JiraIssueFieldAddOrUpdate("0")  // explicit default
//	step.JiraIssueFieldAddOrUpdate("1")                  // older major
func JiraIssueFieldAddOrUpdate(version ...string) *JiraIssueFieldAddOrUpdateBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &JiraIssueFieldAddOrUpdateBuilder{Builder: From("jira-issue-field-add-or-update", v)}
}

// WithProjectPrefix sets jira project prefix.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithProjectPrefix(value string) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithInput("project_prefix", value)
	return b
}

// WithBacklogDefaultUrl sets jira domain.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithBacklogDefaultUrl(value string) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithInput("backlog_default_url", value)
	return b
}

// WithJiraUser sets jira user.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithJiraUser(value string) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithInput("jira_user", value)
	return b
}

// WithJiraToken sets jira user token.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithJiraToken(value string) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithInput("jira_token", value)
	return b
}

// WithJiraIssueFieldName sets jira issue field name.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithJiraIssueFieldName(value string) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithInput("jira_issue_field_name", value)
	return b
}

// WithJiraIssueFieldType sets jira issue field type.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithJiraIssueFieldType(value JiraIssueFieldAddOrUpdateJiraIssueFieldType) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithInput("jira_issue_field_type", string(value))
	return b
}

// WithJiraIssueFieldValue sets jira issue field value to update or add.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithJiraIssueFieldValue(value string) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithInput("jira_issue_field_value", value)
	return b
}

// WithJiraShouldArrayAddOrSet sets if field type is array, should add or set values?.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithJiraShouldArrayAddOrSet(value JiraIssueFieldAddOrUpdateJiraShouldArrayAddOrSet) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithInput("jira_should_array_add_or_set", string(value))
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithVersion(version string) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithInput(key, value string) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithRunIf(expr string) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithIsAlwaysRun(v bool) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithIsSkippable(v bool) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithTitle(title string) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithTimeout(seconds int) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithNoOutputTimeout(seconds int) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithTimeoutDuration(d time.Duration) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithNoOutputTimeoutDuration(d time.Duration) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithExecutionContainer(containerID string) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *JiraIssueFieldAddOrUpdateBuilder) WithServiceContainers(containerIDs ...string) *JiraIssueFieldAddOrUpdateBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
