// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: yarn (1.0.0)

package step

// YarnV1VerboseLog enumerates the valid values for the verbose_log input.
type YarnV1VerboseLog string

const (
	YarnV1VerboseLogYes YarnV1VerboseLog = "yes"
	YarnV1VerboseLogNo  YarnV1VerboseLog = "no"
)

// YarnV1Builder builds a yarn step with typed input methods.
type YarnV1Builder struct{ *Builder }

// YarnV1 creates a yarn step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.YarnV1("1")  // explicit default
//	step.YarnV1("1")                  // older major
func YarnV1(version ...string) *YarnV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &YarnV1Builder{Builder: From("yarn", v)}
}

// WithWorkdir sets working directory.
func (b *YarnV1Builder) WithWorkdir(value string) *YarnV1Builder {
	b.Builder.WithInput("workdir", value)
	return b
}

// WithCommand sets the `yarn` command to run.
func (b *YarnV1Builder) WithCommand(value string) *YarnV1Builder {
	b.Builder.WithInput("command", value)
	return b
}

// WithArgs sets arguments for running `yarn` commands.
func (b *YarnV1Builder) WithArgs(value string) *YarnV1Builder {
	b.Builder.WithInput("args", value)
	return b
}

// WithVerboseLog sets enable verbose logging.
func (b *YarnV1Builder) WithVerboseLog(value YarnV1VerboseLog) *YarnV1Builder {
	b.Builder.WithInput("verbose_log", string(value))
	return b
}
