// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xcuitestbrowserstack (2.0.1)

package step

// XcuitestbrowserstackBuilder is a type alias for XcuitestbrowserstackV2Builder,
// always pointing to the latest supported major version.
// To target a specific major version use XcuitestbrowserstackV{N}() directly.
type XcuitestbrowserstackBuilder = XcuitestbrowserstackV2Builder

// Xcuitestbrowserstack creates a xcuitestbrowserstack step builder at the latest major version (v2).
// To target a specific major version use XcuitestbrowserstackV{N}() directly.
func Xcuitestbrowserstack(version ...string) *XcuitestbrowserstackV2Builder {
	return XcuitestbrowserstackV2(version...)
}
