// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: cache-pull (0.9.4)

package step

// CachePullV0Builder builds a cache-pull step with typed input methods.
//
// Deprecated: The branch-based caching steps are deprecated and being replaced by key-based caching.  Check out our migration guide: [Migrating from branch-based caching to key-based caching](https://devcenter.bitrise.io/en/dependencies-and-caching/branch-based-caching/migrating-from-branch-based-caching-to-key-based-caching.html).
type CachePullV0Builder struct{ *Builder }

// CachePullV0 creates a cache-pull step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.CachePullV0("0")  // explicit default
//	step.CachePullV0("1")                  // older major
//
// Deprecated: The branch-based caching steps are deprecated and being replaced by key-based caching.  Check out our migration guide: [Migrating from branch-based caching to key-based caching](https://devcenter.bitrise.io/en/dependencies-and-caching/branch-based-caching/migrating-from-branch-based-caching-to-key-based-caching.html).
func CachePullV0(version ...string) *CachePullV0Builder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &CachePullV0Builder{Builder: From("cache-pull", v)}
}

// WithWorkdir sets working directory path.
func (b *CachePullV0Builder) WithWorkdir(value string) *CachePullV0Builder {
	b.Builder.WithInput("workdir", value)
	return b
}

// WithIsDebugMode sets debug mode?.
func (b *CachePullV0Builder) WithIsDebugMode(value string) *CachePullV0Builder {
	b.Builder.WithInput("is_debug_mode", value)
	return b
}

// WithCacheApiUrl sets cache API URL.
func (b *CachePullV0Builder) WithCacheApiUrl(value string) *CachePullV0Builder {
	b.Builder.WithInput("cache_api_url", value)
	return b
}
