// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: generate-xcode-html-report (1.1.1)

package step

// GenerateXcodeHtmlReportVerbose enumerates the valid values for the verbose input.
type GenerateXcodeHtmlReportVerbose string

const (
	GenerateXcodeHtmlReportVerboseTrue  GenerateXcodeHtmlReportVerbose = "true"
	GenerateXcodeHtmlReportVerboseFalse GenerateXcodeHtmlReportVerbose = "false"
)

// GenerateXcodeHtmlReportBuilder builds a generate-xcode-html-report step with typed input methods.
type GenerateXcodeHtmlReportBuilder struct{ *Builder }

// GenerateXcodeHtmlReport creates a generate-xcode-html-report step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.GenerateXcodeHtmlReport("1")  // explicit default
//	step.GenerateXcodeHtmlReport("1")                  // older major
func GenerateXcodeHtmlReport(version ...string) *GenerateXcodeHtmlReportBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &GenerateXcodeHtmlReportBuilder{Builder: From("generate-xcode-html-report", v)}
}

// WithXcresultPatterns sets xcresult file paths.
func (b *GenerateXcodeHtmlReportBuilder) WithXcresultPatterns(value string) *GenerateXcodeHtmlReportBuilder {
	b.Builder.WithInput("xcresult_patterns", value)
	return b
}

// WithTestResultDir sets bitrise test result directory.
func (b *GenerateXcodeHtmlReportBuilder) WithTestResultDir(value string) *GenerateXcodeHtmlReportBuilder {
	b.Builder.WithInput("test_result_dir", value)
	return b
}

// WithVerbose sets enable verbose logging.
func (b *GenerateXcodeHtmlReportBuilder) WithVerbose(value GenerateXcodeHtmlReportVerbose) *GenerateXcodeHtmlReportBuilder {
	b.Builder.WithInput("verbose", string(value))
	return b
}

// generateXcodeHtmlReportOutputs holds the names of environment variables published
// by the generate-xcode-html-report step (v1) at run time.
type generateXcodeHtmlReportOutputs struct {
	// BitriseHtmlReportDir is the "Html test report location" output env var.
	BitriseHtmlReportDir string
}

// GenerateXcodeHtmlReportOutputs provides typed access to the environment variable names
// that generate-xcode-html-report (v1) exports after a successful run.
var GenerateXcodeHtmlReportOutputs = generateXcodeHtmlReportOutputs{
	BitriseHtmlReportDir: "BITRISE_HTML_REPORT_DIR",
}
