// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xamarin-test-cloud-for-android (2.3.0)

package step

// XamarinTestCloudForAndroidV2TestCloudIsAsync enumerates the valid values for the test_cloud_is_async input.
type XamarinTestCloudForAndroidV2TestCloudIsAsync string

const (
	XamarinTestCloudForAndroidV2TestCloudIsAsyncYes XamarinTestCloudForAndroidV2TestCloudIsAsync = "yes"
	XamarinTestCloudForAndroidV2TestCloudIsAsyncNo  XamarinTestCloudForAndroidV2TestCloudIsAsync = "no"
)

// XamarinTestCloudForAndroidV2TestCloudParallelization enumerates the valid values for the test_cloud_parallelization input.
type XamarinTestCloudForAndroidV2TestCloudParallelization string

const (
	XamarinTestCloudForAndroidV2TestCloudParallelizationNone          XamarinTestCloudForAndroidV2TestCloudParallelization = "none"
	XamarinTestCloudForAndroidV2TestCloudParallelizationByTestFixture XamarinTestCloudForAndroidV2TestCloudParallelization = "by_test_fixture"
	XamarinTestCloudForAndroidV2TestCloudParallelizationByTestChunk   XamarinTestCloudForAndroidV2TestCloudParallelization = "by_test_chunk"
)

// XamarinTestCloudForAndroidV2BuildTool enumerates the valid values for the build_tool input.
type XamarinTestCloudForAndroidV2BuildTool string

const (
	XamarinTestCloudForAndroidV2BuildToolMsbuild XamarinTestCloudForAndroidV2BuildTool = "msbuild"
	XamarinTestCloudForAndroidV2BuildToolXbuild  XamarinTestCloudForAndroidV2BuildTool = "xbuild"
)

// XamarinTestCloudForAndroidV2Builder builds a xamarin-test-cloud-for-android step with typed input methods.
//
// Deprecated: This step is deprecated, please use [App Center upload and schedule tests](https://github.com/bitrise-steplib/steps-appcenter-test) Step instead.
type XamarinTestCloudForAndroidV2Builder struct{ *Builder }

// XamarinTestCloudForAndroidV2 creates a xamarin-test-cloud-for-android step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.XamarinTestCloudForAndroidV2("2")  // explicit default
//	step.XamarinTestCloudForAndroidV2("1")                  // older major
//
// Deprecated: This step is deprecated, please use [App Center upload and schedule tests](https://github.com/bitrise-steplib/steps-appcenter-test) Step instead.
func XamarinTestCloudForAndroidV2(version ...string) *XamarinTestCloudForAndroidV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &XamarinTestCloudForAndroidV2Builder{Builder: From("xamarin-test-cloud-for-android", v)}
}

// WithXamarinUser sets user email.
func (b *XamarinTestCloudForAndroidV2Builder) WithXamarinUser(value string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithInput("xamarin_user", value)
	return b
}

// WithTestCloudApiKey sets api key.
func (b *XamarinTestCloudForAndroidV2Builder) WithTestCloudApiKey(value string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithInput("test_cloud_api_key", value)
	return b
}

// WithTestCloudDevices sets device selection id.
func (b *XamarinTestCloudForAndroidV2Builder) WithTestCloudDevices(value string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithInput("test_cloud_devices", value)
	return b
}

// WithTestCloudSeries sets test series.
func (b *XamarinTestCloudForAndroidV2Builder) WithTestCloudSeries(value string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithInput("test_cloud_series", value)
	return b
}

// WithXamarinProject sets path to Xamarin Solution.
func (b *XamarinTestCloudForAndroidV2Builder) WithXamarinProject(value string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithInput("xamarin_project", value)
	return b
}

// WithXamarinConfiguration sets xamarin project configuration.
func (b *XamarinTestCloudForAndroidV2Builder) WithXamarinConfiguration(value string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithInput("xamarin_configuration", value)
	return b
}

// WithXamarinPlatform sets xamarin platform.
func (b *XamarinTestCloudForAndroidV2Builder) WithXamarinPlatform(value string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithInput("xamarin_platform", value)
	return b
}

// WithTestCloudIsAsync sets don't wait for cloud test run to complete.
func (b *XamarinTestCloudForAndroidV2Builder) WithTestCloudIsAsync(value XamarinTestCloudForAndroidV2TestCloudIsAsync) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithInput("test_cloud_is_async", string(value))
	return b
}

// WithTestCloudParallelization sets run tests in parallel by method/fixture.
func (b *XamarinTestCloudForAndroidV2Builder) WithTestCloudParallelization(value XamarinTestCloudForAndroidV2TestCloudParallelization) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithInput("test_cloud_parallelization", string(value))
	return b
}

// WithSignParameters sets signing parameters.
func (b *XamarinTestCloudForAndroidV2Builder) WithSignParameters(value string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithInput("sign_parameters", value)
	return b
}

// WithOtherParameters sets other parameters.
func (b *XamarinTestCloudForAndroidV2Builder) WithOtherParameters(value string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithInput("other_parameters", value)
	return b
}

// WithBuildTool sets (Experimental) Which tool to use for building?.
func (b *XamarinTestCloudForAndroidV2Builder) WithBuildTool(value XamarinTestCloudForAndroidV2BuildTool) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithInput("build_tool", string(value))
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *XamarinTestCloudForAndroidV2Builder) WithRunIf(expr string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *XamarinTestCloudForAndroidV2Builder) WithIsAlwaysRun(v bool) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *XamarinTestCloudForAndroidV2Builder) WithIsSkippable(v bool) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *XamarinTestCloudForAndroidV2Builder) WithTitle(title string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *XamarinTestCloudForAndroidV2Builder) WithTimeout(seconds int) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *XamarinTestCloudForAndroidV2Builder) WithNoOutputTimeout(seconds int) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *XamarinTestCloudForAndroidV2Builder) WithExecutionContainer(containerID string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *XamarinTestCloudForAndroidV2Builder) WithServiceContainers(containerIDs ...string) *XamarinTestCloudForAndroidV2Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// xamarinTestCloudForAndroidV2Outputs holds the names of environment variables published
// by the xamarin-test-cloud-for-android step (v2) at run time.
type xamarinTestCloudForAndroidV2Outputs struct {
	// BitriseXamarinTestResult is the "Result of the tests. 'succeeded' or 'failed'." output env var.
	BitriseXamarinTestResult string
	// BitriseXamarinTestFullResultsText is the "Result of the tests." output env var.
	BitriseXamarinTestFullResultsText string
	// BitriseXamarinTestToRunId is the "Test to run ID." output env var.
	BitriseXamarinTestToRunId string
}

// XamarinTestCloudForAndroidV2Outputs provides typed access to the environment variable names
// that xamarin-test-cloud-for-android (v2) exports after a successful run.
var XamarinTestCloudForAndroidV2Outputs = xamarinTestCloudForAndroidV2Outputs{
	BitriseXamarinTestResult:          "BITRISE_XAMARIN_TEST_RESULT",
	BitriseXamarinTestFullResultsText: "BITRISE_XAMARIN_TEST_FULL_RESULTS_TEXT",
	BitriseXamarinTestToRunId:         "BITRISE_XAMARIN_TEST_TO_RUN_ID",
}
