// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: wait-for-android-emulator (1.0.9)

package step

// WaitForAndroidEmulatorBuilder builds a wait-for-android-emulator step with typed input methods.
type WaitForAndroidEmulatorBuilder struct{ *Builder }

// WaitForAndroidEmulator creates a wait-for-android-emulator step builder (v1).
func WaitForAndroidEmulator() *WaitForAndroidEmulatorBuilder {
	return &WaitForAndroidEmulatorBuilder{Builder: From("wait-for-android-emulator", "1")}
}

// WithEmulatorSerial sets emulator serial.
func (b *WaitForAndroidEmulatorBuilder) WithEmulatorSerial(value string) *WaitForAndroidEmulatorBuilder {
	b.Builder.WithInput("emulator_serial", value)
	return b
}

// WithBootTimeout sets waiting timeout (secs).
func (b *WaitForAndroidEmulatorBuilder) WithBootTimeout(value string) *WaitForAndroidEmulatorBuilder {
	b.Builder.WithInput("boot_timeout", value)
	return b
}

// WithAndroidHome sets android SDK path.
func (b *WaitForAndroidEmulatorBuilder) WithAndroidHome(value string) *WaitForAndroidEmulatorBuilder {
	b.Builder.WithInput("android_home", value)
	return b
}
