// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: monitoring-apps-permissions (1.0.4)

package step

import "time"

// MonitoringAppsPermissionsCheckAndroid enumerates the valid values for the check_android input.
type MonitoringAppsPermissionsCheckAndroid string

const (
	MonitoringAppsPermissionsCheckAndroidYes MonitoringAppsPermissionsCheckAndroid = "yes"
	MonitoringAppsPermissionsCheckAndroidNo  MonitoringAppsPermissionsCheckAndroid = "no"
)

// MonitoringAppsPermissionsCheckIos enumerates the valid values for the check_ios input.
type MonitoringAppsPermissionsCheckIos string

const (
	MonitoringAppsPermissionsCheckIosYes MonitoringAppsPermissionsCheckIos = "yes"
	MonitoringAppsPermissionsCheckIosNo  MonitoringAppsPermissionsCheckIos = "no"
)

// MonitoringAppsPermissionsBuilder builds a monitoring-apps-permissions step with typed input methods.
type MonitoringAppsPermissionsBuilder struct{ *Builder }

// MonitoringAppsPermissions creates a monitoring-apps-permissions step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.MonitoringAppsPermissions("1")  // explicit default
//	step.MonitoringAppsPermissions("1")                  // older major
func MonitoringAppsPermissions(version ...string) *MonitoringAppsPermissionsBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &MonitoringAppsPermissionsBuilder{Builder: From("monitoring-apps-permissions", v)}
}

// WithCheckAndroid sets check Android.
func (b *MonitoringAppsPermissionsBuilder) WithCheckAndroid(value MonitoringAppsPermissionsCheckAndroid) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithInput("check_android", string(value))
	return b
}

// WithCheckIos sets check iOS.
func (b *MonitoringAppsPermissionsBuilder) WithCheckIos(value MonitoringAppsPermissionsCheckIos) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithInput("check_ios", string(value))
	return b
}

// WithIosAppName sets iOS app name (Display Name).
func (b *MonitoringAppsPermissionsBuilder) WithIosAppName(value string) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithInput("ios_app_name", value)
	return b
}

// WithConfigFilePath sets config file path.
func (b *MonitoringAppsPermissionsBuilder) WithConfigFilePath(value string) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithInput("config_file_path", value)
	return b
}

// WithAndroidPermissionCount sets android permission.
func (b *MonitoringAppsPermissionsBuilder) WithAndroidPermissionCount(value string) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithInput("android_permission_count", value)
	return b
}

// WithIosPermissionCount sets iOS permission.
func (b *MonitoringAppsPermissionsBuilder) WithIosPermissionCount(value string) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithInput("ios_permission_count", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *MonitoringAppsPermissionsBuilder) WithRunIf(expr string) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *MonitoringAppsPermissionsBuilder) WithIsAlwaysRun(v bool) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *MonitoringAppsPermissionsBuilder) WithIsSkippable(v bool) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *MonitoringAppsPermissionsBuilder) WithTitle(title string) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *MonitoringAppsPermissionsBuilder) WithTimeout(seconds int) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *MonitoringAppsPermissionsBuilder) WithNoOutputTimeout(seconds int) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *MonitoringAppsPermissionsBuilder) WithTimeoutDuration(d time.Duration) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *MonitoringAppsPermissionsBuilder) WithNoOutputTimeoutDuration(d time.Duration) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *MonitoringAppsPermissionsBuilder) WithExecutionContainer(containerID string) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *MonitoringAppsPermissionsBuilder) WithServiceContainers(containerIDs ...string) *MonitoringAppsPermissionsBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// monitoringAppsPermissionsOutputs holds the names of environment variables published
// by the monitoring-apps-permissions step (v1) at run time.
type monitoringAppsPermissionsOutputs struct {
	// IosPermissionCount is the "Current build's ios permission count" output env var.
	IosPermissionCount string
	// AndroidPermissionCount is the "Current build's Android permission count" output env var.
	AndroidPermissionCount string
}

// MonitoringAppsPermissionsOutputs provides typed access to the environment variable names
// that monitoring-apps-permissions (v1) exports after a successful run.
var MonitoringAppsPermissionsOutputs = monitoringAppsPermissionsOutputs{
	IosPermissionCount:     "IOS_PERMISSION_COUNT",
	AndroidPermissionCount: "ANDROID_PERMISSION_COUNT",
}
