// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: cordova-config (0.0.3)

package step

// CordovaConfigBuilder builds a cordova-config step with typed input methods.
type CordovaConfigBuilder struct{ *Builder }

// CordovaConfig creates a cordova-config step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.CordovaConfig("0")  // explicit default
//	step.CordovaConfig("1")                  // older major
func CordovaConfig(version ...string) *CordovaConfigBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &CordovaConfigBuilder{Builder: From("cordova-config", v)}
}

// WithName sets cordova application name.
func (b *CordovaConfigBuilder) WithName(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("name", value)
	return b
}

// WithId sets cordova ID.
func (b *CordovaConfigBuilder) WithId(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("id", value)
	return b
}

// WithAndroidVersionCode sets android version code.
func (b *CordovaConfigBuilder) WithAndroidVersionCode(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("android_version_code", value)
	return b
}

// WithAndroidPackageName sets android package name.
func (b *CordovaConfigBuilder) WithAndroidPackageName(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("android_package_name", value)
	return b
}

// WithIosBundleVersion sets iOS bundle version.
func (b *CordovaConfigBuilder) WithIosBundleVersion(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("ios_bundle_version", value)
	return b
}

// WithIosBundleIdentifier sets iOS bundle identifier.
func (b *CordovaConfigBuilder) WithIosBundleIdentifier(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("ios_bundle_identifier", value)
	return b
}

// WithConfigPath sets cordova config.xml file location.
func (b *CordovaConfigBuilder) WithConfigPath(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("config_path", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *CordovaConfigBuilder) WithRunIf(expr string) *CordovaConfigBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *CordovaConfigBuilder) WithIsAlwaysRun(v bool) *CordovaConfigBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *CordovaConfigBuilder) WithIsSkippable(v bool) *CordovaConfigBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *CordovaConfigBuilder) WithTitle(title string) *CordovaConfigBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *CordovaConfigBuilder) WithTimeout(seconds int) *CordovaConfigBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *CordovaConfigBuilder) WithNoOutputTimeout(seconds int) *CordovaConfigBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *CordovaConfigBuilder) WithExecutionContainer(containerID string) *CordovaConfigBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *CordovaConfigBuilder) WithServiceContainers(containerIDs ...string) *CordovaConfigBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
