// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: swift-package-manager-test-for-mac (0.0.1)

package step

// SwiftPackageManagerTestForMacBuilder builds a swift-package-manager-test-for-mac step with typed input methods.
type SwiftPackageManagerTestForMacBuilder struct{ *Builder }

// SwiftPackageManagerTestForMac creates a swift-package-manager-test-for-mac step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.SwiftPackageManagerTestForMac("0")  // explicit default
//	step.SwiftPackageManagerTestForMac("1")                  // older major
func SwiftPackageManagerTestForMac(version ...string) *SwiftPackageManagerTestForMacBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &SwiftPackageManagerTestForMacBuilder{Builder: From("swift-package-manager-test-for-mac", v)}
}

// WithBuildPath sets build Path.
func (b *SwiftPackageManagerTestForMacBuilder) WithBuildPath(value string) *SwiftPackageManagerTestForMacBuilder {
	b.Builder.WithInput("build_path", value)
	return b
}

// WithIsSkipBuild sets skip build.
func (b *SwiftPackageManagerTestForMacBuilder) WithIsSkipBuild(value string) *SwiftPackageManagerTestForMacBuilder {
	b.Builder.WithInput("is_skip_build", value)
	return b
}

// WithIsParallel sets parallel test.
func (b *SwiftPackageManagerTestForMacBuilder) WithIsParallel(value string) *SwiftPackageManagerTestForMacBuilder {
	b.Builder.WithInput("is_parallel", value)
	return b
}
