// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: waldo-upload (2.4.1)

package step

// WaldoUploadV2Builder builds a waldo-upload step with typed input methods.
type WaldoUploadV2Builder struct{ *Builder }

// WaldoUploadV2 creates a waldo-upload step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.WaldoUploadV2("2")  // explicit default
//	step.WaldoUploadV2("1")                  // older major
func WaldoUploadV2(version ...string) *WaldoUploadV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &WaldoUploadV2Builder{Builder: From("waldo-upload", v)}
}

// WithBuildPath sets build path.
func (b *WaldoUploadV2Builder) WithBuildPath(value string) *WaldoUploadV2Builder {
	b.Builder.WithInput("build_path", value)
	return b
}

// WithUploadToken sets upload token.
func (b *WaldoUploadV2Builder) WithUploadToken(value string) *WaldoUploadV2Builder {
	b.Builder.WithInput("upload_token", value)
	return b
}

// WithVariantName sets variant name.
func (b *WaldoUploadV2Builder) WithVariantName(value string) *WaldoUploadV2Builder {
	b.Builder.WithInput("variant_name", value)
	return b
}

// WithGitCommit sets git commit.
func (b *WaldoUploadV2Builder) WithGitCommit(value string) *WaldoUploadV2Builder {
	b.Builder.WithInput("git_commit", value)
	return b
}

// WithGitBranch sets git branch.
func (b *WaldoUploadV2Builder) WithGitBranch(value string) *WaldoUploadV2Builder {
	b.Builder.WithInput("git_branch", value)
	return b
}

// WithIsDebugMode sets debug mode?.
func (b *WaldoUploadV2Builder) WithIsDebugMode(value string) *WaldoUploadV2Builder {
	b.Builder.WithInput("is_debug_mode", value)
	return b
}

// waldoUploadV2Outputs holds the names of environment variables published
// by the waldo-upload step (v2) at run time.
type waldoUploadV2Outputs struct {
	// WaldoBuildId is the "Build ID" output env var.
	WaldoBuildId string
}

// WaldoUploadV2Outputs provides typed access to the environment variable names
// that waldo-upload (v2) exports after a successful run.
var WaldoUploadV2Outputs = waldoUploadV2Outputs{
	WaldoBuildId: "WALDO_BUILD_ID",
}
