// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: bitrise-step-qyrus-mobility-test-runner-android (0.0.2)

package step

import "time"

// BitriseStepQyrusMobilityTestRunnerAndroidEnableDebug enumerates the valid values for the enable_debug input.
type BitriseStepQyrusMobilityTestRunnerAndroidEnableDebug string

const (
	BitriseStepQyrusMobilityTestRunnerAndroidEnableDebugYes BitriseStepQyrusMobilityTestRunnerAndroidEnableDebug = "yes"
	BitriseStepQyrusMobilityTestRunnerAndroidEnableDebugNo  BitriseStepQyrusMobilityTestRunnerAndroidEnableDebug = "no"
)

// BitriseStepQyrusMobilityTestRunnerAndroidUploadApp enumerates the valid values for the upload_app input.
type BitriseStepQyrusMobilityTestRunnerAndroidUploadApp string

const (
	BitriseStepQyrusMobilityTestRunnerAndroidUploadAppYes BitriseStepQyrusMobilityTestRunnerAndroidUploadApp = "yes"
	BitriseStepQyrusMobilityTestRunnerAndroidUploadAppNo  BitriseStepQyrusMobilityTestRunnerAndroidUploadApp = "no"
)

// BitriseStepQyrusMobilityTestRunnerAndroidBuilder builds a bitrise-step-qyrus-mobility-test-runner-android step with typed input methods.
type BitriseStepQyrusMobilityTestRunnerAndroidBuilder struct{ *Builder }

// BitriseStepQyrusMobilityTestRunnerAndroid creates a bitrise-step-qyrus-mobility-test-runner-android step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.BitriseStepQyrusMobilityTestRunnerAndroid("0")  // explicit default
//	step.BitriseStepQyrusMobilityTestRunnerAndroid("1")                  // older major
func BitriseStepQyrusMobilityTestRunnerAndroid(version ...string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &BitriseStepQyrusMobilityTestRunnerAndroidBuilder{Builder: From("bitrise-step-qyrus-mobility-test-runner-android", v)}
}

// WithEnableDebug sets debug mode.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithEnableDebug(value BitriseStepQyrusMobilityTestRunnerAndroidEnableDebug) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithInput("enable_debug", string(value))
	return b
}

// WithUploadApp sets upload app.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithUploadApp(value BitriseStepQyrusMobilityTestRunnerAndroidUploadApp) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithInput("upload_app", string(value))
	return b
}

// WithGatewayUrl sets gateway URL.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithGatewayUrl(value string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithInput("gateway_url", value)
	return b
}

// WithUploadPath sets a Bitrise generated APK or IPA path.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithUploadPath(value string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithInput("upload_path", value)
	return b
}

// WithQyrusUsername sets qyrus Username.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithQyrusUsername(value string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithInput("qyrus_username", value)
	return b
}

// WithQyrusPassword sets qyrus Password.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithQyrusPassword(value string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithInput("qyrus_password", value)
	return b
}

// WithQyrusTeamName sets qyrus Team Name.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithQyrusTeamName(value string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithInput("qyrus_team_name", value)
	return b
}

// WithQyrusProjectName sets qyrus Project Name.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithQyrusProjectName(value string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithInput("qyrus_project_name", value)
	return b
}

// WithQyrusSuiteName sets qyrus Suite Name.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithQyrusSuiteName(value string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithInput("qyrus_suite_name", value)
	return b
}

// WithAppActivity sets app Activity.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithAppActivity(value string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithInput("app_activity", value)
	return b
}

// WithBundleId sets bundle Id.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithBundleId(value string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithInput("bundle_id", value)
	return b
}

// WithDevicePoolName sets device_pool_name.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithDevicePoolName(value string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithInput("device_pool_name", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithRunIf(expr string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithIsAlwaysRun(v bool) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithIsSkippable(v bool) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithTitle(title string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithTimeout(seconds int) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithNoOutputTimeout(seconds int) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithTimeoutDuration(d time.Duration) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithNoOutputTimeoutDuration(d time.Duration) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithExecutionContainer(containerID string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *BitriseStepQyrusMobilityTestRunnerAndroidBuilder) WithServiceContainers(containerIDs ...string) *BitriseStepQyrusMobilityTestRunnerAndroidBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// bitriseStepQyrusMobilityTestRunnerAndroidOutputs holds the names of environment variables published
// by the bitrise-step-qyrus-mobility-test-runner-android step (v0) at run time.
type bitriseStepQyrusMobilityTestRunnerAndroidOutputs struct {
	// QyrusTestReportUrl is the "Qyrus report download url" output env var.
	QyrusTestReportUrl string
}

// BitriseStepQyrusMobilityTestRunnerAndroidOutputs provides typed access to the environment variable names
// that bitrise-step-qyrus-mobility-test-runner-android (v0) exports after a successful run.
var BitriseStepQyrusMobilityTestRunnerAndroidOutputs = bitriseStepQyrusMobilityTestRunnerAndroidOutputs{
	QyrusTestReportUrl: "QYRUS_TEST_REPORT_URL",
}
