// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: lambdatest-upload (1.0.0)

package step

// LambdatestUploadV1Builder builds a lambdatest-upload step with typed input methods.
type LambdatestUploadV1Builder struct{ *Builder }

// LambdatestUploadV1 creates a lambdatest-upload step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.LambdatestUploadV1("1")  // explicit default
//	step.LambdatestUploadV1("1")                  // older major
func LambdatestUploadV1(version ...string) *LambdatestUploadV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &LambdatestUploadV1Builder{Builder: From("lambdatest-upload", v)}
}

// WithUploadPath sets a Bitrise generated APK or IPA path.
func (b *LambdatestUploadV1Builder) WithUploadPath(value string) *LambdatestUploadV1Builder {
	b.Builder.WithInput("upload_path", value)
	return b
}

// WithLambdatestUsername sets lambdaTest username.
func (b *LambdatestUploadV1Builder) WithLambdatestUsername(value string) *LambdatestUploadV1Builder {
	b.Builder.WithInput("lambdatest_username", value)
	return b
}

// WithLambdatestAccessKey sets lambdaTest access key.
func (b *LambdatestUploadV1Builder) WithLambdatestAccessKey(value string) *LambdatestUploadV1Builder {
	b.Builder.WithInput("lambdatest_access_key", value)
	return b
}

// WithCustomId sets custom Id.
func (b *LambdatestUploadV1Builder) WithCustomId(value string) *LambdatestUploadV1Builder {
	b.Builder.WithInput("custom_id", value)
	return b
}
