// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: chuck-norris (1.0.1)

package step

// ChuckNorrisBuilder builds a chuck-norris step with typed input methods.
type ChuckNorrisBuilder struct{ *Builder }

// ChuckNorris creates a chuck-norris step builder (v1).
func ChuckNorris() *ChuckNorrisBuilder {
	return &ChuckNorrisBuilder{Builder: From("chuck-norris", "1")}
}

// WithCategory sets joke category, optional..
func (b *ChuckNorrisBuilder) WithCategory(value string) *ChuckNorrisBuilder {
	b.Builder.WithInput("category", value)
	return b
}

// WithApiBaseUrl sets aPI base URL.
func (b *ChuckNorrisBuilder) WithApiBaseUrl(value string) *ChuckNorrisBuilder {
	b.Builder.WithInput("api_base_url", value)
	return b
}
