// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: docker-build-push (1.0.1)

package step

// DockerBuildPushBuilder builds a docker-build-push step with typed input methods.
type DockerBuildPushBuilder struct{ *Builder }

// DockerBuildPush creates a docker-build-push step builder (v1).
func DockerBuildPush(version ...string) *DockerBuildPushBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &DockerBuildPushBuilder{Builder: From("docker-build-push", v)}
}

// WithTags sets image tags.
func (b *DockerBuildPushBuilder) WithTags(value string) *DockerBuildPushBuilder {
	b.Builder.WithInput("tags", value)
	return b
}

// WithContext sets build context path.
func (b *DockerBuildPushBuilder) WithContext(value string) *DockerBuildPushBuilder {
	b.Builder.WithInput("context", value)
	return b
}

// WithFile sets dockerfile path.
func (b *DockerBuildPushBuilder) WithFile(value string) *DockerBuildPushBuilder {
	b.Builder.WithInput("file", value)
	return b
}

// WithPush sets push docker image.
func (b *DockerBuildPushBuilder) WithPush(value string) *DockerBuildPushBuilder {
	b.Builder.WithInput("push", value)
	return b
}

// WithUseBitriseCache sets use Bitrise key-value cache.
func (b *DockerBuildPushBuilder) WithUseBitriseCache(value string) *DockerBuildPushBuilder {
	b.Builder.WithInput("use_bitrise_cache", value)
	return b
}

// WithBuildArg sets build arguments.
func (b *DockerBuildPushBuilder) WithBuildArg(value string) *DockerBuildPushBuilder {
	b.Builder.WithInput("build_arg", value)
	return b
}

// WithCacheFrom sets cache from arguments.
func (b *DockerBuildPushBuilder) WithCacheFrom(value string) *DockerBuildPushBuilder {
	b.Builder.WithInput("cache_from", value)
	return b
}

// WithCacheTo sets cache to arguments.
func (b *DockerBuildPushBuilder) WithCacheTo(value string) *DockerBuildPushBuilder {
	b.Builder.WithInput("cache_to", value)
	return b
}

// WithExtraOptions sets extra options.
func (b *DockerBuildPushBuilder) WithExtraOptions(value string) *DockerBuildPushBuilder {
	b.Builder.WithInput("extra_options", value)
	return b
}

// WithBuildxHostNetwork sets enables to use the host network with the buildkit build container.
func (b *DockerBuildPushBuilder) WithBuildxHostNetwork(value string) *DockerBuildPushBuilder {
	b.Builder.WithInput("buildx_host_network", value)
	return b
}

// WithVerbose sets verbose logging.
func (b *DockerBuildPushBuilder) WithVerbose(value string) *DockerBuildPushBuilder {
	b.Builder.WithInput("verbose", value)
	return b
}
