// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: expo-detach (1.1.0)

package step

// ExpoDetachBuilder builds a expo-detach step with typed input methods.
type ExpoDetachBuilder struct{ *Builder }

// ExpoDetach creates a expo-detach step builder (v1).
func ExpoDetach(version ...string) *ExpoDetachBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ExpoDetachBuilder{Builder: From("expo-detach", v)}
}

// WithProjectPath sets working directory.
func (b *ExpoDetachBuilder) WithProjectPath(value string) *ExpoDetachBuilder {
	b.Builder.WithInput("project_path", value)
	return b
}

// WithExpoCliVerson sets expo CLI version.
func (b *ExpoDetachBuilder) WithExpoCliVerson(value string) *ExpoDetachBuilder {
	b.Builder.WithInput("expo_cli_verson", value)
	return b
}

// WithUserName sets username for Expo.
func (b *ExpoDetachBuilder) WithUserName(value string) *ExpoDetachBuilder {
	b.Builder.WithInput("user_name", value)
	return b
}

// WithPassword sets password for your Expo account.
func (b *ExpoDetachBuilder) WithPassword(value string) *ExpoDetachBuilder {
	b.Builder.WithInput("password", value)
	return b
}

// WithRunPublish sets run expo publish after eject?.
func (b *ExpoDetachBuilder) WithRunPublish(value string) *ExpoDetachBuilder {
	b.Builder.WithInput("run_publish", value)
	return b
}

// WithOverrideReactNativeVersion sets react Native version to set in package.json.
func (b *ExpoDetachBuilder) WithOverrideReactNativeVersion(value string) *ExpoDetachBuilder {
	b.Builder.WithInput("override_react_native_version", value)
	return b
}
