// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: embrace-symbol-upload (1.0.0)

package step

// EmbraceSymbolUploadBuilder builds a embrace-symbol-upload step with typed input methods.
type EmbraceSymbolUploadBuilder struct{ *Builder }

// EmbraceSymbolUpload creates a embrace-symbol-upload step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.EmbraceSymbolUpload("1")  // explicit default
//	step.EmbraceSymbolUpload("1")                  // older major
func EmbraceSymbolUpload(version ...string) *EmbraceSymbolUploadBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &EmbraceSymbolUploadBuilder{Builder: From("embrace-symbol-upload", v)}
}

// WithEmbraceApp sets embrace App ID.
func (b *EmbraceSymbolUploadBuilder) WithEmbraceApp(value string) *EmbraceSymbolUploadBuilder {
	b.Builder.WithInput("embrace_app", value)
	return b
}

// WithEmbraceApiToken sets embrace API Token.
func (b *EmbraceSymbolUploadBuilder) WithEmbraceApiToken(value string) *EmbraceSymbolUploadBuilder {
	b.Builder.WithInput("embrace_api_token", value)
	return b
}

// WithDsymPath sets dSYM Path.
func (b *EmbraceSymbolUploadBuilder) WithDsymPath(value string) *EmbraceSymbolUploadBuilder {
	b.Builder.WithInput("dsym_path", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *EmbraceSymbolUploadBuilder) WithRunIf(expr string) *EmbraceSymbolUploadBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *EmbraceSymbolUploadBuilder) WithIsAlwaysRun(v bool) *EmbraceSymbolUploadBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *EmbraceSymbolUploadBuilder) WithIsSkippable(v bool) *EmbraceSymbolUploadBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *EmbraceSymbolUploadBuilder) WithTitle(title string) *EmbraceSymbolUploadBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *EmbraceSymbolUploadBuilder) WithTimeout(seconds int) *EmbraceSymbolUploadBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *EmbraceSymbolUploadBuilder) WithNoOutputTimeout(seconds int) *EmbraceSymbolUploadBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *EmbraceSymbolUploadBuilder) WithExecutionContainer(containerID string) *EmbraceSymbolUploadBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *EmbraceSymbolUploadBuilder) WithServiceContainers(containerIDs ...string) *EmbraceSymbolUploadBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
