// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: restore-dart-cache (2.1.2)

package step

// RestoreDartCacheV2Builder builds a restore-dart-cache step with typed input methods.
type RestoreDartCacheV2Builder struct{ *Builder }

// RestoreDartCacheV2 creates a restore-dart-cache step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.RestoreDartCacheV2("2")  // explicit default
//	step.RestoreDartCacheV2("1")                  // older major
func RestoreDartCacheV2(version ...string) *RestoreDartCacheV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &RestoreDartCacheV2Builder{Builder: From("restore-dart-cache", v)}
}

// WithVerbose sets verbose logging.
func (b *RestoreDartCacheV2Builder) WithVerbose(value string) *RestoreDartCacheV2Builder {
	b.Builder.WithInput("verbose", value)
	return b
}

// WithRetries sets number of retries.
func (b *RestoreDartCacheV2Builder) WithRetries(value string) *RestoreDartCacheV2Builder {
	b.Builder.WithInput("retries", value)
	return b
}
