// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: appcenter-app-release (1.0.5)

package step

// AppcenterAppReleaseBuilder builds a appcenter-app-release step with typed input methods.
//
// Deprecated: This step is no longer maintained by its author.  It's recommended to use the new AppCenter steps created and maintained by Bitrise: - For iOS, use the [AppCenter iOS Deploy](https://github.com/bitrise-steplib/steps-appcenter-deploy-ios) Step instead - For Android, use the [AppCenter Android Deploy](https://github.com/bitrise-steplib/steps-appcenter-deploy-android) Step instead
type AppcenterAppReleaseBuilder struct{ *Builder }

// AppcenterAppRelease creates a appcenter-app-release step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.AppcenterAppRelease("1")  // explicit default
//	step.AppcenterAppRelease("1")                  // older major
//
// Deprecated: This step is no longer maintained by its author.  It's recommended to use the new AppCenter steps created and maintained by Bitrise: - For iOS, use the [AppCenter iOS Deploy](https://github.com/bitrise-steplib/steps-appcenter-deploy-ios) Step instead - For Android, use the [AppCenter Android Deploy](https://github.com/bitrise-steplib/steps-appcenter-deploy-android) Step instead
func AppcenterAppRelease(version ...string) *AppcenterAppReleaseBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &AppcenterAppReleaseBuilder{Builder: From("appcenter-app-release", v)}
}

// WithAppcenterApiToken sets appCenter API Token.
func (b *AppcenterAppReleaseBuilder) WithAppcenterApiToken(value string) *AppcenterAppReleaseBuilder {
	b.Builder.WithInput("appcenter_api_token", value)
	return b
}

// WithAppcenterName sets appCenter Application Name.
func (b *AppcenterAppReleaseBuilder) WithAppcenterName(value string) *AppcenterAppReleaseBuilder {
	b.Builder.WithInput("appcenter_name", value)
	return b
}

// WithAppcenterOrg sets appCenter Organization.
func (b *AppcenterAppReleaseBuilder) WithAppcenterOrg(value string) *AppcenterAppReleaseBuilder {
	b.Builder.WithInput("appcenter_org", value)
	return b
}

// WithArtifactPath sets path to the built application file (.ipa or .apk).
func (b *AppcenterAppReleaseBuilder) WithArtifactPath(value string) *AppcenterAppReleaseBuilder {
	b.Builder.WithInput("artifact_path", value)
	return b
}

// WithDistributionGroups sets appCenter distribution groups.
func (b *AppcenterAppReleaseBuilder) WithDistributionGroups(value string) *AppcenterAppReleaseBuilder {
	b.Builder.WithInput("distribution_groups", value)
	return b
}

// WithMandatoryUpdate sets appCenter Mandatory Update flag.
func (b *AppcenterAppReleaseBuilder) WithMandatoryUpdate(value string) *AppcenterAppReleaseBuilder {
	b.Builder.WithInput("mandatory_update", value)
	return b
}

// WithNotifyTesters sets notify testers?.
func (b *AppcenterAppReleaseBuilder) WithNotifyTesters(value string) *AppcenterAppReleaseBuilder {
	b.Builder.WithInput("notify_testers", value)
	return b
}

// WithReleaseNotes sets uploaded build related release notes.
func (b *AppcenterAppReleaseBuilder) WithReleaseNotes(value string) *AppcenterAppReleaseBuilder {
	b.Builder.WithInput("release_notes", value)
	return b
}

// appcenterAppReleaseOutputs holds the names of environment variables published
// by the appcenter-app-release step (v1) at run time.
type appcenterAppReleaseOutputs struct {
	// AppcenterDownloadUrl is the "Download URL from AppCenter" output env var.
	AppcenterDownloadUrl string
}

// AppcenterAppReleaseOutputs provides typed access to the environment variable names
// that appcenter-app-release (v1) exports after a successful run.
var AppcenterAppReleaseOutputs = appcenterAppReleaseOutputs{
	AppcenterDownloadUrl: "APPCENTER_DOWNLOAD_URL",
}
