// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: restore-cocoapods-cache (2.1.3)

package step

import "time"

// RestoreCocoapodsCacheV2Verbose enumerates the valid values for the verbose input.
type RestoreCocoapodsCacheV2Verbose string

const (
	RestoreCocoapodsCacheV2VerboseTrue  RestoreCocoapodsCacheV2Verbose = "true"
	RestoreCocoapodsCacheV2VerboseFalse RestoreCocoapodsCacheV2Verbose = "false"
)

// RestoreCocoapodsCacheV2Builder builds a restore-cocoapods-cache step with typed input methods.
type RestoreCocoapodsCacheV2Builder struct{ *Builder }

// RestoreCocoapodsCacheV2 creates a restore-cocoapods-cache step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.RestoreCocoapodsCacheV2("2")  // explicit default
//	step.RestoreCocoapodsCacheV2("1")                  // older major
func RestoreCocoapodsCacheV2(version ...string) *RestoreCocoapodsCacheV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &RestoreCocoapodsCacheV2Builder{Builder: From("restore-cocoapods-cache", v)}
}

// WithVerbose sets verbose logging.
func (b *RestoreCocoapodsCacheV2Builder) WithVerbose(value RestoreCocoapodsCacheV2Verbose) *RestoreCocoapodsCacheV2Builder {
	b.Builder.WithInput("verbose", string(value))
	return b
}

// WithRetries sets number of retries.
func (b *RestoreCocoapodsCacheV2Builder) WithRetries(value string) *RestoreCocoapodsCacheV2Builder {
	b.Builder.WithInput("retries", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *RestoreCocoapodsCacheV2Builder) WithRunIf(expr string) *RestoreCocoapodsCacheV2Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *RestoreCocoapodsCacheV2Builder) WithIsAlwaysRun(v bool) *RestoreCocoapodsCacheV2Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *RestoreCocoapodsCacheV2Builder) WithIsSkippable(v bool) *RestoreCocoapodsCacheV2Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *RestoreCocoapodsCacheV2Builder) WithTitle(title string) *RestoreCocoapodsCacheV2Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *RestoreCocoapodsCacheV2Builder) WithTimeout(seconds int) *RestoreCocoapodsCacheV2Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *RestoreCocoapodsCacheV2Builder) WithNoOutputTimeout(seconds int) *RestoreCocoapodsCacheV2Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *RestoreCocoapodsCacheV2Builder) WithTimeoutDuration(d time.Duration) *RestoreCocoapodsCacheV2Builder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *RestoreCocoapodsCacheV2Builder) WithNoOutputTimeoutDuration(d time.Duration) *RestoreCocoapodsCacheV2Builder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *RestoreCocoapodsCacheV2Builder) WithExecutionContainer(containerID string) *RestoreCocoapodsCacheV2Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *RestoreCocoapodsCacheV2Builder) WithServiceContainers(containerIDs ...string) *RestoreCocoapodsCacheV2Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// restoreCocoapodsCacheV2Outputs holds the names of environment variables published
// by the restore-cocoapods-cache step (v2) at run time.
type restoreCocoapodsCacheV2Outputs struct {
	// BitriseCacheHit is the "Cache hit" output env var.
	BitriseCacheHit string
}

// RestoreCocoapodsCacheV2Outputs provides typed access to the environment variable names
// that restore-cocoapods-cache (v2) exports after a successful run.
var RestoreCocoapodsCacheV2Outputs = restoreCocoapodsCacheV2Outputs{
	BitriseCacheHit: "BITRISE_CACHE_HIT",
}
