// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xctest-html-report (0.2.1)

package step

// XctestHtmlReportV0GenerateJunit enumerates the valid values for the generate_junit input.
type XctestHtmlReportV0GenerateJunit string

const (
	XctestHtmlReportV0GenerateJunitYes XctestHtmlReportV0GenerateJunit = "yes"
	XctestHtmlReportV0GenerateJunitNo  XctestHtmlReportV0GenerateJunit = "no"
)

// XctestHtmlReportV0InstallBranch enumerates the valid values for the install_branch input.
type XctestHtmlReportV0InstallBranch string

const (
	XctestHtmlReportV0InstallBranchDevelop XctestHtmlReportV0InstallBranch = "develop"
	XctestHtmlReportV0InstallBranchMaster  XctestHtmlReportV0InstallBranch = "master"
)

// XctestHtmlReportV0Verbose enumerates the valid values for the verbose input.
type XctestHtmlReportV0Verbose string

const (
	XctestHtmlReportV0VerboseYes XctestHtmlReportV0Verbose = "yes"
	XctestHtmlReportV0VerboseNo  XctestHtmlReportV0Verbose = "no"
)

// XctestHtmlReportV0Builder builds a xctest-html-report step with typed input methods.
//
// Deprecated: This step is no longer maintained. To generate HTML reports from xcresult files use the new official Bitrise step: "Generate Xcode test report html" (https://devcenter.bitrise.io/en/testing/testing-ios-apps/viewing-xcode-test-results-in-rich-html-format.html).
type XctestHtmlReportV0Builder struct{ *Builder }

// XctestHtmlReportV0 creates a xctest-html-report step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.XctestHtmlReportV0("0")  // explicit default
//	step.XctestHtmlReportV0("1")                  // older major
//
// Deprecated: This step is no longer maintained. To generate HTML reports from xcresult files use the new official Bitrise step: "Generate Xcode test report html" (https://devcenter.bitrise.io/en/testing/testing-ios-apps/viewing-xcode-test-results-in-rich-html-format.html).
func XctestHtmlReportV0(version ...string) *XctestHtmlReportV0Builder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &XctestHtmlReportV0Builder{Builder: From("xctest-html-report", v)}
}

// WithTestResultPath sets xcode test result (.xctesresult) paths.
func (b *XctestHtmlReportV0Builder) WithTestResultPath(value string) *XctestHtmlReportV0Builder {
	b.Builder.WithInput("test_result_path", value)
	return b
}

// WithGenerateJunit sets generate JUnit report?.
func (b *XctestHtmlReportV0Builder) WithGenerateJunit(value XctestHtmlReportV0GenerateJunit) *XctestHtmlReportV0Builder {
	b.Builder.WithInput("generate_junit", string(value))
	return b
}

// WithOutputDir sets output directory path.
func (b *XctestHtmlReportV0Builder) WithOutputDir(value string) *XctestHtmlReportV0Builder {
	b.Builder.WithInput("output_dir", value)
	return b
}

// WithInstallBranch sets install branch of XCTestHTMLReport.
func (b *XctestHtmlReportV0Builder) WithInstallBranch(value XctestHtmlReportV0InstallBranch) *XctestHtmlReportV0Builder {
	b.Builder.WithInput("install_branch", string(value))
	return b
}

// WithVerbose sets enable verbose log?.
func (b *XctestHtmlReportV0Builder) WithVerbose(value XctestHtmlReportV0Verbose) *XctestHtmlReportV0Builder {
	b.Builder.WithInput("verbose", string(value))
	return b
}

// xctestHtmlReportV0Outputs holds the names of environment variables published
// by the xctest-html-report step (v0) at run time.
type xctestHtmlReportV0Outputs struct {
	// XcHtmlReport is the "The path of the generated `HTML report`. Which was exported to the output\\_dir ( $BITRISE\\_DEPLOY\\_DIR by default )" output env var.
	XcHtmlReport string
	// XcJunitReport is the "The path of the generated `JUnit report`. Which was exported to the output\\_dir ( $BITRISE\\_DEPLOY\\_DIR by default )" output env var.
	XcJunitReport string
}

// XctestHtmlReportV0Outputs provides typed access to the environment variable names
// that xctest-html-report (v0) exports after a successful run.
var XctestHtmlReportV0Outputs = xctestHtmlReportV0Outputs{
	XcHtmlReport:  "XC_HTML_REPORT",
	XcJunitReport: "XC_JUNIT_REPORT",
}
