// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: codecov (1.1.6)

package step

// CodecovV1Builder builds a codecov step with typed input methods.
type CodecovV1Builder struct{ *Builder }

// CodecovV1 creates a codecov step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.CodecovV1("1")  // explicit default
//	step.CodecovV1("1")                  // older major
func CodecovV1(version ...string) *CodecovV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &CodecovV1Builder{Builder: From("codecov", v)}
}

// WithCODECOVTOKEN sets codecov.io token.
func (b *CodecovV1Builder) WithCODECOVTOKEN(value string) *CodecovV1Builder {
	b.Builder.WithInput("CODECOV_TOKEN", value)
	return b
}

// WithOtherOptions sets additional options for Codecov call.
func (b *CodecovV1Builder) WithOtherOptions(value string) *CodecovV1Builder {
	b.Builder.WithInput("other_options", value)
	return b
}
