// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: smart-qa (0.0.2)

package step

// SmartQaBuilder builds a smart-qa step with typed input methods.
type SmartQaBuilder struct{ *Builder }

// SmartQa creates a smart-qa step builder (v0).
func SmartQa() *SmartQaBuilder {
	return &SmartQaBuilder{Builder: From("smart-qa", "0")}
}

// WithBuildPath sets build Path.
func (b *SmartQaBuilder) WithBuildPath(value string) *SmartQaBuilder {
	b.Builder.WithInput("build_path", value)
	return b
}

// WithApiKey sets aPI KEY.
func (b *SmartQaBuilder) WithApiKey(value string) *SmartQaBuilder {
	b.Builder.WithInput("api_key", value)
	return b
}
