// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: generate-image-difference (0.0.2)

package step

// GenerateImageDifferenceBuilder builds a generate-image-difference step with typed input methods.
type GenerateImageDifferenceBuilder struct{ *Builder }

// GenerateImageDifference creates a generate-image-difference step builder (v0).
func GenerateImageDifference(version ...string) *GenerateImageDifferenceBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &GenerateImageDifferenceBuilder{Builder: From("generate-image-difference", v)}
}

// WithBeforeImages sets before images path.
func (b *GenerateImageDifferenceBuilder) WithBeforeImages(value string) *GenerateImageDifferenceBuilder {
	b.Builder.WithInput("before_images", value)
	return b
}

// WithAfterImages sets after images path.
func (b *GenerateImageDifferenceBuilder) WithAfterImages(value string) *GenerateImageDifferenceBuilder {
	b.Builder.WithInput("after_images", value)
	return b
}
