// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: cordova-ios (0.1.0)

package step

// CordovaIosCordovaCommand enumerates the valid values for the cordova_command input.
type CordovaIosCordovaCommand string

const (
	CordovaIosCordovaCommandBuild       CordovaIosCordovaCommand = "build"
	CordovaIosCordovaCommandPlatformAdd CordovaIosCordovaCommand = "platform add"
)

// CordovaIosIsDebug enumerates the valid values for the is_debug input.
type CordovaIosIsDebug string

const (
	CordovaIosIsDebugNo  CordovaIosIsDebug = "no"
	CordovaIosIsDebugYes CordovaIosIsDebug = "yes"
)

// CordovaIosBuilder builds a cordova-ios step with typed input methods.
type CordovaIosBuilder struct{ *Builder }

// CordovaIos creates a cordova-ios step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.CordovaIos("0")  // explicit default
//	step.CordovaIos("1")                  // older major
func CordovaIos(version ...string) *CordovaIosBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &CordovaIosBuilder{Builder: From("cordova-ios", v)}
}

// WithCordovaDir sets the directory of the Cordova application..
func (b *CordovaIosBuilder) WithCordovaDir(value string) *CordovaIosBuilder {
	b.Builder.WithInput("cordova_dir", value)
	return b
}

// WithCordovaCommand sets cordova command to run..
func (b *CordovaIosBuilder) WithCordovaCommand(value CordovaIosCordovaCommand) *CordovaIosBuilder {
	b.Builder.WithInput("cordova_command", string(value))
	return b
}

// WithPlatformName sets platform to build..
func (b *CordovaIosBuilder) WithPlatformName(value string) *CordovaIosBuilder {
	b.Builder.WithInput("platform_name", value)
	return b
}

// WithBuildOptions sets additional options for `cordova` command.
func (b *CordovaIosBuilder) WithBuildOptions(value string) *CordovaIosBuilder {
	b.Builder.WithInput("build_options", value)
	return b
}

// WithIsDebug sets debug?.
func (b *CordovaIosBuilder) WithIsDebug(value CordovaIosIsDebug) *CordovaIosBuilder {
	b.Builder.WithInput("is_debug", string(value))
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *CordovaIosBuilder) WithRunIf(expr string) *CordovaIosBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *CordovaIosBuilder) WithIsAlwaysRun(v bool) *CordovaIosBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *CordovaIosBuilder) WithIsSkippable(v bool) *CordovaIosBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *CordovaIosBuilder) WithTitle(title string) *CordovaIosBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *CordovaIosBuilder) WithTimeout(seconds int) *CordovaIosBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *CordovaIosBuilder) WithNoOutputTimeout(seconds int) *CordovaIosBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *CordovaIosBuilder) WithExecutionContainer(containerID string) *CordovaIosBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *CordovaIosBuilder) WithServiceContainers(containerIDs ...string) *CordovaIosBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
