// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: timestamp (0.9.1)

package step

// TimestampBuilder builds a timestamp step with typed input methods.
type TimestampBuilder struct{ *Builder }

// Timestamp creates a timestamp step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.Timestamp("0")  // explicit default
//	step.Timestamp("1")                  // older major
func Timestamp(version ...string) *TimestampBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &TimestampBuilder{Builder: From("timestamp", v)}
}

// WithRunIf overrides the run_if expression for this step.
func (b *TimestampBuilder) WithRunIf(expr string) *TimestampBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *TimestampBuilder) WithIsAlwaysRun(v bool) *TimestampBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *TimestampBuilder) WithIsSkippable(v bool) *TimestampBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *TimestampBuilder) WithTitle(title string) *TimestampBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *TimestampBuilder) WithTimeout(seconds int) *TimestampBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *TimestampBuilder) WithNoOutputTimeout(seconds int) *TimestampBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *TimestampBuilder) WithExecutionContainer(containerID string) *TimestampBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *TimestampBuilder) WithServiceContainers(containerIDs ...string) *TimestampBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// timestampOutputs holds the names of environment variables published
// by the timestamp step (v0) at run time.
type timestampOutputs struct {
	// UnixTimestamp is the "unix style" output env var.
	UnixTimestamp string
	// IsoDatetime is the "iso 8601 (RFC3339Nano)" output env var.
	IsoDatetime string
}

// TimestampOutputs provides typed access to the environment variable names
// that timestamp (v0) exports after a successful run.
var TimestampOutputs = timestampOutputs{
	UnixTimestamp: "UNIX_TIMESTAMP",
	IsoDatetime:   "ISO_DATETIME",
}
