// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: restore-cocoapods-cache (1.1.1)

package step

// RestoreCocoapodsCacheV1Builder builds a restore-cocoapods-cache step with typed input methods.
type RestoreCocoapodsCacheV1Builder struct{ *Builder }

// RestoreCocoapodsCacheV1 creates a restore-cocoapods-cache step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.RestoreCocoapodsCacheV1("1")  // explicit default
//	step.RestoreCocoapodsCacheV1("1")                  // older major
func RestoreCocoapodsCacheV1(version ...string) *RestoreCocoapodsCacheV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &RestoreCocoapodsCacheV1Builder{Builder: From("restore-cocoapods-cache", v)}
}

// WithVerbose sets verbose logging.
func (b *RestoreCocoapodsCacheV1Builder) WithVerbose(value string) *RestoreCocoapodsCacheV1Builder {
	b.Builder.WithInput("verbose", value)
	return b
}
