// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: ionic-archive (0.10.0)

package step

// IonicArchiveV0Builder builds a ionic-archive step with typed input methods.
type IonicArchiveV0Builder struct{ *Builder }

// IonicArchiveV0 creates a ionic-archive step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.IonicArchiveV0("0")  // explicit default
//	step.IonicArchiveV0("1")                  // older major
func IonicArchiveV0(version ...string) *IonicArchiveV0Builder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &IonicArchiveV0Builder{Builder: From("ionic-archive", v)}
}

// WithPlatform sets platform to use in ionic-cli commands.
func (b *IonicArchiveV0Builder) WithPlatform(value string) *IonicArchiveV0Builder {
	b.Builder.WithInput("platform", value)
	return b
}

// WithConfiguration sets build command configuration.
func (b *IonicArchiveV0Builder) WithConfiguration(value string) *IonicArchiveV0Builder {
	b.Builder.WithInput("configuration", value)
	return b
}

// WithTarget sets build command target.
func (b *IonicArchiveV0Builder) WithTarget(value string) *IonicArchiveV0Builder {
	b.Builder.WithInput("target", value)
	return b
}

// WithBuildConfig sets build configuration path, to describe code signing properties.
func (b *IonicArchiveV0Builder) WithBuildConfig(value string) *IonicArchiveV0Builder {
	b.Builder.WithInput("build_config", value)
	return b
}

// WithOptions sets options to append to the ionic-cli build command.
func (b *IonicArchiveV0Builder) WithOptions(value string) *IonicArchiveV0Builder {
	b.Builder.WithInput("options", value)
	return b
}

// WithIonicUsername sets ionic username.
func (b *IonicArchiveV0Builder) WithIonicUsername(value string) *IonicArchiveV0Builder {
	b.Builder.WithInput("ionic_username", value)
	return b
}

// WithIonicPassword sets ionic password.
func (b *IonicArchiveV0Builder) WithIonicPassword(value string) *IonicArchiveV0Builder {
	b.Builder.WithInput("ionic_password", value)
	return b
}

// WithCordovaVersion sets cordova version.
func (b *IonicArchiveV0Builder) WithCordovaVersion(value string) *IonicArchiveV0Builder {
	b.Builder.WithInput("cordova_version", value)
	return b
}

// WithIonicVersion sets ionic version.
func (b *IonicArchiveV0Builder) WithIonicVersion(value string) *IonicArchiveV0Builder {
	b.Builder.WithInput("ionic_version", value)
	return b
}

// WithWorkdir sets working directory.
func (b *IonicArchiveV0Builder) WithWorkdir(value string) *IonicArchiveV0Builder {
	b.Builder.WithInput("workdir", value)
	return b
}
