// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: export-ios-to-lingohub (0.0.2)

package step

import "time"

// ExportIosToLingohubBuilder builds a export-ios-to-lingohub step with typed input methods.
type ExportIosToLingohubBuilder struct{ *Builder }

// ExportIosToLingohub creates a export-ios-to-lingohub step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.ExportIosToLingohub("0")  // explicit default
//	step.ExportIosToLingohub("1")                  // older major
func ExportIosToLingohub(version ...string) *ExportIosToLingohubBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ExportIosToLingohubBuilder{Builder: From("export-ios-to-lingohub", v)}
}

// WithLingohubIosAccount sets account.
func (b *ExportIosToLingohubBuilder) WithLingohubIosAccount(value string) *ExportIosToLingohubBuilder {
	b.Builder.WithInput("lingohub_ios_account", value)
	return b
}

// WithLingohubIosProjectName sets project.
func (b *ExportIosToLingohubBuilder) WithLingohubIosProjectName(value string) *ExportIosToLingohubBuilder {
	b.Builder.WithInput("lingohub_ios_project_name", value)
	return b
}

// WithLingohubIosToken sets auth Token.
func (b *ExportIosToLingohubBuilder) WithLingohubIosToken(value string) *ExportIosToLingohubBuilder {
	b.Builder.WithInput("lingohub_ios_token", value)
	return b
}

// WithLingohubIosUploadLanguage sets upload Language.
func (b *ExportIosToLingohubBuilder) WithLingohubIosUploadLanguage(value string) *ExportIosToLingohubBuilder {
	b.Builder.WithInput("lingohub_ios_upload_language", value)
	return b
}

// WithLingohubIosProjectPath sets project Path.
func (b *ExportIosToLingohubBuilder) WithLingohubIosProjectPath(value string) *ExportIosToLingohubBuilder {
	b.Builder.WithInput("lingohub_ios_project_path", value)
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *ExportIosToLingohubBuilder) WithVersion(version string) *ExportIosToLingohubBuilder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *ExportIosToLingohubBuilder) WithInput(key, value string) *ExportIosToLingohubBuilder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *ExportIosToLingohubBuilder) WithRunIf(expr string) *ExportIosToLingohubBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *ExportIosToLingohubBuilder) WithIsAlwaysRun(v bool) *ExportIosToLingohubBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *ExportIosToLingohubBuilder) WithIsSkippable(v bool) *ExportIosToLingohubBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *ExportIosToLingohubBuilder) WithTitle(title string) *ExportIosToLingohubBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *ExportIosToLingohubBuilder) WithTimeout(seconds int) *ExportIosToLingohubBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *ExportIosToLingohubBuilder) WithNoOutputTimeout(seconds int) *ExportIosToLingohubBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *ExportIosToLingohubBuilder) WithTimeoutDuration(d time.Duration) *ExportIosToLingohubBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *ExportIosToLingohubBuilder) WithNoOutputTimeoutDuration(d time.Duration) *ExportIosToLingohubBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *ExportIosToLingohubBuilder) WithExecutionContainer(containerID string) *ExportIosToLingohubBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *ExportIosToLingohubBuilder) WithServiceContainers(containerIDs ...string) *ExportIosToLingohubBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
