// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: azure-devops-status (1.0.1)

package step

// AzureDevopsStatusDevopsCommitState enumerates the valid values for the devops_commit_state input.
type AzureDevopsStatusDevopsCommitState string

const (
	AzureDevopsStatusDevopsCommitStateAuto          AzureDevopsStatusDevopsCommitState = "auto"
	AzureDevopsStatusDevopsCommitStatePending       AzureDevopsStatusDevopsCommitState = "pending"
	AzureDevopsStatusDevopsCommitStateSucceeded     AzureDevopsStatusDevopsCommitState = "succeeded"
	AzureDevopsStatusDevopsCommitStateFailed        AzureDevopsStatusDevopsCommitState = "failed"
	AzureDevopsStatusDevopsCommitStateError         AzureDevopsStatusDevopsCommitState = "error"
	AzureDevopsStatusDevopsCommitStateNotSet        AzureDevopsStatusDevopsCommitState = "notSet"
	AzureDevopsStatusDevopsCommitStateNotApplicable AzureDevopsStatusDevopsCommitState = "notApplicable"
)

// AzureDevopsStatusBuilder builds a azure-devops-status step with typed input methods.
type AzureDevopsStatusBuilder struct{ *Builder }

// AzureDevopsStatus creates a azure-devops-status step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.AzureDevopsStatus("1")  // explicit default
//	step.AzureDevopsStatus("1")                  // older major
func AzureDevopsStatus(version ...string) *AzureDevopsStatusBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &AzureDevopsStatusBuilder{Builder: From("azure-devops-status", v)}
}

// WithDevopsUser sets azure DevOps user name.
func (b *AzureDevopsStatusBuilder) WithDevopsUser(value string) *AzureDevopsStatusBuilder {
	b.Builder.WithInput("devops_user", value)
	return b
}

// WithDevopsPat sets azure DevOps Personal Access Token.
func (b *AzureDevopsStatusBuilder) WithDevopsPat(value string) *AzureDevopsStatusBuilder {
	b.Builder.WithInput("devops_pat", value)
	return b
}

// WithDevopsOrganization sets azure DevOps organization.
func (b *AzureDevopsStatusBuilder) WithDevopsOrganization(value string) *AzureDevopsStatusBuilder {
	b.Builder.WithInput("devops_organization", value)
	return b
}

// WithDevopsProject sets azure DevOps project.
func (b *AzureDevopsStatusBuilder) WithDevopsProject(value string) *AzureDevopsStatusBuilder {
	b.Builder.WithInput("devops_project", value)
	return b
}

// WithDevopsRepositoryId sets azure DevOps repository ID.
func (b *AzureDevopsStatusBuilder) WithDevopsRepositoryId(value string) *AzureDevopsStatusBuilder {
	b.Builder.WithInput("devops_repository_id", value)
	return b
}

// WithDevopsCommitState sets commit status.
func (b *AzureDevopsStatusBuilder) WithDevopsCommitState(value AzureDevopsStatusDevopsCommitState) *AzureDevopsStatusBuilder {
	b.Builder.WithInput("devops_commit_state", string(value))
	return b
}

// WithDevopsDescription sets commit status description.
func (b *AzureDevopsStatusBuilder) WithDevopsDescription(value string) *AzureDevopsStatusBuilder {
	b.Builder.WithInput("devops_description", value)
	return b
}

// WithDevopsTargetUrl sets target URL.
func (b *AzureDevopsStatusBuilder) WithDevopsTargetUrl(value string) *AzureDevopsStatusBuilder {
	b.Builder.WithInput("devops_target_url", value)
	return b
}

// WithDevopsContextName sets name identifier.
func (b *AzureDevopsStatusBuilder) WithDevopsContextName(value string) *AzureDevopsStatusBuilder {
	b.Builder.WithInput("devops_context_name", value)
	return b
}

// WithDevopsContextGenre sets status genre.
func (b *AzureDevopsStatusBuilder) WithDevopsContextGenre(value string) *AzureDevopsStatusBuilder {
	b.Builder.WithInput("devops_context_genre", value)
	return b
}
