// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: autify-upload (1.1.0)

package step

// AutifyUploadBuilder builds a autify-upload step with typed input methods.
type AutifyUploadBuilder struct{ *Builder }

// AutifyUpload creates a autify-upload step builder (v1).
func AutifyUpload(version ...string) *AutifyUploadBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &AutifyUploadBuilder{Builder: From("autify-upload", v)}
}

// WithAccessToken sets access token of Autify for Mobile.
func (b *AutifyUploadBuilder) WithAccessToken(value string) *AutifyUploadBuilder {
	b.Builder.WithInput("access_token", value)
	return b
}

// WithWorkspaceId sets workspace ID to upload.
func (b *AutifyUploadBuilder) WithWorkspaceId(value string) *AutifyUploadBuilder {
	b.Builder.WithInput("workspace_id", value)
	return b
}

// WithBuildPath sets build path to upload.
func (b *AutifyUploadBuilder) WithBuildPath(value string) *AutifyUploadBuilder {
	b.Builder.WithInput("build_path", value)
	return b
}

// WithAutifyPath sets a path to Autify CLI.
func (b *AutifyUploadBuilder) WithAutifyPath(value string) *AutifyUploadBuilder {
	b.Builder.WithInput("autify_path", value)
	return b
}

// WithAutifyCliInstallerUrl sets autify CLI installer URL.
func (b *AutifyUploadBuilder) WithAutifyCliInstallerUrl(value string) *AutifyUploadBuilder {
	b.Builder.WithInput("autify_cli_installer_url", value)
	return b
}
