// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: post-jira-comment-with-build-details (1.1.1)

package step

// PostJiraCommentWithBuildDetailsV1Builder builds a post-jira-comment-with-build-details step with typed input methods.
type PostJiraCommentWithBuildDetailsV1Builder struct{ *Builder }

// PostJiraCommentWithBuildDetailsV1 creates a post-jira-comment-with-build-details step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.PostJiraCommentWithBuildDetailsV1("1")  // explicit default
//	step.PostJiraCommentWithBuildDetailsV1("1")                  // older major
func PostJiraCommentWithBuildDetailsV1(version ...string) *PostJiraCommentWithBuildDetailsV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &PostJiraCommentWithBuildDetailsV1Builder{Builder: From("post-jira-comment-with-build-details", v)}
}

// WithUserName sets jira user name.
func (b *PostJiraCommentWithBuildDetailsV1Builder) WithUserName(value string) *PostJiraCommentWithBuildDetailsV1Builder {
	b.Builder.WithInput("user_name", value)
	return b
}

// WithApiToken sets jira API token.
func (b *PostJiraCommentWithBuildDetailsV1Builder) WithApiToken(value string) *PostJiraCommentWithBuildDetailsV1Builder {
	b.Builder.WithInput("api_token", value)
	return b
}

// WithIssueKeys sets jira issue keys.
func (b *PostJiraCommentWithBuildDetailsV1Builder) WithIssueKeys(value string) *PostJiraCommentWithBuildDetailsV1Builder {
	b.Builder.WithInput("issue_keys", value)
	return b
}

// WithBaseUrl sets jira base URL.
func (b *PostJiraCommentWithBuildDetailsV1Builder) WithBaseUrl(value string) *PostJiraCommentWithBuildDetailsV1Builder {
	b.Builder.WithInput("base_url", value)
	return b
}

// WithBuildMessage sets build message.
func (b *PostJiraCommentWithBuildDetailsV1Builder) WithBuildMessage(value string) *PostJiraCommentWithBuildDetailsV1Builder {
	b.Builder.WithInput("build_message", value)
	return b
}
