// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: manage-ios-code-signing (2.2.3)

package step

import "time"

// ManageIosCodeSigningV2AppleServiceConnection enumerates the valid values for the apple_service_connection input.
type ManageIosCodeSigningV2AppleServiceConnection string

const (
	ManageIosCodeSigningV2AppleServiceConnectionApiKey  ManageIosCodeSigningV2AppleServiceConnection = "api-key"
	ManageIosCodeSigningV2AppleServiceConnectionAppleId ManageIosCodeSigningV2AppleServiceConnection = "apple-id"
)

// ManageIosCodeSigningV2DistributionMethod enumerates the valid values for the distribution_method input.
type ManageIosCodeSigningV2DistributionMethod string

const (
	ManageIosCodeSigningV2DistributionMethodDevelopment ManageIosCodeSigningV2DistributionMethod = "development"
	ManageIosCodeSigningV2DistributionMethodAppStore    ManageIosCodeSigningV2DistributionMethod = "app-store"
	ManageIosCodeSigningV2DistributionMethodAdHoc       ManageIosCodeSigningV2DistributionMethod = "ad-hoc"
	ManageIosCodeSigningV2DistributionMethodEnterprise  ManageIosCodeSigningV2DistributionMethod = "enterprise"
)

// ManageIosCodeSigningV2SignUitestTargets enumerates the valid values for the sign_uitest_targets input.
type ManageIosCodeSigningV2SignUitestTargets string

const (
	ManageIosCodeSigningV2SignUitestTargetsYes ManageIosCodeSigningV2SignUitestTargets = "yes"
	ManageIosCodeSigningV2SignUitestTargetsNo  ManageIosCodeSigningV2SignUitestTargets = "no"
)

// ManageIosCodeSigningV2RegisterTestDevices enumerates the valid values for the register_test_devices input.
type ManageIosCodeSigningV2RegisterTestDevices string

const (
	ManageIosCodeSigningV2RegisterTestDevicesYes ManageIosCodeSigningV2RegisterTestDevices = "yes"
	ManageIosCodeSigningV2RegisterTestDevicesNo  ManageIosCodeSigningV2RegisterTestDevices = "no"
)

// ManageIosCodeSigningV2ApiKeyEnterpriseAccount enumerates the valid values for the api_key_enterprise_account input.
type ManageIosCodeSigningV2ApiKeyEnterpriseAccount string

const (
	ManageIosCodeSigningV2ApiKeyEnterpriseAccountYes ManageIosCodeSigningV2ApiKeyEnterpriseAccount = "yes"
	ManageIosCodeSigningV2ApiKeyEnterpriseAccountNo  ManageIosCodeSigningV2ApiKeyEnterpriseAccount = "no"
)

// ManageIosCodeSigningV2VerboseLog enumerates the valid values for the verbose_log input.
type ManageIosCodeSigningV2VerboseLog string

const (
	ManageIosCodeSigningV2VerboseLogYes ManageIosCodeSigningV2VerboseLog = "yes"
	ManageIosCodeSigningV2VerboseLogNo  ManageIosCodeSigningV2VerboseLog = "no"
)

// ManageIosCodeSigningV2Builder builds a manage-ios-code-signing step with typed input methods.
//
// v1→v2: added `api_key_enterprise_account`, `fallback_provisioning_profile_url_list`
type ManageIosCodeSigningV2Builder struct{ *Builder }

// ManageIosCodeSigningV2 creates a manage-ios-code-signing step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.ManageIosCodeSigningV2("2")  // explicit default
//	step.ManageIosCodeSigningV2("1")                  // older major
//
// v1→v2: added `api_key_enterprise_account`, `fallback_provisioning_profile_url_list`
func ManageIosCodeSigningV2(version ...string) *ManageIosCodeSigningV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ManageIosCodeSigningV2Builder{Builder: From("manage-ios-code-signing", v)}
}

// WithAppleServiceConnection sets apple service connection method.
func (b *ManageIosCodeSigningV2Builder) WithAppleServiceConnection(value ManageIosCodeSigningV2AppleServiceConnection) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("apple_service_connection", string(value))
	return b
}

// WithDistributionMethod sets distribution method.
func (b *ManageIosCodeSigningV2Builder) WithDistributionMethod(value ManageIosCodeSigningV2DistributionMethod) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("distribution_method", string(value))
	return b
}

// WithProjectPath sets project path.
func (b *ManageIosCodeSigningV2Builder) WithProjectPath(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("project_path", value)
	return b
}

// WithScheme sets scheme.
func (b *ManageIosCodeSigningV2Builder) WithScheme(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("scheme", value)
	return b
}

// WithConfiguration sets build Configuration.
func (b *ManageIosCodeSigningV2Builder) WithConfiguration(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("configuration", value)
	return b
}

// WithSignUitestTargets sets ensure code signing assets for UITest targets too.
func (b *ManageIosCodeSigningV2Builder) WithSignUitestTargets(value ManageIosCodeSigningV2SignUitestTargets) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("sign_uitest_targets", string(value))
	return b
}

// WithRegisterTestDevices sets register test devices on the Apple Developer Portal.
func (b *ManageIosCodeSigningV2Builder) WithRegisterTestDevices(value ManageIosCodeSigningV2RegisterTestDevices) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("register_test_devices", string(value))
	return b
}

// WithMinProfileValidity sets the minimum days the Provisioning Profile should be valid.
func (b *ManageIosCodeSigningV2Builder) WithMinProfileValidity(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("min_profile_validity", value)
	return b
}

// WithAppleTeamId sets developer Portal team ID.
func (b *ManageIosCodeSigningV2Builder) WithAppleTeamId(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("apple_team_id", value)
	return b
}

// WithFallbackProvisioningProfileUrlList sets fallback provisioning profile URLs.
func (b *ManageIosCodeSigningV2Builder) WithFallbackProvisioningProfileUrlList(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("fallback_provisioning_profile_url_list", value)
	return b
}

// WithCertificateUrlList sets code signing certificate URL.
func (b *ManageIosCodeSigningV2Builder) WithCertificateUrlList(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("certificate_url_list", value)
	return b
}

// WithPassphraseList sets code signing certificate passphrase.
func (b *ManageIosCodeSigningV2Builder) WithPassphraseList(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("passphrase_list", value)
	return b
}

// WithKeychainPath sets keychain path.
func (b *ManageIosCodeSigningV2Builder) WithKeychainPath(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("keychain_path", value)
	return b
}

// WithKeychainPassword sets keychain password.
func (b *ManageIosCodeSigningV2Builder) WithKeychainPassword(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("keychain_password", value)
	return b
}

// WithBuildUrl sets bitrise build URL.
func (b *ManageIosCodeSigningV2Builder) WithBuildUrl(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("build_url", value)
	return b
}

// WithBuildApiToken sets bitrise build API token.
func (b *ManageIosCodeSigningV2Builder) WithBuildApiToken(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("build_api_token", value)
	return b
}

// WithApiKeyPath sets app Store Connect API private key.
func (b *ManageIosCodeSigningV2Builder) WithApiKeyPath(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("api_key_path", value)
	return b
}

// WithApiKeyId sets app Store Connect API key ID.
func (b *ManageIosCodeSigningV2Builder) WithApiKeyId(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("api_key_id", value)
	return b
}

// WithApiKeyIssuerId sets app Store Connect API issuer ID.
func (b *ManageIosCodeSigningV2Builder) WithApiKeyIssuerId(value string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("api_key_issuer_id", value)
	return b
}

// WithApiKeyEnterpriseAccount sets app Store Connect API enterprise account.
func (b *ManageIosCodeSigningV2Builder) WithApiKeyEnterpriseAccount(value ManageIosCodeSigningV2ApiKeyEnterpriseAccount) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("api_key_enterprise_account", string(value))
	return b
}

// WithVerboseLog sets verbose logging.
func (b *ManageIosCodeSigningV2Builder) WithVerboseLog(value ManageIosCodeSigningV2VerboseLog) *ManageIosCodeSigningV2Builder {
	b.Builder.WithInput("verbose_log", string(value))
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *ManageIosCodeSigningV2Builder) WithRunIf(expr string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *ManageIosCodeSigningV2Builder) WithIsAlwaysRun(v bool) *ManageIosCodeSigningV2Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *ManageIosCodeSigningV2Builder) WithIsSkippable(v bool) *ManageIosCodeSigningV2Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *ManageIosCodeSigningV2Builder) WithTitle(title string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *ManageIosCodeSigningV2Builder) WithTimeout(seconds int) *ManageIosCodeSigningV2Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *ManageIosCodeSigningV2Builder) WithNoOutputTimeout(seconds int) *ManageIosCodeSigningV2Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *ManageIosCodeSigningV2Builder) WithTimeoutDuration(d time.Duration) *ManageIosCodeSigningV2Builder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *ManageIosCodeSigningV2Builder) WithNoOutputTimeoutDuration(d time.Duration) *ManageIosCodeSigningV2Builder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *ManageIosCodeSigningV2Builder) WithExecutionContainer(containerID string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *ManageIosCodeSigningV2Builder) WithServiceContainers(containerIDs ...string) *ManageIosCodeSigningV2Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// manageIosCodeSigningV2Outputs holds the names of environment variables published
// by the manage-ios-code-signing step (v2) at run time.
type manageIosCodeSigningV2Outputs struct {
	// BitriseExportMethod is the "The selected distribution type" output env var.
	BitriseExportMethod string
	// BitriseDeveloperTeam is the "The development team's ID" output env var.
	BitriseDeveloperTeam string
	// BitriseDevelopmentCodesignIdentity is the "The development codesign identity's name" output env var.
	BitriseDevelopmentCodesignIdentity string
	// BitriseProductionCodesignIdentity is the "The production codesign identity's name" output env var.
	BitriseProductionCodesignIdentity string
	// BitriseDevelopmentProfile is the "The main target's development provisioning profile UUID" output env var.
	BitriseDevelopmentProfile string
	// BitriseProductionProfile is the "The main target's production provisioning profile UUID" output env var.
	BitriseProductionProfile string
}

// ManageIosCodeSigningV2Outputs provides typed access to the environment variable names
// that manage-ios-code-signing (v2) exports after a successful run.
var ManageIosCodeSigningV2Outputs = manageIosCodeSigningV2Outputs{
	BitriseExportMethod:                "BITRISE_EXPORT_METHOD",
	BitriseDeveloperTeam:               "BITRISE_DEVELOPER_TEAM",
	BitriseDevelopmentCodesignIdentity: "BITRISE_DEVELOPMENT_CODESIGN_IDENTITY",
	BitriseProductionCodesignIdentity:  "BITRISE_PRODUCTION_CODESIGN_IDENTITY",
	BitriseDevelopmentProfile:          "BITRISE_DEVELOPMENT_PROFILE",
	BitriseProductionProfile:           "BITRISE_PRODUCTION_PROFILE",
}
