// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: data-theorem-mobile-secure (1.2.0)

package step

// DataTheoremMobileSecureV1Builder builds a data-theorem-mobile-secure step with typed input methods.
type DataTheoremMobileSecureV1Builder struct{ *Builder }

// DataTheoremMobileSecureV1 creates a data-theorem-mobile-secure step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.DataTheoremMobileSecureV1("1")  // explicit default
//	step.DataTheoremMobileSecureV1("1")                  // older major
func DataTheoremMobileSecureV1(version ...string) *DataTheoremMobileSecureV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &DataTheoremMobileSecureV1Builder{Builder: From("data-theorem-mobile-secure", v)}
}

// WithFilePath sets file path to the APK or IPA to upload.
func (b *DataTheoremMobileSecureV1Builder) WithFilePath(value string) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithInput("file_path", value)
	return b
}

// WithDtUploadApiKey sets data Theorem Upload API Key.
func (b *DataTheoremMobileSecureV1Builder) WithDtUploadApiKey(value string) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithInput("dt_upload_api_key", value)
	return b
}

// WithSourcemap sets android mapping file.
func (b *DataTheoremMobileSecureV1Builder) WithSourcemap(value string) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithInput("sourcemap", value)
	return b
}
