// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: carthage (2.4.0)

package step

// CarthageV2Builder builds a carthage step with typed input methods.
type CarthageV2Builder struct{ *Builder }

// CarthageV2 creates a carthage step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.CarthageV2("2")  // explicit default
//	step.CarthageV2("1")                  // older major
func CarthageV2(version ...string) *CarthageV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &CarthageV2Builder{Builder: From("carthage", v)}
}

// WithGithubAccessToken sets github Personal Access Token.
func (b *CarthageV2Builder) WithGithubAccessToken(value string) *CarthageV2Builder {
	b.Builder.WithInput("github_access_token", value)
	return b
}

// WithCarthageCommand sets carthage command to run.
func (b *CarthageV2Builder) WithCarthageCommand(value string) *CarthageV2Builder {
	b.Builder.WithInput("carthage_command", value)
	return b
}

// WithNoUseBinaries sets set no use binaries flag.
func (b *CarthageV2Builder) WithNoUseBinaries(value string) *CarthageV2Builder {
	b.Builder.WithInput("no_use_binaries", value)
	return b
}

// WithVerboseOutput sets set verbose output flag.
func (b *CarthageV2Builder) WithVerboseOutput(value string) *CarthageV2Builder {
	b.Builder.WithInput("verbose_output", value)
	return b
}

// WithSshOutput sets set ssh flag.
func (b *CarthageV2Builder) WithSshOutput(value string) *CarthageV2Builder {
	b.Builder.WithInput("ssh_output", value)
	return b
}

// WithWorkingDir sets working directory.
func (b *CarthageV2Builder) WithWorkingDir(value string) *CarthageV2Builder {
	b.Builder.WithInput("working_dir", value)
	return b
}

// WithPlatform sets platform.
func (b *CarthageV2Builder) WithPlatform(value string) *CarthageV2Builder {
	b.Builder.WithInput("platform", value)
	return b
}

// WithCarthageOptions sets additional options for `carthage` command.
func (b *CarthageV2Builder) WithCarthageOptions(value string) *CarthageV2Builder {
	b.Builder.WithInput("carthage_options", value)
	return b
}
