// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: data-theorem-mobile-secure (1.2.0)

package step

// DataTheoremMobileSecureBuilder builds a data-theorem-mobile-secure step with typed input methods.
type DataTheoremMobileSecureBuilder struct{ *Builder }

// DataTheoremMobileSecure creates a data-theorem-mobile-secure step builder (v1).
func DataTheoremMobileSecure() *DataTheoremMobileSecureBuilder {
	return &DataTheoremMobileSecureBuilder{Builder: From("data-theorem-mobile-secure", "1")}
}

// WithFilePath sets file path to the APK or IPA to upload.
func (b *DataTheoremMobileSecureBuilder) WithFilePath(value string) *DataTheoremMobileSecureBuilder {
	b.Builder.WithInput("file_path", value)
	return b
}

// WithDtUploadApiKey sets data Theorem Upload API Key.
func (b *DataTheoremMobileSecureBuilder) WithDtUploadApiKey(value string) *DataTheoremMobileSecureBuilder {
	b.Builder.WithInput("dt_upload_api_key", value)
	return b
}

// WithSourcemap sets android mapping file.
func (b *DataTheoremMobileSecureBuilder) WithSourcemap(value string) *DataTheoremMobileSecureBuilder {
	b.Builder.WithInput("sourcemap", value)
	return b
}
