// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: firebase-dsym-upload (2.0.1)

package step

// FirebaseDsymUploadV2FduLogging enumerates the valid values for the fdu_logging input.
type FirebaseDsymUploadV2FduLogging string

const (
	FirebaseDsymUploadV2FduLoggingYes FirebaseDsymUploadV2FduLogging = "yes"
	FirebaseDsymUploadV2FduLoggingNo  FirebaseDsymUploadV2FduLogging = "no"
)

// FirebaseDsymUploadV2Builder builds a firebase-dsym-upload step with typed input methods.
type FirebaseDsymUploadV2Builder struct{ *Builder }

// FirebaseDsymUploadV2 creates a firebase-dsym-upload step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.FirebaseDsymUploadV2("2")  // explicit default
//	step.FirebaseDsymUploadV2("1")                  // older major
func FirebaseDsymUploadV2(version ...string) *FirebaseDsymUploadV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &FirebaseDsymUploadV2Builder{Builder: From("firebase-dsym-upload", v)}
}

// WithFduFabricLocation sets location of FirebaseCrashlytics.
func (b *FirebaseDsymUploadV2Builder) WithFduFabricLocation(value string) *FirebaseDsymUploadV2Builder {
	b.Builder.WithInput("fdu_fabric_location", value)
	return b
}

// WithFduGoogleServicesLocation sets location of your GoogleService-Info.plist.
func (b *FirebaseDsymUploadV2Builder) WithFduGoogleServicesLocation(value string) *FirebaseDsymUploadV2Builder {
	b.Builder.WithInput("fdu_google_services_location", value)
	return b
}

// WithFduDsymLocation sets location of the bitrise dSYMs.
func (b *FirebaseDsymUploadV2Builder) WithFduDsymLocation(value string) *FirebaseDsymUploadV2Builder {
	b.Builder.WithInput("fdu_dsym_location", value)
	return b
}

// WithFduLogging sets show additional logging.
func (b *FirebaseDsymUploadV2Builder) WithFduLogging(value FirebaseDsymUploadV2FduLogging) *FirebaseDsymUploadV2Builder {
	b.Builder.WithInput("fdu_logging", string(value))
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *FirebaseDsymUploadV2Builder) WithRunIf(expr string) *FirebaseDsymUploadV2Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *FirebaseDsymUploadV2Builder) WithIsAlwaysRun(v bool) *FirebaseDsymUploadV2Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *FirebaseDsymUploadV2Builder) WithIsSkippable(v bool) *FirebaseDsymUploadV2Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *FirebaseDsymUploadV2Builder) WithTitle(title string) *FirebaseDsymUploadV2Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *FirebaseDsymUploadV2Builder) WithTimeout(seconds int) *FirebaseDsymUploadV2Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *FirebaseDsymUploadV2Builder) WithNoOutputTimeout(seconds int) *FirebaseDsymUploadV2Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *FirebaseDsymUploadV2Builder) WithExecutionContainer(containerID string) *FirebaseDsymUploadV2Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *FirebaseDsymUploadV2Builder) WithServiceContainers(containerIDs ...string) *FirebaseDsymUploadV2Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
