// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: cordova-android (0.9.2)

package step

// CordovaAndroidBuilder builds a cordova-android step with typed input methods.
type CordovaAndroidBuilder struct{ *Builder }

// CordovaAndroid creates a cordova-android step builder (v0).
func CordovaAndroid() *CordovaAndroidBuilder {
	return &CordovaAndroidBuilder{Builder: From("cordova-android", "0")}
}

// WithCordovaCommand sets cordova command to run..
func (b *CordovaAndroidBuilder) WithCordovaCommand(value string) *CordovaAndroidBuilder {
	b.Builder.WithInput("cordova_command", value)
	return b
}

// WithPlatformName sets platform to build..
func (b *CordovaAndroidBuilder) WithPlatformName(value string) *CordovaAndroidBuilder {
	b.Builder.WithInput("platform_name", value)
	return b
}

// WithBuildOptions sets additional options for `cordova` command.
func (b *CordovaAndroidBuilder) WithBuildOptions(value string) *CordovaAndroidBuilder {
	b.Builder.WithInput("build_options", value)
	return b
}
