// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: remote-script-runner (2.0.1)

package step

// RemoteScriptRunnerBuilder builds a remote-script-runner step with typed input methods.
type RemoteScriptRunnerBuilder struct{ *Builder }

// RemoteScriptRunner creates a remote-script-runner step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.RemoteScriptRunner("2")  // explicit default
//	step.RemoteScriptRunner("1")                  // older major
func RemoteScriptRunner(version ...string) *RemoteScriptRunnerBuilder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &RemoteScriptRunnerBuilder{Builder: From("remote-script-runner", v)}
}

// WithScriptUrl sets script URL.
func (b *RemoteScriptRunnerBuilder) WithScriptUrl(value string) *RemoteScriptRunnerBuilder {
	b.Builder.WithInput("script_url", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *RemoteScriptRunnerBuilder) WithRunIf(expr string) *RemoteScriptRunnerBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *RemoteScriptRunnerBuilder) WithIsAlwaysRun(v bool) *RemoteScriptRunnerBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *RemoteScriptRunnerBuilder) WithIsSkippable(v bool) *RemoteScriptRunnerBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *RemoteScriptRunnerBuilder) WithTitle(title string) *RemoteScriptRunnerBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *RemoteScriptRunnerBuilder) WithTimeout(seconds int) *RemoteScriptRunnerBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *RemoteScriptRunnerBuilder) WithNoOutputTimeout(seconds int) *RemoteScriptRunnerBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *RemoteScriptRunnerBuilder) WithExecutionContainer(containerID string) *RemoteScriptRunnerBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *RemoteScriptRunnerBuilder) WithServiceContainers(containerIDs ...string) *RemoteScriptRunnerBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
