// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: restore-gradle-cache (2.2.4)

package step

// RestoreGradleCacheV2Verbose enumerates the valid values for the verbose input.
type RestoreGradleCacheV2Verbose string

const (
	RestoreGradleCacheV2VerboseTrue  RestoreGradleCacheV2Verbose = "true"
	RestoreGradleCacheV2VerboseFalse RestoreGradleCacheV2Verbose = "false"
)

// RestoreGradleCacheV2Builder builds a restore-gradle-cache step with typed input methods.
type RestoreGradleCacheV2Builder struct{ *Builder }

// RestoreGradleCacheV2 creates a restore-gradle-cache step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.RestoreGradleCacheV2("2")  // explicit default
//	step.RestoreGradleCacheV2("1")                  // older major
func RestoreGradleCacheV2(version ...string) *RestoreGradleCacheV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &RestoreGradleCacheV2Builder{Builder: From("restore-gradle-cache", v)}
}

// WithVerbose sets verbose logging.
func (b *RestoreGradleCacheV2Builder) WithVerbose(value RestoreGradleCacheV2Verbose) *RestoreGradleCacheV2Builder {
	b.Builder.WithInput("verbose", string(value))
	return b
}

// WithRetries sets number of retries.
func (b *RestoreGradleCacheV2Builder) WithRetries(value string) *RestoreGradleCacheV2Builder {
	b.Builder.WithInput("retries", value)
	return b
}

// restoreGradleCacheV2Outputs holds the names of environment variables published
// by the restore-gradle-cache step (v2) at run time.
type restoreGradleCacheV2Outputs struct {
	// BitriseCacheHit is the "Cache hit" output env var.
	BitriseCacheHit string
}

// RestoreGradleCacheV2Outputs provides typed access to the environment variable names
// that restore-gradle-cache (v2) exports after a successful run.
var RestoreGradleCacheV2Outputs = restoreGradleCacheV2Outputs{
	BitriseCacheHit: "BITRISE_CACHE_HIT",
}
