// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: beat-android-code-stats (0.0.2)

package step

import "time"

// BeatAndroidCodeStatsBuilder builds a beat-android-code-stats step with typed input methods.
type BeatAndroidCodeStatsBuilder struct{ *Builder }

// BeatAndroidCodeStats creates a beat-android-code-stats step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.BeatAndroidCodeStats("0")  // explicit default
//	step.BeatAndroidCodeStats("1")                  // older major
func BeatAndroidCodeStats(version ...string) *BeatAndroidCodeStatsBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &BeatAndroidCodeStatsBuilder{Builder: From("beat-android-code-stats", v)}
}

// WithProjectLocation sets project Location.
func (b *BeatAndroidCodeStatsBuilder) WithProjectLocation(value string) *BeatAndroidCodeStatsBuilder {
	b.Builder.WithInput("project_location", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *BeatAndroidCodeStatsBuilder) WithRunIf(expr string) *BeatAndroidCodeStatsBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *BeatAndroidCodeStatsBuilder) WithIsAlwaysRun(v bool) *BeatAndroidCodeStatsBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *BeatAndroidCodeStatsBuilder) WithIsSkippable(v bool) *BeatAndroidCodeStatsBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *BeatAndroidCodeStatsBuilder) WithTitle(title string) *BeatAndroidCodeStatsBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *BeatAndroidCodeStatsBuilder) WithTimeout(seconds int) *BeatAndroidCodeStatsBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *BeatAndroidCodeStatsBuilder) WithNoOutputTimeout(seconds int) *BeatAndroidCodeStatsBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *BeatAndroidCodeStatsBuilder) WithTimeoutDuration(d time.Duration) *BeatAndroidCodeStatsBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *BeatAndroidCodeStatsBuilder) WithNoOutputTimeoutDuration(d time.Duration) *BeatAndroidCodeStatsBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *BeatAndroidCodeStatsBuilder) WithExecutionContainer(containerID string) *BeatAndroidCodeStatsBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *BeatAndroidCodeStatsBuilder) WithServiceContainers(containerIDs ...string) *BeatAndroidCodeStatsBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// beatAndroidCodeStatsOutputs holds the names of environment variables published
// by the beat-android-code-stats step (v0) at run time.
type beatAndroidCodeStatsOutputs struct {
	// KotlinLinesCode is the "Kotlin lines of code" output env var.
	KotlinLinesCode string
	// JavaLinesCode is the "Java lines of code" output env var.
	JavaLinesCode string
	// XmlLinesCode is the "XML lines of code" output env var.
	XmlLinesCode string
	// KotlinPercentageCode is the "Kotlin percentage of code" output env var.
	KotlinPercentageCode string
	// JavaPercentageCode is the "Java percentage of code" output env var.
	JavaPercentageCode string
	// DocumentationFiles is the "Documentation files" output env var.
	DocumentationFiles string
	// UnitTestsCount is the "Unit tests" output env var.
	UnitTestsCount string
	// UiTestsCount is the "UI tests" output env var.
	UiTestsCount string
	// MvpPresentersCount is the "MVP Presenters" output env var.
	MvpPresentersCount string
	// ViewmodelCount is the "ViewModels" output env var.
	ViewmodelCount string
}

// BeatAndroidCodeStatsOutputs provides typed access to the environment variable names
// that beat-android-code-stats (v0) exports after a successful run.
var BeatAndroidCodeStatsOutputs = beatAndroidCodeStatsOutputs{
	KotlinLinesCode:      "KOTLIN_LINES_CODE",
	JavaLinesCode:        "JAVA_LINES_CODE",
	XmlLinesCode:         "XML_LINES_CODE",
	KotlinPercentageCode: "KOTLIN_PERCENTAGE_CODE",
	JavaPercentageCode:   "JAVA_PERCENTAGE_CODE",
	DocumentationFiles:   "DOCUMENTATION_FILES",
	UnitTestsCount:       "UNIT_TESTS_COUNT",
	UiTestsCount:         "UI_TESTS_COUNT",
	MvpPresentersCount:   "MVP_PRESENTERS_COUNT",
	ViewmodelCount:       "VIEWMODEL_COUNT",
}
