// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: cocoapod-key (2.0.0)

package step

// CocoapodKeyBuilder builds a cocoapod-key step with typed input methods.
type CocoapodKeyBuilder struct{ *Builder }

// CocoapodKey creates a cocoapod-key step builder (v2).
func CocoapodKey(version ...string) *CocoapodKeyBuilder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &CocoapodKeyBuilder{Builder: From("cocoapod-key", v)}
}

// WithProjectName sets project name.
func (b *CocoapodKeyBuilder) WithProjectName(value string) *CocoapodKeyBuilder {
	b.Builder.WithInput("project_name", value)
	return b
}

// WithPodfilePath sets podfile path.
func (b *CocoapodKeyBuilder) WithPodfilePath(value string) *CocoapodKeyBuilder {
	b.Builder.WithInput("podfile_path", value)
	return b
}

// WithKeys sets keys (No longer used).
func (b *CocoapodKeyBuilder) WithKeys(value string) *CocoapodKeyBuilder {
	b.Builder.WithInput("keys", value)
	return b
}

// WithValues sets values (No longer used).
func (b *CocoapodKeyBuilder) WithValues(value string) *CocoapodKeyBuilder {
	b.Builder.WithInput("values", value)
	return b
}
