// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: karma-jasmine-runner (0.9.2)

package step

// KarmaJasmineRunnerBuilder builds a karma-jasmine-runner step with typed input methods.
type KarmaJasmineRunnerBuilder struct{ *Builder }

// KarmaJasmineRunner creates a karma-jasmine-runner step builder (v0).
func KarmaJasmineRunner() *KarmaJasmineRunnerBuilder {
	return &KarmaJasmineRunnerBuilder{Builder: From("karma-jasmine-runner", "0")}
}

// WithWorkdir sets working directory.
func (b *KarmaJasmineRunnerBuilder) WithWorkdir(value string) *KarmaJasmineRunnerBuilder {
	b.Builder.WithInput("workdir", value)
	return b
}

// WithBrowsers sets list of browsers to start.
func (b *KarmaJasmineRunnerBuilder) WithBrowsers(value string) *KarmaJasmineRunnerBuilder {
	b.Builder.WithInput("browsers", value)
	return b
}

// WithOptions sets options to append to the karma start command.
func (b *KarmaJasmineRunnerBuilder) WithOptions(value string) *KarmaJasmineRunnerBuilder {
	b.Builder.WithInput("options", value)
	return b
}
