// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: build-router-wait (0.12.4)

package step

// BuildRouterWaitAbortOnFail enumerates the valid values for the abort_on_fail input.
type BuildRouterWaitAbortOnFail string

const (
	BuildRouterWaitAbortOnFailYes BuildRouterWaitAbortOnFail = "yes"
	BuildRouterWaitAbortOnFailNo  BuildRouterWaitAbortOnFail = "no"
)

// BuildRouterWaitVerbose enumerates the valid values for the verbose input.
type BuildRouterWaitVerbose string

const (
	BuildRouterWaitVerboseYes BuildRouterWaitVerbose = "yes"
	BuildRouterWaitVerboseNo  BuildRouterWaitVerbose = "no"
)

// BuildRouterWaitBuilder builds a build-router-wait step with typed input methods.
type BuildRouterWaitBuilder struct{ *Builder }

// BuildRouterWait creates a build-router-wait step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.BuildRouterWait("0")  // explicit default
//	step.BuildRouterWait("1")                  // older major
func BuildRouterWait(version ...string) *BuildRouterWaitBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &BuildRouterWaitBuilder{Builder: From("build-router-wait", v)}
}

// WithAccessToken sets bitrise Access Token.
func (b *BuildRouterWaitBuilder) WithAccessToken(value string) *BuildRouterWaitBuilder {
	b.Builder.WithInput("access_token", value)
	return b
}

// WithBuildslugs sets build slugs.
func (b *BuildRouterWaitBuilder) WithBuildslugs(value string) *BuildRouterWaitBuilder {
	b.Builder.WithInput("buildslugs", value)
	return b
}

// WithBuildArtifactsSavePath sets the path of the build artifacts.
func (b *BuildRouterWaitBuilder) WithBuildArtifactsSavePath(value string) *BuildRouterWaitBuilder {
	b.Builder.WithInput("build_artifacts_save_path", value)
	return b
}

// WithAbortOnFail sets abort all builds if one fails.
func (b *BuildRouterWaitBuilder) WithAbortOnFail(value BuildRouterWaitAbortOnFail) *BuildRouterWaitBuilder {
	b.Builder.WithInput("abort_on_fail", string(value))
	return b
}

// WithVerbose sets enable verbose log?.
func (b *BuildRouterWaitBuilder) WithVerbose(value BuildRouterWaitVerbose) *BuildRouterWaitBuilder {
	b.Builder.WithInput("verbose", string(value))
	return b
}
