// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: file-downloader (1.1.0)

package step

// FileDownloaderV1Builder builds a file-downloader step with typed input methods.
type FileDownloaderV1Builder struct{ *Builder }

// FileDownloaderV1 creates a file-downloader step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.FileDownloaderV1("1")  // explicit default
//	step.FileDownloaderV1("1")                  // older major
func FileDownloaderV1(version ...string) *FileDownloaderV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &FileDownloaderV1Builder{Builder: From("file-downloader", v)}
}

// WithSource sets download source URL.
func (b *FileDownloaderV1Builder) WithSource(value string) *FileDownloaderV1Builder {
	b.Builder.WithInput("source", value)
	return b
}

// WithDestination sets download destination path.
func (b *FileDownloaderV1Builder) WithDestination(value string) *FileDownloaderV1Builder {
	b.Builder.WithInput("destination", value)
	return b
}

// WithFilePermission sets destination file permission.
func (b *FileDownloaderV1Builder) WithFilePermission(value string) *FileDownloaderV1Builder {
	b.Builder.WithInput("file_permission", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *FileDownloaderV1Builder) WithRunIf(expr string) *FileDownloaderV1Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *FileDownloaderV1Builder) WithIsAlwaysRun(v bool) *FileDownloaderV1Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *FileDownloaderV1Builder) WithIsSkippable(v bool) *FileDownloaderV1Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *FileDownloaderV1Builder) WithTitle(title string) *FileDownloaderV1Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *FileDownloaderV1Builder) WithTimeout(seconds int) *FileDownloaderV1Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *FileDownloaderV1Builder) WithNoOutputTimeout(seconds int) *FileDownloaderV1Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *FileDownloaderV1Builder) WithExecutionContainer(containerID string) *FileDownloaderV1Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *FileDownloaderV1Builder) WithServiceContainers(containerIDs ...string) *FileDownloaderV1Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
