// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: carthage (2.4.0)

package step

// CarthageV2CarthageCommand enumerates the valid values for the carthage_command input.
type CarthageV2CarthageCommand string

const (
	CarthageV2CarthageCommandBootstrap CarthageV2CarthageCommand = "bootstrap"
	CarthageV2CarthageCommandUpdate    CarthageV2CarthageCommand = "update"
	CarthageV2CarthageCommandBuild     CarthageV2CarthageCommand = "build"
	CarthageV2CarthageCommandCheckout  CarthageV2CarthageCommand = "checkout"
)

// CarthageV2NoUseBinaries enumerates the valid values for the no_use_binaries input.
type CarthageV2NoUseBinaries string

const (
	CarthageV2NoUseBinariesTrue  CarthageV2NoUseBinaries = "true"
	CarthageV2NoUseBinariesFalse CarthageV2NoUseBinaries = "false"
)

// CarthageV2VerboseOutput enumerates the valid values for the verbose_output input.
type CarthageV2VerboseOutput string

const (
	CarthageV2VerboseOutputTrue  CarthageV2VerboseOutput = "true"
	CarthageV2VerboseOutputFalse CarthageV2VerboseOutput = "false"
)

// CarthageV2SshOutput enumerates the valid values for the ssh_output input.
type CarthageV2SshOutput string

const (
	CarthageV2SshOutputTrue  CarthageV2SshOutput = "true"
	CarthageV2SshOutputFalse CarthageV2SshOutput = "false"
)

// CarthageV2Platform enumerates the valid values for the platform input.
type CarthageV2Platform string

const (
	CarthageV2PlatformIOS    CarthageV2Platform = "iOS"
	CarthageV2PlatformMac    CarthageV2Platform = "Mac"
	CarthageV2PlatformIOSMac CarthageV2Platform = "iOS,Mac"
	CarthageV2PlatformTvOS   CarthageV2Platform = "tvOS"
	CarthageV2PlatformAll    CarthageV2Platform = "all"
)

// CarthageV2Builder builds a carthage step with typed input methods.
type CarthageV2Builder struct{ *Builder }

// CarthageV2 creates a carthage step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.CarthageV2("2")  // explicit default
//	step.CarthageV2("1")                  // older major
func CarthageV2(version ...string) *CarthageV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &CarthageV2Builder{Builder: From("carthage", v)}
}

// WithGithubAccessToken sets github Personal Access Token.
func (b *CarthageV2Builder) WithGithubAccessToken(value string) *CarthageV2Builder {
	b.Builder.WithInput("github_access_token", value)
	return b
}

// WithCarthageCommand sets carthage command to run.
func (b *CarthageV2Builder) WithCarthageCommand(value CarthageV2CarthageCommand) *CarthageV2Builder {
	b.Builder.WithInput("carthage_command", string(value))
	return b
}

// WithNoUseBinaries sets set no use binaries flag.
func (b *CarthageV2Builder) WithNoUseBinaries(value CarthageV2NoUseBinaries) *CarthageV2Builder {
	b.Builder.WithInput("no_use_binaries", string(value))
	return b
}

// WithVerboseOutput sets set verbose output flag.
func (b *CarthageV2Builder) WithVerboseOutput(value CarthageV2VerboseOutput) *CarthageV2Builder {
	b.Builder.WithInput("verbose_output", string(value))
	return b
}

// WithSshOutput sets set ssh flag.
func (b *CarthageV2Builder) WithSshOutput(value CarthageV2SshOutput) *CarthageV2Builder {
	b.Builder.WithInput("ssh_output", string(value))
	return b
}

// WithWorkingDir sets working directory.
func (b *CarthageV2Builder) WithWorkingDir(value string) *CarthageV2Builder {
	b.Builder.WithInput("working_dir", value)
	return b
}

// WithPlatform sets platform.
func (b *CarthageV2Builder) WithPlatform(value CarthageV2Platform) *CarthageV2Builder {
	b.Builder.WithInput("platform", string(value))
	return b
}

// WithCarthageOptions sets additional options for `carthage` command.
func (b *CarthageV2Builder) WithCarthageOptions(value string) *CarthageV2Builder {
	b.Builder.WithInput("carthage_options", value)
	return b
}
