// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xcode-test (4.7.5)

package step

// XcodeTestV4Builder builds a xcode-test step with typed input methods.
type XcodeTestV4Builder struct{ *Builder }

// XcodeTestV4 creates a xcode-test step builder (v4 by default).
// Pass an explicit major version to override the default:
//
//	step.XcodeTestV4("4")  // explicit default
//	step.XcodeTestV4("1")                  // older major
func XcodeTestV4(version ...string) *XcodeTestV4Builder {
	v := "4"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &XcodeTestV4Builder{Builder: From("xcode-test", v)}
}

// WithProjectPath sets project path.
func (b *XcodeTestV4Builder) WithProjectPath(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("project_path", value)
	return b
}

// WithScheme sets scheme.
func (b *XcodeTestV4Builder) WithScheme(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("scheme", value)
	return b
}

// WithDestination sets device destination specifier.
func (b *XcodeTestV4Builder) WithDestination(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("destination", value)
	return b
}

// WithTestPlan sets test Plan.
func (b *XcodeTestV4Builder) WithTestPlan(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("test_plan", value)
	return b
}

// WithTestRepetitionMode sets test Repetition Mode (Available in Xcode 13+).
func (b *XcodeTestV4Builder) WithTestRepetitionMode(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("test_repetition_mode", value)
	return b
}

// WithMaximumTestRepetitions sets maximum Test Repetitions (Available in Xcode 13+).
func (b *XcodeTestV4Builder) WithMaximumTestRepetitions(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("maximum_test_repetitions", value)
	return b
}

// WithRelaunchTestsForEachRepetition sets relaunch Tests for Each Repetition (Available in Xcode 13+).
func (b *XcodeTestV4Builder) WithRelaunchTestsForEachRepetition(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("relaunch_tests_for_each_repetition", value)
	return b
}

// WithShouldRetryTestOnFail sets should retry tests on failure? (Not available in Xcode 13+).
func (b *XcodeTestV4Builder) WithShouldRetryTestOnFail(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("should_retry_test_on_fail", value)
	return b
}

// WithXcconfigContent sets build settings (xcconfig).
func (b *XcodeTestV4Builder) WithXcconfigContent(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("xcconfig_content", value)
	return b
}

// WithPerformCleanAction sets perform clean action.
func (b *XcodeTestV4Builder) WithPerformCleanAction(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("perform_clean_action", value)
	return b
}

// WithXcodebuildOptions sets additional options for the xcodebuild command.
func (b *XcodeTestV4Builder) WithXcodebuildOptions(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("xcodebuild_options", value)
	return b
}

// WithLogFormatter sets log formatter.
func (b *XcodeTestV4Builder) WithLogFormatter(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("log_formatter", value)
	return b
}

// WithXcbeautifyOptions sets additional options for the xcbeautify command.
func (b *XcodeTestV4Builder) WithXcbeautifyOptions(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("xcbeautify_options", value)
	return b
}

// WithXcprettyOptions sets additional options for the xcpretty command.
func (b *XcodeTestV4Builder) WithXcprettyOptions(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("xcpretty_options", value)
	return b
}

// WithCacheLevel sets enable collecting cache content.
func (b *XcodeTestV4Builder) WithCacheLevel(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("cache_level", value)
	return b
}

// WithVerboseLog sets enable verbose logging.
func (b *XcodeTestV4Builder) WithVerboseLog(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("verbose_log", value)
	return b
}

// WithCollectSimulatorDiagnostics sets collect Simulator diagnostics.
func (b *XcodeTestV4Builder) WithCollectSimulatorDiagnostics(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("collect_simulator_diagnostics", value)
	return b
}

// WithHeadlessMode sets run the simulator in headless mode.
func (b *XcodeTestV4Builder) WithHeadlessMode(value string) *XcodeTestV4Builder {
	b.Builder.WithInput("headless_mode", value)
	return b
}
