// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: connect-to-fortigate-sslvpn (1.0.0)

package step

// ConnectToFortigateSslvpnBuilder builds a connect-to-fortigate-sslvpn step with typed input methods.
type ConnectToFortigateSslvpnBuilder struct{ *Builder }

// ConnectToFortigateSslvpn creates a connect-to-fortigate-sslvpn step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.ConnectToFortigateSslvpn("1")  // explicit default
//	step.ConnectToFortigateSslvpn("1")                  // older major
func ConnectToFortigateSslvpn(version ...string) *ConnectToFortigateSslvpnBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ConnectToFortigateSslvpnBuilder{Builder: From("connect-to-fortigate-sslvpn", v)}
}

// WithFtgHost sets remote Gateway.
func (b *ConnectToFortigateSslvpnBuilder) WithFtgHost(value string) *ConnectToFortigateSslvpnBuilder {
	b.Builder.WithInput("ftg_host", value)
	return b
}

// WithFtgPort sets remote Gateway Port.
func (b *ConnectToFortigateSslvpnBuilder) WithFtgPort(value string) *ConnectToFortigateSslvpnBuilder {
	b.Builder.WithInput("ftg_port", value)
	return b
}

// WithFtgUsername sets username.
func (b *ConnectToFortigateSslvpnBuilder) WithFtgUsername(value string) *ConnectToFortigateSslvpnBuilder {
	b.Builder.WithInput("ftg_username", value)
	return b
}

// WithFtgPassword sets password.
func (b *ConnectToFortigateSslvpnBuilder) WithFtgPassword(value string) *ConnectToFortigateSslvpnBuilder {
	b.Builder.WithInput("ftg_password", value)
	return b
}

// WithFtgTrustedCerts sets trusted certs.
func (b *ConnectToFortigateSslvpnBuilder) WithFtgTrustedCerts(value string) *ConnectToFortigateSslvpnBuilder {
	b.Builder.WithInput("ftg_trusted_certs", value)
	return b
}

// WithFtgLogfile sets log file path.
func (b *ConnectToFortigateSslvpnBuilder) WithFtgLogfile(value string) *ConnectToFortigateSslvpnBuilder {
	b.Builder.WithInput("ftg_logfile", value)
	return b
}

// WithIpHosts sets /etc/hosts.
func (b *ConnectToFortigateSslvpnBuilder) WithIpHosts(value string) *ConnectToFortigateSslvpnBuilder {
	b.Builder.WithInput("ip_hosts", value)
	return b
}

// WithIpRoutes sets iP Addresses to route.
func (b *ConnectToFortigateSslvpnBuilder) WithIpRoutes(value string) *ConnectToFortigateSslvpnBuilder {
	b.Builder.WithInput("ip_routes", value)
	return b
}
