// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xcode-archive (2.8.7)

package step

// XcodeArchiveV2Builder builds a xcode-archive step with typed input methods.
type XcodeArchiveV2Builder struct{ *Builder }

// XcodeArchiveV2 creates a xcode-archive step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.XcodeArchiveV2("2")  // explicit default
//	step.XcodeArchiveV2("1")                  // older major
func XcodeArchiveV2(version ...string) *XcodeArchiveV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &XcodeArchiveV2Builder{Builder: From("xcode-archive", v)}
}

// WithProjectPath sets project (or Workspace) path.
func (b *XcodeArchiveV2Builder) WithProjectPath(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("project_path", value)
	return b
}

// WithScheme sets scheme name.
func (b *XcodeArchiveV2Builder) WithScheme(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("scheme", value)
	return b
}

// WithConfiguration sets configuration name.
func (b *XcodeArchiveV2Builder) WithConfiguration(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("configuration", value)
	return b
}

// WithExportMethod sets select method for export.
func (b *XcodeArchiveV2Builder) WithExportMethod(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("export_method", value)
	return b
}

// WithTeamId sets the Developer Portal team to use for this export.
func (b *XcodeArchiveV2Builder) WithTeamId(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("team_id", value)
	return b
}

// WithCompileBitcode sets rebuild from bitcode.
func (b *XcodeArchiveV2Builder) WithCompileBitcode(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("compile_bitcode", value)
	return b
}

// WithUploadBitcode sets include bitcode.
func (b *XcodeArchiveV2Builder) WithUploadBitcode(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("upload_bitcode", value)
	return b
}

// WithIcloudContainerEnvironment sets iCloud container environment.
func (b *XcodeArchiveV2Builder) WithIcloudContainerEnvironment(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("icloud_container_environment", value)
	return b
}

// WithDisableIndexWhileBuilding sets disable indexing during the build.
func (b *XcodeArchiveV2Builder) WithDisableIndexWhileBuilding(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("disable_index_while_building", value)
	return b
}

// WithCacheLevel sets enable caching of Swift Package Manager packages.
func (b *XcodeArchiveV2Builder) WithCacheLevel(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("cache_level", value)
	return b
}

// WithForceTeamId sets force code signing with Development Team.
func (b *XcodeArchiveV2Builder) WithForceTeamId(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("force_team_id", value)
	return b
}

// WithForceCodeSignIdentity sets force code signing with Code Signing Identity.
func (b *XcodeArchiveV2Builder) WithForceCodeSignIdentity(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("force_code_sign_identity", value)
	return b
}

// WithForceProvisioningProfileSpecifier sets force code signing with Provisioning Profile Specifier.
func (b *XcodeArchiveV2Builder) WithForceProvisioningProfileSpecifier(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("force_provisioning_profile_specifier", value)
	return b
}

// WithForceProvisioningProfile sets force code signing with Provisioning Profile.
func (b *XcodeArchiveV2Builder) WithForceProvisioningProfile(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("force_provisioning_profile", value)
	return b
}

// WithCustomExportOptionsPlistContent sets custom export options plist content.
func (b *XcodeArchiveV2Builder) WithCustomExportOptionsPlistContent(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("custom_export_options_plist_content", value)
	return b
}

// WithArtifactName sets generated Artifact Name.
func (b *XcodeArchiveV2Builder) WithArtifactName(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("artifact_name", value)
	return b
}

// WithXcodebuildOptions sets additional options for xcodebuild call.
func (b *XcodeArchiveV2Builder) WithXcodebuildOptions(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("xcodebuild_options", value)
	return b
}

// WithWorkdir sets working directory.
func (b *XcodeArchiveV2Builder) WithWorkdir(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("workdir", value)
	return b
}

// WithOutputDir sets output directory path.
func (b *XcodeArchiveV2Builder) WithOutputDir(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("output_dir", value)
	return b
}

// WithIsCleanBuild sets do a clean Xcode build before the archive?.
func (b *XcodeArchiveV2Builder) WithIsCleanBuild(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("is_clean_build", value)
	return b
}

// WithOutputTool sets output tool.
func (b *XcodeArchiveV2Builder) WithOutputTool(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("output_tool", value)
	return b
}

// WithExportAllDsyms sets export all dsyms.
func (b *XcodeArchiveV2Builder) WithExportAllDsyms(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("export_all_dsyms", value)
	return b
}

// WithVerboseLog sets enable verbose logging?.
func (b *XcodeArchiveV2Builder) WithVerboseLog(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("verbose_log", value)
	return b
}

// WithUseDeprecatedExport sets use deprecated ipa export method?.
func (b *XcodeArchiveV2Builder) WithUseDeprecatedExport(value string) *XcodeArchiveV2Builder {
	b.Builder.WithInput("use_deprecated_export", value)
	return b
}

// xcodeArchiveV2Outputs holds the names of environment variables published
// by the xcode-archive step (v2) at run time.
type xcodeArchiveV2Outputs struct {
	// BitriseIpaPath is the "The created .ipa file's path" output env var.
	BitriseIpaPath string
	// BitriseAppDirPath is the "The generated .app directory" output env var.
	BitriseAppDirPath string
	// BitriseDsymDirPath is the "The created .dSYM dir's path" output env var.
	BitriseDsymDirPath string
	// BitriseDsymPath is the "The created .dSYM.zip file's path" output env var.
	BitriseDsymPath string
	// BitriseXcarchivePath is the "The created .xcarchive file's path" output env var.
	BitriseXcarchivePath string
	// BitriseXcarchiveZipPath is the "The created .xcarchive.zip file's path" output env var.
	BitriseXcarchiveZipPath string
	// BitriseXcodeArchiveRawResultTextPath is the "The full, raw archive output file path" output env var.
	BitriseXcodeArchiveRawResultTextPath string
	// BitriseIdedistributionLogsPath is the "Path to the xcdistributionlogs" output env var.
	BitriseIdedistributionLogsPath string
}

// XcodeArchiveV2Outputs provides typed access to the environment variable names
// that xcode-archive (v2) exports after a successful run.
var XcodeArchiveV2Outputs = xcodeArchiveV2Outputs{
	BitriseIpaPath:                       "BITRISE_IPA_PATH",
	BitriseAppDirPath:                    "BITRISE_APP_DIR_PATH",
	BitriseDsymDirPath:                   "BITRISE_DSYM_DIR_PATH",
	BitriseDsymPath:                      "BITRISE_DSYM_PATH",
	BitriseXcarchivePath:                 "BITRISE_XCARCHIVE_PATH",
	BitriseXcarchiveZipPath:              "BITRISE_XCARCHIVE_ZIP_PATH",
	BitriseXcodeArchiveRawResultTextPath: "BITRISE_XCODE_ARCHIVE_RAW_RESULT_TEXT_PATH",
	BitriseIdedistributionLogsPath:       "BITRISE_IDEDISTRIBUTION_LOGS_PATH",
}
