// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xcode-test-without-building (0.5.1)

package step

// XcodeTestWithoutBuildingTestRepetitionMode enumerates the valid values for the test_repetition_mode input.
type XcodeTestWithoutBuildingTestRepetitionMode string

const (
	XcodeTestWithoutBuildingTestRepetitionModeNone                      XcodeTestWithoutBuildingTestRepetitionMode = "none"
	XcodeTestWithoutBuildingTestRepetitionModeUntilFailure              XcodeTestWithoutBuildingTestRepetitionMode = "until_failure"
	XcodeTestWithoutBuildingTestRepetitionModeRetryOnFailure            XcodeTestWithoutBuildingTestRepetitionMode = "retry_on_failure"
	XcodeTestWithoutBuildingTestRepetitionModeUpUntilMaximumRepetitions XcodeTestWithoutBuildingTestRepetitionMode = "up_until_maximum_repetitions"
)

// XcodeTestWithoutBuildingRelaunchTestsForEachRepetition enumerates the valid values for the relaunch_tests_for_each_repetition input.
type XcodeTestWithoutBuildingRelaunchTestsForEachRepetition string

const (
	XcodeTestWithoutBuildingRelaunchTestsForEachRepetitionYes XcodeTestWithoutBuildingRelaunchTestsForEachRepetition = "yes"
	XcodeTestWithoutBuildingRelaunchTestsForEachRepetitionNo  XcodeTestWithoutBuildingRelaunchTestsForEachRepetition = "no"
)

// XcodeTestWithoutBuildingBuilder builds a xcode-test-without-building step with typed input methods.
type XcodeTestWithoutBuildingBuilder struct{ *Builder }

// XcodeTestWithoutBuilding creates a xcode-test-without-building step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.XcodeTestWithoutBuilding("0")  // explicit default
//	step.XcodeTestWithoutBuilding("1")                  // older major
func XcodeTestWithoutBuilding(version ...string) *XcodeTestWithoutBuildingBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &XcodeTestWithoutBuildingBuilder{Builder: From("xcode-test-without-building", v)}
}

// WithXctestrun sets xctestrun file path.
func (b *XcodeTestWithoutBuildingBuilder) WithXctestrun(value string) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithInput("xctestrun", value)
	return b
}

// WithDestination sets device destination specifier.
func (b *XcodeTestWithoutBuildingBuilder) WithDestination(value string) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithInput("destination", value)
	return b
}

// WithOnlyTesting sets test identifier list to execute.
func (b *XcodeTestWithoutBuildingBuilder) WithOnlyTesting(value string) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithInput("only_testing", value)
	return b
}

// WithSkipTesting sets test identifier list to skip.
func (b *XcodeTestWithoutBuildingBuilder) WithSkipTesting(value string) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithInput("skip_testing", value)
	return b
}

// WithTestRepetitionMode sets test Repetition Mode (Available in Xcode 13+).
func (b *XcodeTestWithoutBuildingBuilder) WithTestRepetitionMode(value XcodeTestWithoutBuildingTestRepetitionMode) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithInput("test_repetition_mode", string(value))
	return b
}

// WithMaximumTestRepetitions sets maximum Test Repetitions (Available in Xcode 13+).
func (b *XcodeTestWithoutBuildingBuilder) WithMaximumTestRepetitions(value string) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithInput("maximum_test_repetitions", value)
	return b
}

// WithRelaunchTestsForEachRepetition sets relaunch Tests for Each Repetition (Available in Xcode 13+).
func (b *XcodeTestWithoutBuildingBuilder) WithRelaunchTestsForEachRepetition(value XcodeTestWithoutBuildingRelaunchTestsForEachRepetition) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithInput("relaunch_tests_for_each_repetition", string(value))
	return b
}

// WithXcodebuildOptions sets additional options for the xcodebuild command.
func (b *XcodeTestWithoutBuildingBuilder) WithXcodebuildOptions(value string) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithInput("xcodebuild_options", value)
	return b
}

// WithQuarantinedTests sets quarantined tests.
func (b *XcodeTestWithoutBuildingBuilder) WithQuarantinedTests(value string) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithInput("quarantined_tests", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *XcodeTestWithoutBuildingBuilder) WithRunIf(expr string) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *XcodeTestWithoutBuildingBuilder) WithIsAlwaysRun(v bool) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *XcodeTestWithoutBuildingBuilder) WithIsSkippable(v bool) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *XcodeTestWithoutBuildingBuilder) WithTitle(title string) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *XcodeTestWithoutBuildingBuilder) WithTimeout(seconds int) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *XcodeTestWithoutBuildingBuilder) WithNoOutputTimeout(seconds int) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *XcodeTestWithoutBuildingBuilder) WithExecutionContainer(containerID string) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *XcodeTestWithoutBuildingBuilder) WithServiceContainers(containerIDs ...string) *XcodeTestWithoutBuildingBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// xcodeTestWithoutBuildingOutputs holds the names of environment variables published
// by the xcode-test-without-building step (v0) at run time.
type xcodeTestWithoutBuildingOutputs struct {
	// BitriseXcresultPath is the "Test result bundle path" output env var.
	BitriseXcresultPath string
	// BitriseXcresultZipPath is the "Zipped test result bundle path" output env var.
	BitriseXcresultZipPath string
}

// XcodeTestWithoutBuildingOutputs provides typed access to the environment variable names
// that xcode-test-without-building (v0) exports after a successful run.
var XcodeTestWithoutBuildingOutputs = xcodeTestWithoutBuildingOutputs{
	BitriseXcresultPath:    "BITRISE_XCRESULT_PATH",
	BitriseXcresultZipPath: "BITRISE_XCRESULT_ZIP_PATH",
}
