// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: change-android-applicationid (1.0.0)

package step

// ChangeAndroidApplicationidBuilder builds a change-android-applicationid step with typed input methods.
type ChangeAndroidApplicationidBuilder struct{ *Builder }

// ChangeAndroidApplicationid creates a change-android-applicationid step builder (v1).
func ChangeAndroidApplicationid() *ChangeAndroidApplicationidBuilder {
	return &ChangeAndroidApplicationidBuilder{Builder: From("change-android-applicationid", "1")}
}

// WithBuildGradlePath sets path to the build.gradle file.
func (b *ChangeAndroidApplicationidBuilder) WithBuildGradlePath(value string) *ChangeAndroidApplicationidBuilder {
	b.Builder.WithInput("build_gradle_path", value)
	return b
}

// WithNewApplicationId sets new applicationId.
func (b *ChangeAndroidApplicationidBuilder) WithNewApplicationId(value string) *ChangeAndroidApplicationidBuilder {
	b.Builder.WithInput("new_application_id", value)
	return b
}
