// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: fastlane (3.5.2)

package step

// FastlaneV3Connection enumerates the valid values for the connection input.
type FastlaneV3Connection string

const (
	FastlaneV3ConnectionAutomatic FastlaneV3Connection = "automatic"
	FastlaneV3ConnectionApiKey    FastlaneV3Connection = "api_key"
	FastlaneV3ConnectionAppleId   FastlaneV3Connection = "apple_id"
	FastlaneV3ConnectionOff       FastlaneV3Connection = "off"
)

// FastlaneV3UpdateFastlane enumerates the valid values for the update_fastlane input.
type FastlaneV3UpdateFastlane string

const (
	FastlaneV3UpdateFastlaneTrue  FastlaneV3UpdateFastlane = "true"
	FastlaneV3UpdateFastlaneFalse FastlaneV3UpdateFastlane = "false"
)

// FastlaneV3VerboseLog enumerates the valid values for the verbose_log input.
type FastlaneV3VerboseLog string

const (
	FastlaneV3VerboseLogYes FastlaneV3VerboseLog = "yes"
	FastlaneV3VerboseLogNo  FastlaneV3VerboseLog = "no"
)

// FastlaneV3EnableCache enumerates the valid values for the enable_cache input.
type FastlaneV3EnableCache string

const (
	FastlaneV3EnableCacheYes FastlaneV3EnableCache = "yes"
	FastlaneV3EnableCacheNo  FastlaneV3EnableCache = "no"
)

// FastlaneV3Builder builds a fastlane step with typed input methods.
type FastlaneV3Builder struct{ *Builder }

// FastlaneV3 creates a fastlane step builder (v3 by default).
// Pass an explicit major version to override the default:
//
//	step.FastlaneV3("3")  // explicit default
//	step.FastlaneV3("1")                  // older major
func FastlaneV3(version ...string) *FastlaneV3Builder {
	v := "3"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &FastlaneV3Builder{Builder: From("fastlane", v)}
}

// WithLane sets fastlane lane.
func (b *FastlaneV3Builder) WithLane(value string) *FastlaneV3Builder {
	b.Builder.WithInput("lane", value)
	return b
}

// WithWorkDir sets working directory.
func (b *FastlaneV3Builder) WithWorkDir(value string) *FastlaneV3Builder {
	b.Builder.WithInput("work_dir", value)
	return b
}

// WithConnection sets bitrise Apple Developer Connection.
func (b *FastlaneV3Builder) WithConnection(value FastlaneV3Connection) *FastlaneV3Builder {
	b.Builder.WithInput("connection", string(value))
	return b
}

// WithApiKeyPath sets aPI Key: URL.
func (b *FastlaneV3Builder) WithApiKeyPath(value string) *FastlaneV3Builder {
	b.Builder.WithInput("api_key_path", value)
	return b
}

// WithApiIssuer sets aPI Key: Issuer ID.
func (b *FastlaneV3Builder) WithApiIssuer(value string) *FastlaneV3Builder {
	b.Builder.WithInput("api_issuer", value)
	return b
}

// WithAppleId sets apple ID: Email.
func (b *FastlaneV3Builder) WithAppleId(value string) *FastlaneV3Builder {
	b.Builder.WithInput("apple_id", value)
	return b
}

// WithPassword sets apple ID: Password.
func (b *FastlaneV3Builder) WithPassword(value string) *FastlaneV3Builder {
	b.Builder.WithInput("password", value)
	return b
}

// WithAppPassword sets apple ID: Application-specific password.
func (b *FastlaneV3Builder) WithAppPassword(value string) *FastlaneV3Builder {
	b.Builder.WithInput("app_password", value)
	return b
}

// WithUpdateFastlane sets should update fastlane gem before run?.
func (b *FastlaneV3Builder) WithUpdateFastlane(value FastlaneV3UpdateFastlane) *FastlaneV3Builder {
	b.Builder.WithInput("update_fastlane", string(value))
	return b
}

// WithVerboseLog sets enable verbose logging?.
func (b *FastlaneV3Builder) WithVerboseLog(value FastlaneV3VerboseLog) *FastlaneV3Builder {
	b.Builder.WithInput("verbose_log", string(value))
	return b
}

// WithEnableCache sets enable collecting files to be included in the build cache.
func (b *FastlaneV3Builder) WithEnableCache(value FastlaneV3EnableCache) *FastlaneV3Builder {
	b.Builder.WithInput("enable_cache", string(value))
	return b
}
