// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: activate-ssh-key (4.1.1)

package step

// ActivateSshKeyV4Builder builds a activate-ssh-key step with typed input methods.
type ActivateSshKeyV4Builder struct{ *Builder }

// ActivateSshKeyV4 creates a activate-ssh-key step builder (v4 by default).
// Pass an explicit major version to override the default:
//
//	step.ActivateSshKeyV4("4")  // explicit default
//	step.ActivateSshKeyV4("1")                  // older major
func ActivateSshKeyV4(version ...string) *ActivateSshKeyV4Builder {
	v := "4"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ActivateSshKeyV4Builder{Builder: From("activate-ssh-key", v)}
}

// WithSshRsaPrivateKey sets sSH private key content.
func (b *ActivateSshKeyV4Builder) WithSshRsaPrivateKey(value string) *ActivateSshKeyV4Builder {
	b.Builder.WithInput("ssh_rsa_private_key", value)
	return b
}

// WithSshKeySavePath sets sSH key save path.
func (b *ActivateSshKeyV4Builder) WithSshKeySavePath(value string) *ActivateSshKeyV4Builder {
	b.Builder.WithInput("ssh_key_save_path", value)
	return b
}

// WithIsRemoveOtherIdentities sets remove other identities from SSH agent.
func (b *ActivateSshKeyV4Builder) WithIsRemoveOtherIdentities(value string) *ActivateSshKeyV4Builder {
	b.Builder.WithInput("is_remove_other_identities", value)
	return b
}

// WithVerbose sets enable verbose logging.
func (b *ActivateSshKeyV4Builder) WithVerbose(value string) *ActivateSshKeyV4Builder {
	b.Builder.WithInput("verbose", value)
	return b
}
