// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xcode-project-info (2.1.0)

package step

// XcodeProjectInfoV2Builder builds a xcode-project-info step with typed input methods.
type XcodeProjectInfoV2Builder struct{ *Builder }

// XcodeProjectInfoV2 creates a xcode-project-info step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.XcodeProjectInfoV2("2")  // explicit default
//	step.XcodeProjectInfoV2("1")                  // older major
func XcodeProjectInfoV2(version ...string) *XcodeProjectInfoV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &XcodeProjectInfoV2Builder{Builder: From("xcode-project-info", v)}
}

// WithInfoPlistPath sets relative path from Source directory to Info.plist file.
func (b *XcodeProjectInfoV2Builder) WithInfoPlistPath(value string) *XcodeProjectInfoV2Builder {
	b.Builder.WithInput("info_plist_path", value)
	return b
}

// WithXcodeprojPath sets relative path from Source directory to Xcode project file.
func (b *XcodeProjectInfoV2Builder) WithXcodeprojPath(value string) *XcodeProjectInfoV2Builder {
	b.Builder.WithInput("xcodeproj_path", value)
	return b
}

// WithTarget sets for Xcode 11+ projects, get the version & build for this target.
func (b *XcodeProjectInfoV2Builder) WithTarget(value string) *XcodeProjectInfoV2Builder {
	b.Builder.WithInput("target", value)
	return b
}
