// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: create-github-app-token (1.0.0)

package step

// CreateGithubAppTokenBuilder builds a create-github-app-token step with typed input methods.
type CreateGithubAppTokenBuilder struct{ *Builder }

// CreateGithubAppToken creates a create-github-app-token step builder (v1).
func CreateGithubAppToken() *CreateGithubAppTokenBuilder {
	return &CreateGithubAppTokenBuilder{Builder: From("create-github-app-token", "1")}
}

// WithGithubRepository sets gitHub repository name.
func (b *CreateGithubAppTokenBuilder) WithGithubRepository(value string) *CreateGithubAppTokenBuilder {
	b.Builder.WithInput("github_repository", value)
	return b
}

// WithClientId sets client ID.
func (b *CreateGithubAppTokenBuilder) WithClientId(value string) *CreateGithubAppTokenBuilder {
	b.Builder.WithInput("client_id", value)
	return b
}

// WithPrivateKeyPath sets private key path.
func (b *CreateGithubAppTokenBuilder) WithPrivateKeyPath(value string) *CreateGithubAppTokenBuilder {
	b.Builder.WithInput("private_key_path", value)
	return b
}
