// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: save-s3-cache (0.9.1)

package step

// SaveS3CacheBuilder builds a save-s3-cache step with typed input methods.
type SaveS3CacheBuilder struct{ *Builder }

// SaveS3Cache creates a save-s3-cache step builder (v0).
func SaveS3Cache(version ...string) *SaveS3CacheBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &SaveS3CacheBuilder{Builder: From("save-s3-cache", v)}
}

// WithKey sets cache key.
func (b *SaveS3CacheBuilder) WithKey(value string) *SaveS3CacheBuilder {
	b.Builder.WithInput("key", value)
	return b
}

// WithPaths sets paths to cache.
func (b *SaveS3CacheBuilder) WithPaths(value string) *SaveS3CacheBuilder {
	b.Builder.WithInput("paths", value)
	return b
}

// WithVerbose sets verbose logging.
func (b *SaveS3CacheBuilder) WithVerbose(value string) *SaveS3CacheBuilder {
	b.Builder.WithInput("verbose", value)
	return b
}

// WithAwsBucket sets aWS Bucket name.
func (b *SaveS3CacheBuilder) WithAwsBucket(value string) *SaveS3CacheBuilder {
	b.Builder.WithInput("aws_bucket", value)
	return b
}

// WithAwsRegion sets aWS Region.
func (b *SaveS3CacheBuilder) WithAwsRegion(value string) *SaveS3CacheBuilder {
	b.Builder.WithInput("aws_region", value)
	return b
}

// WithAwsAccessKeyId sets aWS_ACCESS_KEY_ID.
func (b *SaveS3CacheBuilder) WithAwsAccessKeyId(value string) *SaveS3CacheBuilder {
	b.Builder.WithInput("aws_access_key_id", value)
	return b
}

// WithAwsSecretAccessKey sets aWS_SECRET_ACCESS_KEY.
func (b *SaveS3CacheBuilder) WithAwsSecretAccessKey(value string) *SaveS3CacheBuilder {
	b.Builder.WithInput("aws_secret_access_key", value)
	return b
}
