// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: bitbucket-snippet-runner (1.2.0)

package step

// BitbucketSnippetRunnerV1IsDebug enumerates the valid values for the is_debug input.
type BitbucketSnippetRunnerV1IsDebug string

const (
	BitbucketSnippetRunnerV1IsDebugNo  BitbucketSnippetRunnerV1IsDebug = "no"
	BitbucketSnippetRunnerV1IsDebugYes BitbucketSnippetRunnerV1IsDebug = "yes"
)

// BitbucketSnippetRunnerV1Builder builds a bitbucket-snippet-runner step with typed input methods.
type BitbucketSnippetRunnerV1Builder struct{ *Builder }

// BitbucketSnippetRunnerV1 creates a bitbucket-snippet-runner step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.BitbucketSnippetRunnerV1("1")  // explicit default
//	step.BitbucketSnippetRunnerV1("1")                  // older major
func BitbucketSnippetRunnerV1(version ...string) *BitbucketSnippetRunnerV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &BitbucketSnippetRunnerV1Builder{Builder: From("bitbucket-snippet-runner", v)}
}

// WithScriptUrl sets snippet URL.
func (b *BitbucketSnippetRunnerV1Builder) WithScriptUrl(value string) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithInput("script_url", value)
	return b
}

// WithUsername sets username.
func (b *BitbucketSnippetRunnerV1Builder) WithUsername(value string) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithInput("username", value)
	return b
}

// WithPassword sets password.
func (b *BitbucketSnippetRunnerV1Builder) WithPassword(value string) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithInput("password", value)
	return b
}

// WithWorkingDir sets working directory.
func (b *BitbucketSnippetRunnerV1Builder) WithWorkingDir(value string) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithInput("working_dir", value)
	return b
}

// WithScriptArgs sets script Arguments.
func (b *BitbucketSnippetRunnerV1Builder) WithScriptArgs(value string) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithInput("script_args", value)
	return b
}

// WithIsDebug sets debug print?.
func (b *BitbucketSnippetRunnerV1Builder) WithIsDebug(value BitbucketSnippetRunnerV1IsDebug) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithInput("is_debug", string(value))
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *BitbucketSnippetRunnerV1Builder) WithRunIf(expr string) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *BitbucketSnippetRunnerV1Builder) WithIsAlwaysRun(v bool) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *BitbucketSnippetRunnerV1Builder) WithIsSkippable(v bool) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *BitbucketSnippetRunnerV1Builder) WithTitle(title string) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *BitbucketSnippetRunnerV1Builder) WithTimeout(seconds int) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *BitbucketSnippetRunnerV1Builder) WithNoOutputTimeout(seconds int) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *BitbucketSnippetRunnerV1Builder) WithExecutionContainer(containerID string) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *BitbucketSnippetRunnerV1Builder) WithServiceContainers(containerIDs ...string) *BitbucketSnippetRunnerV1Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
