// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: deploy-to-updraft (0.0.2)

package step

// DeployToUpdraftBuilder builds a deploy-to-updraft step with typed input methods.
type DeployToUpdraftBuilder struct{ *Builder }

// DeployToUpdraft creates a deploy-to-updraft step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.DeployToUpdraft("0")  // explicit default
//	step.DeployToUpdraft("1")                  // older major
func DeployToUpdraft(version ...string) *DeployToUpdraftBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &DeployToUpdraftBuilder{Builder: From("deploy-to-updraft", v)}
}

// WithApiKey sets updraft API_KEY.
func (b *DeployToUpdraftBuilder) WithApiKey(value string) *DeployToUpdraftBuilder {
	b.Builder.WithInput("api_key", value)
	return b
}

// WithAppKey sets updraft APP_KEY.
func (b *DeployToUpdraftBuilder) WithAppKey(value string) *DeployToUpdraftBuilder {
	b.Builder.WithInput("app_key", value)
	return b
}

// WithAppPath sets app file path.
func (b *DeployToUpdraftBuilder) WithAppPath(value string) *DeployToUpdraftBuilder {
	b.Builder.WithInput("app_path", value)
	return b
}

// WithReleaseNotes sets release notes.
func (b *DeployToUpdraftBuilder) WithReleaseNotes(value string) *DeployToUpdraftBuilder {
	b.Builder.WithInput("release_notes", value)
	return b
}
