// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: export-xcarchive (2.2.0)

package step

// ExportXcarchiveV2ExportMethod enumerates the valid values for the export_method input.
type ExportXcarchiveV2ExportMethod string

const (
	ExportXcarchiveV2ExportMethodAutoDetect  ExportXcarchiveV2ExportMethod = "auto-detect"
	ExportXcarchiveV2ExportMethodAppStore    ExportXcarchiveV2ExportMethod = "app-store"
	ExportXcarchiveV2ExportMethodAdHoc       ExportXcarchiveV2ExportMethod = "ad-hoc"
	ExportXcarchiveV2ExportMethodEnterprise  ExportXcarchiveV2ExportMethod = "enterprise"
	ExportXcarchiveV2ExportMethodDevelopment ExportXcarchiveV2ExportMethod = "development"
)

// ExportXcarchiveV2UploadBitcode enumerates the valid values for the upload_bitcode input.
type ExportXcarchiveV2UploadBitcode string

const (
	ExportXcarchiveV2UploadBitcodeYes ExportXcarchiveV2UploadBitcode = "yes"
	ExportXcarchiveV2UploadBitcodeNo  ExportXcarchiveV2UploadBitcode = "no"
)

// ExportXcarchiveV2CompileBitcode enumerates the valid values for the compile_bitcode input.
type ExportXcarchiveV2CompileBitcode string

const (
	ExportXcarchiveV2CompileBitcodeYes ExportXcarchiveV2CompileBitcode = "yes"
	ExportXcarchiveV2CompileBitcodeNo  ExportXcarchiveV2CompileBitcode = "no"
)

// ExportXcarchiveV2Product enumerates the valid values for the product input.
type ExportXcarchiveV2Product string

const (
	ExportXcarchiveV2ProductApp     ExportXcarchiveV2Product = "app"
	ExportXcarchiveV2ProductAppClip ExportXcarchiveV2Product = "app-clip"
)

// ExportXcarchiveV2UseLegacyExport enumerates the valid values for the use_legacy_export input.
type ExportXcarchiveV2UseLegacyExport string

const (
	ExportXcarchiveV2UseLegacyExportYes ExportXcarchiveV2UseLegacyExport = "yes"
	ExportXcarchiveV2UseLegacyExportNo  ExportXcarchiveV2UseLegacyExport = "no"
)

// ExportXcarchiveV2VerboseLog enumerates the valid values for the verbose_log input.
type ExportXcarchiveV2VerboseLog string

const (
	ExportXcarchiveV2VerboseLogYes ExportXcarchiveV2VerboseLog = "yes"
	ExportXcarchiveV2VerboseLogNo  ExportXcarchiveV2VerboseLog = "no"
)

// ExportXcarchiveV2Builder builds a export-xcarchive step with typed input methods.
type ExportXcarchiveV2Builder struct{ *Builder }

// ExportXcarchiveV2 creates a export-xcarchive step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.ExportXcarchiveV2("2")  // explicit default
//	step.ExportXcarchiveV2("1")                  // older major
func ExportXcarchiveV2(version ...string) *ExportXcarchiveV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ExportXcarchiveV2Builder{Builder: From("export-xcarchive", v)}
}

// WithArchivePath sets iOS or tvOS archive path.
func (b *ExportXcarchiveV2Builder) WithArchivePath(value string) *ExportXcarchiveV2Builder {
	b.Builder.WithInput("archive_path", value)
	return b
}

// WithExportMethod sets select method for export.
func (b *ExportXcarchiveV2Builder) WithExportMethod(value ExportXcarchiveV2ExportMethod) *ExportXcarchiveV2Builder {
	b.Builder.WithInput("export_method", string(value))
	return b
}

// WithUploadBitcode sets include bitcode.
func (b *ExportXcarchiveV2Builder) WithUploadBitcode(value ExportXcarchiveV2UploadBitcode) *ExportXcarchiveV2Builder {
	b.Builder.WithInput("upload_bitcode", string(value))
	return b
}

// WithCompileBitcode sets rebuild from bitcode.
func (b *ExportXcarchiveV2Builder) WithCompileBitcode(value ExportXcarchiveV2CompileBitcode) *ExportXcarchiveV2Builder {
	b.Builder.WithInput("compile_bitcode", string(value))
	return b
}

// WithTeamId sets the Developer Portal team to use for this export.
func (b *ExportXcarchiveV2Builder) WithTeamId(value string) *ExportXcarchiveV2Builder {
	b.Builder.WithInput("team_id", value)
	return b
}

// WithProduct sets select a product to distribute.
func (b *ExportXcarchiveV2Builder) WithProduct(value ExportXcarchiveV2Product) *ExportXcarchiveV2Builder {
	b.Builder.WithInput("product", string(value))
	return b
}

// WithCustomExportOptionsPlistContent sets custom export options plist content.
func (b *ExportXcarchiveV2Builder) WithCustomExportOptionsPlistContent(value string) *ExportXcarchiveV2Builder {
	b.Builder.WithInput("custom_export_options_plist_content", value)
	return b
}

// WithUseLegacyExport sets use legacy ipa export method?.
func (b *ExportXcarchiveV2Builder) WithUseLegacyExport(value ExportXcarchiveV2UseLegacyExport) *ExportXcarchiveV2Builder {
	b.Builder.WithInput("use_legacy_export", string(value))
	return b
}

// WithVerboseLog sets enable verbose logging?.
func (b *ExportXcarchiveV2Builder) WithVerboseLog(value ExportXcarchiveV2VerboseLog) *ExportXcarchiveV2Builder {
	b.Builder.WithInput("verbose_log", string(value))
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *ExportXcarchiveV2Builder) WithRunIf(expr string) *ExportXcarchiveV2Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *ExportXcarchiveV2Builder) WithIsAlwaysRun(v bool) *ExportXcarchiveV2Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *ExportXcarchiveV2Builder) WithIsSkippable(v bool) *ExportXcarchiveV2Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *ExportXcarchiveV2Builder) WithTitle(title string) *ExportXcarchiveV2Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *ExportXcarchiveV2Builder) WithTimeout(seconds int) *ExportXcarchiveV2Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *ExportXcarchiveV2Builder) WithNoOutputTimeout(seconds int) *ExportXcarchiveV2Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *ExportXcarchiveV2Builder) WithExecutionContainer(containerID string) *ExportXcarchiveV2Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *ExportXcarchiveV2Builder) WithServiceContainers(containerIDs ...string) *ExportXcarchiveV2Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// exportXcarchiveV2Outputs holds the names of environment variables published
// by the export-xcarchive step (v2) at run time.
type exportXcarchiveV2Outputs struct {
	// BitriseIpaPath is the "The created iOS or tvOS .ipa file's path." output env var.
	BitriseIpaPath string
	// BitriseDsymPath is the "The created iOS or tvOS .dSYM zip file's path." output env var.
	BitriseDsymPath string
	// BitriseIdedistributionLogsPath is the "Path to the xcdistributionlogs zip" output env var.
	BitriseIdedistributionLogsPath string
}

// ExportXcarchiveV2Outputs provides typed access to the environment variable names
// that export-xcarchive (v2) exports after a successful run.
var ExportXcarchiveV2Outputs = exportXcarchiveV2Outputs{
	BitriseIpaPath:                 "BITRISE_IPA_PATH",
	BitriseDsymPath:                "BITRISE_DSYM_PATH",
	BitriseIdedistributionLogsPath: "BITRISE_IDEDISTRIBUTION_LOGS_PATH",
}
