// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: appetize-deploy (0.10.0)

package step

// AppetizeDeployVerbose enumerates the valid values for the verbose input.
type AppetizeDeployVerbose string

const (
	AppetizeDeployVerboseTrue  AppetizeDeployVerbose = "true"
	AppetizeDeployVerboseFalse AppetizeDeployVerbose = "false"
)

// AppetizeDeployBuilder builds a appetize-deploy step with typed input methods.
type AppetizeDeployBuilder struct{ *Builder }

// AppetizeDeploy creates a appetize-deploy step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.AppetizeDeploy("0")  // explicit default
//	step.AppetizeDeploy("1")                  // older major
func AppetizeDeploy(version ...string) *AppetizeDeployBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &AppetizeDeployBuilder{Builder: From("appetize-deploy", v)}
}

// WithAppPath sets application path.
func (b *AppetizeDeployBuilder) WithAppPath(value string) *AppetizeDeployBuilder {
	b.Builder.WithInput("app_path", value)
	return b
}

// WithAppetizeToken sets appetize.io API Token.
func (b *AppetizeDeployBuilder) WithAppetizeToken(value string) *AppetizeDeployBuilder {
	b.Builder.WithInput("appetize_token", value)
	return b
}

// WithPublicKey sets public key.
func (b *AppetizeDeployBuilder) WithPublicKey(value string) *AppetizeDeployBuilder {
	b.Builder.WithInput("public_key", value)
	return b
}

// WithAppetizeApi sets appetize.io api endpoint.
func (b *AppetizeDeployBuilder) WithAppetizeApi(value string) *AppetizeDeployBuilder {
	b.Builder.WithInput("appetize_api", value)
	return b
}

// WithAppetizeHost sets appetize.io host.
func (b *AppetizeDeployBuilder) WithAppetizeHost(value string) *AppetizeDeployBuilder {
	b.Builder.WithInput("appetize_host", value)
	return b
}

// WithVerbose sets enable verbose logging.
func (b *AppetizeDeployBuilder) WithVerbose(value AppetizeDeployVerbose) *AppetizeDeployBuilder {
	b.Builder.WithInput("verbose", string(value))
	return b
}

// appetizeDeployOutputs holds the names of environment variables published
// by the appetize-deploy step (v0) at run time.
type appetizeDeployOutputs struct {
	// AppetizeAppUrl is the "Public URL for the app" output env var.
	AppetizeAppUrl string
}

// AppetizeDeployOutputs provides typed access to the environment variable names
// that appetize-deploy (v0) exports after a successful run.
var AppetizeDeployOutputs = appetizeDeployOutputs{
	AppetizeAppUrl: "APPETIZE_APP_URL",
}
