// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: openstf-disconnect (0.0.6)

package step

// OpenstfDisconnectBuilder builds a openstf-disconnect step with typed input methods.
type OpenstfDisconnectBuilder struct{ *Builder }

// OpenstfDisconnect creates a openstf-disconnect step builder (v0).
func OpenstfDisconnect(version ...string) *OpenstfDisconnectBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &OpenstfDisconnectBuilder{Builder: From("openstf-disconnect", v)}
}

// WithStfHostUrl sets sTF Host URL.
func (b *OpenstfDisconnectBuilder) WithStfHostUrl(value string) *OpenstfDisconnectBuilder {
	b.Builder.WithInput("stf_host_url", value)
	return b
}

// WithStfAccessToken sets sTF API access token.
func (b *OpenstfDisconnectBuilder) WithStfAccessToken(value string) *OpenstfDisconnectBuilder {
	b.Builder.WithInput("stf_access_token", value)
	return b
}

// WithStfDeviceSerialList sets connected devices serials.
func (b *OpenstfDisconnectBuilder) WithStfDeviceSerialList(value string) *OpenstfDisconnectBuilder {
	b.Builder.WithInput("stf_device_serial_list", value)
	return b
}
