// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: disable-iphonesimulator-connect-hardware-keyboard (0.1.1)

package step

// DisableIphonesimulatorConnectHardwareKeyboardBuilder builds a disable-iphonesimulator-connect-hardware-keyboard step with typed input methods.
type DisableIphonesimulatorConnectHardwareKeyboardBuilder struct{ *Builder }

// DisableIphonesimulatorConnectHardwareKeyboard creates a disable-iphonesimulator-connect-hardware-keyboard step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.DisableIphonesimulatorConnectHardwareKeyboard("0")  // explicit default
//	step.DisableIphonesimulatorConnectHardwareKeyboard("1")                  // older major
func DisableIphonesimulatorConnectHardwareKeyboard(version ...string) *DisableIphonesimulatorConnectHardwareKeyboardBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &DisableIphonesimulatorConnectHardwareKeyboardBuilder{Builder: From("disable-iphonesimulator-connect-hardware-keyboard", v)}
}

// WithIphonesimulatorPreferencesPth sets iphonesimulator preferences path.
func (b *DisableIphonesimulatorConnectHardwareKeyboardBuilder) WithIphonesimulatorPreferencesPth(value string) *DisableIphonesimulatorConnectHardwareKeyboardBuilder {
	b.Builder.WithInput("iphonesimulator_preferences_pth", value)
	return b
}

// WithVerbose sets verbose.
func (b *DisableIphonesimulatorConnectHardwareKeyboardBuilder) WithVerbose(value string) *DisableIphonesimulatorConnectHardwareKeyboardBuilder {
	b.Builder.WithInput("verbose", value)
	return b
}
