// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xcode-project-info (2.1.0)

package step

// XcodeProjectInfoV2Builder builds a xcode-project-info step with typed input methods.
type XcodeProjectInfoV2Builder struct{ *Builder }

// XcodeProjectInfoV2 creates a xcode-project-info step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.XcodeProjectInfoV2("2")  // explicit default
//	step.XcodeProjectInfoV2("1")                  // older major
func XcodeProjectInfoV2(version ...string) *XcodeProjectInfoV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &XcodeProjectInfoV2Builder{Builder: From("xcode-project-info", v)}
}

// WithInfoPlistPath sets relative path from Source directory to Info.plist file.
func (b *XcodeProjectInfoV2Builder) WithInfoPlistPath(value string) *XcodeProjectInfoV2Builder {
	b.Builder.WithInput("info_plist_path", value)
	return b
}

// WithXcodeprojPath sets relative path from Source directory to Xcode project file.
func (b *XcodeProjectInfoV2Builder) WithXcodeprojPath(value string) *XcodeProjectInfoV2Builder {
	b.Builder.WithInput("xcodeproj_path", value)
	return b
}

// WithTarget sets for Xcode 11+ projects, get the version & build for this target.
func (b *XcodeProjectInfoV2Builder) WithTarget(value string) *XcodeProjectInfoV2Builder {
	b.Builder.WithInput("target", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *XcodeProjectInfoV2Builder) WithRunIf(expr string) *XcodeProjectInfoV2Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *XcodeProjectInfoV2Builder) WithIsAlwaysRun(v bool) *XcodeProjectInfoV2Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *XcodeProjectInfoV2Builder) WithIsSkippable(v bool) *XcodeProjectInfoV2Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *XcodeProjectInfoV2Builder) WithTitle(title string) *XcodeProjectInfoV2Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *XcodeProjectInfoV2Builder) WithTimeout(seconds int) *XcodeProjectInfoV2Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *XcodeProjectInfoV2Builder) WithNoOutputTimeout(seconds int) *XcodeProjectInfoV2Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *XcodeProjectInfoV2Builder) WithExecutionContainer(containerID string) *XcodeProjectInfoV2Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *XcodeProjectInfoV2Builder) WithServiceContainers(containerIDs ...string) *XcodeProjectInfoV2Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// xcodeProjectInfoV2Outputs holds the names of environment variables published
// by the xcode-project-info step (v2) at run time.
type xcodeProjectInfoV2Outputs struct {
	// XpiVersion is the "Version ($CFBundleShortVersionString or $MARKETING_VERSION)" output env var.
	XpiVersion string
	// XpiBuild is the "Build ($CFBundleVersion or $CURRENT_PROJECT_VERSION)" output env var.
	XpiBuild string
}

// XcodeProjectInfoV2Outputs provides typed access to the environment variable names
// that xcode-project-info (v2) exports after a successful run.
var XcodeProjectInfoV2Outputs = xcodeProjectInfoV2Outputs{
	XpiVersion: "XPI_VERSION",
	XpiBuild:   "XPI_BUILD",
}
