// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: pagerduty (0.1.2)

package step

// PagerdutyBuilder builds a pagerduty step with typed input methods.
type PagerdutyBuilder struct{ *Builder }

// Pagerduty creates a pagerduty step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.Pagerduty("0")  // explicit default
//	step.Pagerduty("1")                  // older major
func Pagerduty(version ...string) *PagerdutyBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &PagerdutyBuilder{Builder: From("pagerduty", v)}
}

// WithApiVersion sets aPI version.
func (b *PagerdutyBuilder) WithApiVersion(value string) *PagerdutyBuilder {
	b.Builder.WithInput("api_version", value)
	return b
}

// WithIntegrationKey sets integration key.
func (b *PagerdutyBuilder) WithIntegrationKey(value string) *PagerdutyBuilder {
	b.Builder.WithInput("integration_key", value)
	return b
}

// WithEventDescription sets event description.
func (b *PagerdutyBuilder) WithEventDescription(value string) *PagerdutyBuilder {
	b.Builder.WithInput("event_description", value)
	return b
}

// WithSeverity sets event severity (API v2 only).
func (b *PagerdutyBuilder) WithSeverity(value string) *PagerdutyBuilder {
	b.Builder.WithInput("severity", value)
	return b
}

// pagerdutyOutputs holds the names of environment variables published
// by the pagerduty step (v0) at run time.
type pagerdutyOutputs struct {
	// PagerdutyEventMessage is the "PagerDuty event creation message" output env var.
	PagerdutyEventMessage string
	// PagerdutyIncidentKey is the "PagerDuty event creation incident_key" output env var.
	PagerdutyIncidentKey string
	// PagerdutyDedupKey is the "PagerDuty event creation dedup_key" output env var.
	PagerdutyDedupKey string
}

// PagerdutyOutputs provides typed access to the environment variable names
// that pagerduty (v0) exports after a successful run.
var PagerdutyOutputs = pagerdutyOutputs{
	PagerdutyEventMessage: "PAGERDUTY_EVENT_MESSAGE",
	PagerdutyIncidentKey:  "PAGERDUTY_INCIDENT_KEY",
	PagerdutyDedupKey:     "PAGERDUTY_DEDUP_KEY",
}
