// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: lifx-notifier (1.2.1)

package step

// LifxNotifierSelectorType enumerates the valid values for the selector_type input.
type LifxNotifierSelectorType string

const (
	LifxNotifierSelectorTypeAll      LifxNotifierSelectorType = "all"
	LifxNotifierSelectorTypeLabel    LifxNotifierSelectorType = "label"
	LifxNotifierSelectorTypeGroup    LifxNotifierSelectorType = "group"
	LifxNotifierSelectorTypeLocation LifxNotifierSelectorType = "location"
)

// LifxNotifierColorBuildSuccess enumerates the valid values for the color_build_success input.
type LifxNotifierColorBuildSuccess string

const (
	LifxNotifierColorBuildSuccessBlue   LifxNotifierColorBuildSuccess = "blue"
	LifxNotifierColorBuildSuccessCyan   LifxNotifierColorBuildSuccess = "cyan"
	LifxNotifierColorBuildSuccessGreen  LifxNotifierColorBuildSuccess = "green"
	LifxNotifierColorBuildSuccessOrange LifxNotifierColorBuildSuccess = "orange"
	LifxNotifierColorBuildSuccessPink   LifxNotifierColorBuildSuccess = "pink"
	LifxNotifierColorBuildSuccessPurple LifxNotifierColorBuildSuccess = "purple"
	LifxNotifierColorBuildSuccessRed    LifxNotifierColorBuildSuccess = "red"
	LifxNotifierColorBuildSuccessYellow LifxNotifierColorBuildSuccess = "yellow"
	LifxNotifierColorBuildSuccessWhite  LifxNotifierColorBuildSuccess = "white"
)

// LifxNotifierColorBuildFailure enumerates the valid values for the color_build_failure input.
type LifxNotifierColorBuildFailure string

const (
	LifxNotifierColorBuildFailureBlue   LifxNotifierColorBuildFailure = "blue"
	LifxNotifierColorBuildFailureCyan   LifxNotifierColorBuildFailure = "cyan"
	LifxNotifierColorBuildFailureGreen  LifxNotifierColorBuildFailure = "green"
	LifxNotifierColorBuildFailureOrange LifxNotifierColorBuildFailure = "orange"
	LifxNotifierColorBuildFailurePink   LifxNotifierColorBuildFailure = "pink"
	LifxNotifierColorBuildFailurePurple LifxNotifierColorBuildFailure = "purple"
	LifxNotifierColorBuildFailureRed    LifxNotifierColorBuildFailure = "red"
	LifxNotifierColorBuildFailureYellow LifxNotifierColorBuildFailure = "yellow"
	LifxNotifierColorBuildFailureWhite  LifxNotifierColorBuildFailure = "white"
)

// LifxNotifierEffect enumerates the valid values for the effect input.
type LifxNotifierEffect string

const (
	LifxNotifierEffectNone    LifxNotifierEffect = "none"
	LifxNotifierEffectPulse   LifxNotifierEffect = "pulse"
	LifxNotifierEffectBreathe LifxNotifierEffect = "breathe"
)

// LifxNotifierBuilder builds a lifx-notifier step with typed input methods.
type LifxNotifierBuilder struct{ *Builder }

// LifxNotifier creates a lifx-notifier step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.LifxNotifier("1")  // explicit default
//	step.LifxNotifier("1")                  // older major
func LifxNotifier(version ...string) *LifxNotifierBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &LifxNotifierBuilder{Builder: From("lifx-notifier", v)}
}

// WithAuthToken sets authentication token.
func (b *LifxNotifierBuilder) WithAuthToken(value string) *LifxNotifierBuilder {
	b.Builder.WithInput("auth_token", value)
	return b
}

// WithSelectorType sets selector type.
func (b *LifxNotifierBuilder) WithSelectorType(value LifxNotifierSelectorType) *LifxNotifierBuilder {
	b.Builder.WithInput("selector_type", string(value))
	return b
}

// WithBulbLabel sets lIFX light(s) selector label.
func (b *LifxNotifierBuilder) WithBulbLabel(value string) *LifxNotifierBuilder {
	b.Builder.WithInput("bulb_label", value)
	return b
}

// WithColorBuildSuccess sets build success color (LIFX default).
func (b *LifxNotifierBuilder) WithColorBuildSuccess(value LifxNotifierColorBuildSuccess) *LifxNotifierBuilder {
	b.Builder.WithInput("color_build_success", string(value))
	return b
}

// WithColorBuildSuccessCustom sets build success color (custom).
func (b *LifxNotifierBuilder) WithColorBuildSuccessCustom(value string) *LifxNotifierBuilder {
	b.Builder.WithInput("color_build_success_custom", value)
	return b
}

// WithColorBuildFailure sets build failure color (LIFX default).
func (b *LifxNotifierBuilder) WithColorBuildFailure(value LifxNotifierColorBuildFailure) *LifxNotifierBuilder {
	b.Builder.WithInput("color_build_failure", string(value))
	return b
}

// WithColorBuildFailureCustom sets build failure color (custom).
func (b *LifxNotifierBuilder) WithColorBuildFailureCustom(value string) *LifxNotifierBuilder {
	b.Builder.WithInput("color_build_failure_custom", value)
	return b
}

// WithEffect sets effect.
func (b *LifxNotifierBuilder) WithEffect(value LifxNotifierEffect) *LifxNotifierBuilder {
	b.Builder.WithInput("effect", string(value))
	return b
}

// WithCycles sets number of Effect Cycles.
func (b *LifxNotifierBuilder) WithCycles(value string) *LifxNotifierBuilder {
	b.Builder.WithInput("cycles", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *LifxNotifierBuilder) WithRunIf(expr string) *LifxNotifierBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *LifxNotifierBuilder) WithIsAlwaysRun(v bool) *LifxNotifierBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *LifxNotifierBuilder) WithIsSkippable(v bool) *LifxNotifierBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *LifxNotifierBuilder) WithTitle(title string) *LifxNotifierBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *LifxNotifierBuilder) WithTimeout(seconds int) *LifxNotifierBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *LifxNotifierBuilder) WithNoOutputTimeout(seconds int) *LifxNotifierBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *LifxNotifierBuilder) WithExecutionContainer(containerID string) *LifxNotifierBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *LifxNotifierBuilder) WithServiceContainers(containerIDs ...string) *LifxNotifierBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
