// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: build-status-change (0.1.2)

package step

import "time"

// BuildStatusChangeVerbose enumerates the valid values for the verbose input.
type BuildStatusChangeVerbose string

const (
	BuildStatusChangeVerboseNo  BuildStatusChangeVerbose = "no"
	BuildStatusChangeVerboseYes BuildStatusChangeVerbose = "yes"
)

// BuildStatusChangeBuilder builds a build-status-change step with typed input methods.
type BuildStatusChangeBuilder struct{ *Builder }

// BuildStatusChange creates a build-status-change step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.BuildStatusChange("0")  // explicit default
//	step.BuildStatusChange("1")                  // older major
func BuildStatusChange(version ...string) *BuildStatusChangeBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &BuildStatusChangeBuilder{Builder: From("build-status-change", v)}
}

// WithAccessToken sets bitrise Access Token.
func (b *BuildStatusChangeBuilder) WithAccessToken(value string) *BuildStatusChangeBuilder {
	b.Builder.WithInput("access_token", value)
	return b
}

// WithVerbose sets enable verbose logging?.
func (b *BuildStatusChangeBuilder) WithVerbose(value BuildStatusChangeVerbose) *BuildStatusChangeBuilder {
	b.Builder.WithInput("verbose", string(value))
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *BuildStatusChangeBuilder) WithRunIf(expr string) *BuildStatusChangeBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *BuildStatusChangeBuilder) WithIsAlwaysRun(v bool) *BuildStatusChangeBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *BuildStatusChangeBuilder) WithIsSkippable(v bool) *BuildStatusChangeBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *BuildStatusChangeBuilder) WithTitle(title string) *BuildStatusChangeBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *BuildStatusChangeBuilder) WithTimeout(seconds int) *BuildStatusChangeBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *BuildStatusChangeBuilder) WithNoOutputTimeout(seconds int) *BuildStatusChangeBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *BuildStatusChangeBuilder) WithTimeoutDuration(d time.Duration) *BuildStatusChangeBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *BuildStatusChangeBuilder) WithNoOutputTimeoutDuration(d time.Duration) *BuildStatusChangeBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *BuildStatusChangeBuilder) WithExecutionContainer(containerID string) *BuildStatusChangeBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *BuildStatusChangeBuilder) WithServiceContainers(containerIDs ...string) *BuildStatusChangeBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// buildStatusChangeOutputs holds the names of environment variables published
// by the build-status-change step (v0) at run time.
type buildStatusChangeOutputs struct {
	// BuildStatusChanged is the "Build Status Changed" output env var.
	BuildStatusChanged string
	// PreviousBuildStatus is the "Previous Build Status" output env var.
	PreviousBuildStatus string
}

// BuildStatusChangeOutputs provides typed access to the environment variable names
// that build-status-change (v0) exports after a successful run.
var BuildStatusChangeOutputs = buildStatusChangeOutputs{
	BuildStatusChanged:  "BUILD_STATUS_CHANGED",
	PreviousBuildStatus: "PREVIOUS_BUILD_STATUS",
}
