// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: upload-gradle-github-dependencies (0.1.0)

package step

import "time"

// UploadGradleGithubDependenciesBuilder builds a upload-gradle-github-dependencies step with typed input methods.
type UploadGradleGithubDependenciesBuilder struct{ *Builder }

// UploadGradleGithubDependencies creates a upload-gradle-github-dependencies step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.UploadGradleGithubDependencies("0")  // explicit default
//	step.UploadGradleGithubDependencies("1")                  // older major
func UploadGradleGithubDependencies(version ...string) *UploadGradleGithubDependenciesBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &UploadGradleGithubDependenciesBuilder{Builder: From("upload-gradle-github-dependencies", v)}
}

// WithGradlewPath sets gradlew file path.
func (b *UploadGradleGithubDependenciesBuilder) WithGradlewPath(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("gradlew_path", value)
	return b
}

// WithGithubToken sets github Access Token.
func (b *UploadGradleGithubDependenciesBuilder) WithGithubToken(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("github_token", value)
	return b
}

// WithIncludedProjects sets included projects.
func (b *UploadGradleGithubDependenciesBuilder) WithIncludedProjects(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("included_projects", value)
	return b
}

// WithExcludedProjects sets excluded projects.
func (b *UploadGradleGithubDependenciesBuilder) WithExcludedProjects(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("excluded_projects", value)
	return b
}

// WithIncludedConfigurations sets included configurations.
func (b *UploadGradleGithubDependenciesBuilder) WithIncludedConfigurations(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("included_configurations", value)
	return b
}

// WithExcludedConfigurations sets excluded configurations.
func (b *UploadGradleGithubDependenciesBuilder) WithExcludedConfigurations(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("excluded_configurations", value)
	return b
}

// WithRuntimeIncludedProjects sets runtime included projects.
func (b *UploadGradleGithubDependenciesBuilder) WithRuntimeIncludedProjects(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("runtime_included_projects", value)
	return b
}

// WithRuntimeExcludedProjects sets runtime excluded projects.
func (b *UploadGradleGithubDependenciesBuilder) WithRuntimeExcludedProjects(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("runtime_excluded_projects", value)
	return b
}

// WithRuntimeIncludedConfigurations sets runtime included configurations.
func (b *UploadGradleGithubDependenciesBuilder) WithRuntimeIncludedConfigurations(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("runtime_included_configurations", value)
	return b
}

// WithRuntimeExcludedConfigurations sets runtime excluded configurations.
func (b *UploadGradleGithubDependenciesBuilder) WithRuntimeExcludedConfigurations(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("runtime_excluded_configurations", value)
	return b
}

// WithGithubJobCorrelator sets github Dependency Graph Job Correlator.
func (b *UploadGradleGithubDependenciesBuilder) WithGithubJobCorrelator(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("github_job_correlator", value)
	return b
}

// WithGithubJobId sets github Dependency Graph Job ID.
func (b *UploadGradleGithubDependenciesBuilder) WithGithubJobId(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("github_job_id", value)
	return b
}

// WithGithubGraphRef sets github Dependency Graph Ref.
func (b *UploadGradleGithubDependenciesBuilder) WithGithubGraphRef(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("github_graph_ref", value)
	return b
}

// WithGithubGraphSha sets github Commit SHA-1 Hash.
func (b *UploadGradleGithubDependenciesBuilder) WithGithubGraphSha(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("github_graph_sha", value)
	return b
}

// WithGithubGraphWorkspace sets github Dependency Graph Workspace.
func (b *UploadGradleGithubDependenciesBuilder) WithGithubGraphWorkspace(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("github_graph_workspace", value)
	return b
}

// WithGithubOwner sets gitHub repository owner.
func (b *UploadGradleGithubDependenciesBuilder) WithGithubOwner(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("github_owner", value)
	return b
}

// WithGithubRepo sets gitHub repository.
func (b *UploadGradleGithubDependenciesBuilder) WithGithubRepo(value string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithInput("github_repo", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *UploadGradleGithubDependenciesBuilder) WithRunIf(expr string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *UploadGradleGithubDependenciesBuilder) WithIsAlwaysRun(v bool) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *UploadGradleGithubDependenciesBuilder) WithIsSkippable(v bool) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *UploadGradleGithubDependenciesBuilder) WithTitle(title string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *UploadGradleGithubDependenciesBuilder) WithTimeout(seconds int) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *UploadGradleGithubDependenciesBuilder) WithNoOutputTimeout(seconds int) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *UploadGradleGithubDependenciesBuilder) WithTimeoutDuration(d time.Duration) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *UploadGradleGithubDependenciesBuilder) WithNoOutputTimeoutDuration(d time.Duration) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *UploadGradleGithubDependenciesBuilder) WithExecutionContainer(containerID string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *UploadGradleGithubDependenciesBuilder) WithServiceContainers(containerIDs ...string) *UploadGradleGithubDependenciesBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// uploadGradleGithubDependenciesOutputs holds the names of environment variables published
// by the upload-gradle-github-dependencies step (v0) at run time.
type uploadGradleGithubDependenciesOutputs struct {
	// GithubDependencyGraph is the "Path to Github dependency graph" output env var.
	GithubDependencyGraph string
}

// UploadGradleGithubDependenciesOutputs provides typed access to the environment variable names
// that upload-gradle-github-dependencies (v0) exports after a successful run.
var UploadGradleGithubDependenciesOutputs = uploadGradleGithubDependenciesOutputs{
	GithubDependencyGraph: "GITHUB_DEPENDENCY_GRAPH",
}
