// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: android-manifest-info (1.0.2)

package step

import "time"

// AndroidManifestInfoBuilder builds a android-manifest-info step with typed input methods.
type AndroidManifestInfoBuilder struct{ *Builder }

// AndroidManifestInfo creates a android-manifest-info step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.AndroidManifestInfo("1")  // explicit default
//	step.AndroidManifestInfo("1")                  // older major
func AndroidManifestInfo(version ...string) *AndroidManifestInfoBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &AndroidManifestInfoBuilder{Builder: From("android-manifest-info", v)}
}

// WithManifestFile sets androidManifest.xml file path.
func (b *AndroidManifestInfoBuilder) WithManifestFile(value string) *AndroidManifestInfoBuilder {
	b.Builder.WithInput("manifest_file", value)
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *AndroidManifestInfoBuilder) WithVersion(version string) *AndroidManifestInfoBuilder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *AndroidManifestInfoBuilder) WithInput(key, value string) *AndroidManifestInfoBuilder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *AndroidManifestInfoBuilder) WithRunIf(expr string) *AndroidManifestInfoBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *AndroidManifestInfoBuilder) WithIsAlwaysRun(v bool) *AndroidManifestInfoBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *AndroidManifestInfoBuilder) WithIsSkippable(v bool) *AndroidManifestInfoBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *AndroidManifestInfoBuilder) WithTitle(title string) *AndroidManifestInfoBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *AndroidManifestInfoBuilder) WithTimeout(seconds int) *AndroidManifestInfoBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *AndroidManifestInfoBuilder) WithNoOutputTimeout(seconds int) *AndroidManifestInfoBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *AndroidManifestInfoBuilder) WithTimeoutDuration(d time.Duration) *AndroidManifestInfoBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *AndroidManifestInfoBuilder) WithNoOutputTimeoutDuration(d time.Duration) *AndroidManifestInfoBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *AndroidManifestInfoBuilder) WithExecutionContainer(containerID string) *AndroidManifestInfoBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *AndroidManifestInfoBuilder) WithServiceContainers(containerIDs ...string) *AndroidManifestInfoBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// androidManifestInfoOutputs holds the names of environment variables published
// by the android-manifest-info step (v1) at run time.
type androidManifestInfoOutputs struct {
	// AmiVersionCode is the "Version Code (versionCode from AndroidManifest.xml)" output env var.
	AmiVersionCode string
	// AmiVersionName is the "Version Name (versionName from AndroidManifest.xml)" output env var.
	AmiVersionName string
	// AmiPackageName is the "Package Name (package from AndroidManifest.xml)" output env var.
	AmiPackageName string
	// AmiMinSdkVersion is the "Minimum SDK Version (minSdkVersion from AndroidManifest.xml)" output env var.
	AmiMinSdkVersion string
	// AmiTargetSdkVersion is the "Target SDK Version (targetSdkVersion from AndroidManifest.xml)" output env var.
	AmiTargetSdkVersion string
}

// AndroidManifestInfoOutputs provides typed access to the environment variable names
// that android-manifest-info (v1) exports after a successful run.
var AndroidManifestInfoOutputs = androidManifestInfoOutputs{
	AmiVersionCode:      "AMI_VERSION_CODE",
	AmiVersionName:      "AMI_VERSION_NAME",
	AmiPackageName:      "AMI_PACKAGE_NAME",
	AmiMinSdkVersion:    "AMI_MIN_SDK_VERSION",
	AmiTargetSdkVersion: "AMI_TARGET_SDK_VERSION",
}
