// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: zipalign-apk (0.2.0)

package step

// ZipalignApkBuilder builds a zipalign-apk step with typed input methods.
type ZipalignApkBuilder struct{ *Builder }

// ZipalignApk creates a zipalign-apk step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.ZipalignApk("0")  // explicit default
//	step.ZipalignApk("1")                  // older major
func ZipalignApk(version ...string) *ZipalignApkBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ZipalignApkBuilder{Builder: From("zipalign-apk", v)}
}

// WithBitriseUnalignedApkPath sets unaligned APK Path.
func (b *ZipalignApkBuilder) WithBitriseUnalignedApkPath(value string) *ZipalignApkBuilder {
	b.Builder.WithInput("bitrise_unaligned_apk_path", value)
	return b
}
