// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: saucelabs-espresso-app-automate (0.1.6)

package step

// SaucelabsEspressoAppAutomateBuilder builds a saucelabs-espresso-app-automate step with typed input methods.
type SaucelabsEspressoAppAutomateBuilder struct{ *Builder }

// SaucelabsEspressoAppAutomate creates a saucelabs-espresso-app-automate step builder (v0).
func SaucelabsEspressoAppAutomate(version ...string) *SaucelabsEspressoAppAutomateBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &SaucelabsEspressoAppAutomateBuilder{Builder: From("saucelabs-espresso-app-automate", v)}
}

// WithAppApkPath sets app apk path.
func (b *SaucelabsEspressoAppAutomateBuilder) WithAppApkPath(value string) *SaucelabsEspressoAppAutomateBuilder {
	b.Builder.WithInput("app_apk_path", value)
	return b
}

// WithTestApkPath sets test suite apk path.
func (b *SaucelabsEspressoAppAutomateBuilder) WithTestApkPath(value string) *SaucelabsEspressoAppAutomateBuilder {
	b.Builder.WithInput("test_apk_path", value)
	return b
}

// WithSaucelabsUsername sets sauceLabs username.
func (b *SaucelabsEspressoAppAutomateBuilder) WithSaucelabsUsername(value string) *SaucelabsEspressoAppAutomateBuilder {
	b.Builder.WithInput("saucelabs_username", value)
	return b
}

// WithSaucelabsAccessKey sets sauceLabs access key.
func (b *SaucelabsEspressoAppAutomateBuilder) WithSaucelabsAccessKey(value string) *SaucelabsEspressoAppAutomateBuilder {
	b.Builder.WithInput("saucelabs_access_key", value)
	return b
}

// WithSaucelabsDeviceName sets device Name.
func (b *SaucelabsEspressoAppAutomateBuilder) WithSaucelabsDeviceName(value string) *SaucelabsEspressoAppAutomateBuilder {
	b.Builder.WithInput("saucelabs_device_name", value)
	return b
}

// WithSaucelabsDataCenter sets sauceLabs Data Center.
func (b *SaucelabsEspressoAppAutomateBuilder) WithSaucelabsDataCenter(value string) *SaucelabsEspressoAppAutomateBuilder {
	b.Builder.WithInput("saucelabs_data_center", value)
	return b
}
