// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: go-list (0.10.1)

package step

import "time"

// GoListV0Builder builds a go-list step with typed input methods.
type GoListV0Builder struct{ *Builder }

// GoListV0 creates a go-list step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.GoListV0("0")  // explicit default
//	step.GoListV0("1")                  // older major
func GoListV0(version ...string) *GoListV0Builder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &GoListV0Builder{Builder: From("go-list", v)}
}

// WithExclude sets exclude patterns.
func (b *GoListV0Builder) WithExclude(value string) *GoListV0Builder {
	b.Builder.WithInput("exclude", value)
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *GoListV0Builder) WithVersion(version string) *GoListV0Builder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *GoListV0Builder) WithInput(key, value string) *GoListV0Builder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *GoListV0Builder) WithRunIf(expr string) *GoListV0Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *GoListV0Builder) WithIsAlwaysRun(v bool) *GoListV0Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *GoListV0Builder) WithIsSkippable(v bool) *GoListV0Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *GoListV0Builder) WithTitle(title string) *GoListV0Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *GoListV0Builder) WithTimeout(seconds int) *GoListV0Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *GoListV0Builder) WithNoOutputTimeout(seconds int) *GoListV0Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *GoListV0Builder) WithTimeoutDuration(d time.Duration) *GoListV0Builder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *GoListV0Builder) WithNoOutputTimeoutDuration(d time.Duration) *GoListV0Builder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *GoListV0Builder) WithExecutionContainer(containerID string) *GoListV0Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *GoListV0Builder) WithServiceContainers(containerIDs ...string) *GoListV0Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// goListV0Outputs holds the names of environment variables published
// by the go-list step (v0) at run time.
type goListV0Outputs struct {
	// BitriseGoPackages is the "List of go packages." output env var.
	BitriseGoPackages string
}

// GoListV0Outputs provides typed access to the environment variable names
// that go-list (v0) exports after a successful run.
var GoListV0Outputs = goListV0Outputs{
	BitriseGoPackages: "BITRISE_GO_PACKAGES",
}
