// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: trigger-bitrise-workflow (0.0.8)

package step

// TriggerBitriseWorkflowBuilder builds a trigger-bitrise-workflow step with typed input methods.
type TriggerBitriseWorkflowBuilder struct{ *Builder }

// TriggerBitriseWorkflow creates a trigger-bitrise-workflow step builder (v0).
func TriggerBitriseWorkflow() *TriggerBitriseWorkflowBuilder {
	return &TriggerBitriseWorkflowBuilder{Builder: From("trigger-bitrise-workflow", "0")}
}

// WithAppSlug sets bitrise App Slug.
func (b *TriggerBitriseWorkflowBuilder) WithAppSlug(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("app_slug", value)
	return b
}

// WithApiToken sets build trigger API Token.
func (b *TriggerBitriseWorkflowBuilder) WithApiToken(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("api_token", value)
	return b
}

// WithBranch sets (Source) Branch to build.
func (b *TriggerBitriseWorkflowBuilder) WithBranch(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("branch", value)
	return b
}

// WithTag sets git Tag to build.
func (b *TriggerBitriseWorkflowBuilder) WithTag(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("tag", value)
	return b
}

// WithCommitHash sets git commit hash to build.
func (b *TriggerBitriseWorkflowBuilder) WithCommitHash(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("commit_hash", value)
	return b
}

// WithCommitMessage sets git commit message (or build's message).
func (b *TriggerBitriseWorkflowBuilder) WithCommitMessage(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("commit_message", value)
	return b
}

// WithWorkflowId sets workflow ID.
func (b *TriggerBitriseWorkflowBuilder) WithWorkflowId(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("workflow_id", value)
	return b
}

// WithBranchDest sets pull request destination branch.
func (b *TriggerBitriseWorkflowBuilder) WithBranchDest(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("branch_dest", value)
	return b
}

// WithPullRequestId sets pull Request ID.
func (b *TriggerBitriseWorkflowBuilder) WithPullRequestId(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("pull_request_id", value)
	return b
}

// WithPullRequestRepositoryUrl sets pull Request repository URL.
func (b *TriggerBitriseWorkflowBuilder) WithPullRequestRepositoryUrl(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("pull_request_repository_url", value)
	return b
}

// WithPullRequestMergeBranch sets pull Request pre-merge branch.
func (b *TriggerBitriseWorkflowBuilder) WithPullRequestMergeBranch(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("pull_request_merge_branch", value)
	return b
}

// WithPullRequestHeadBranch sets pull Request head branch.
func (b *TriggerBitriseWorkflowBuilder) WithPullRequestHeadBranch(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("pull_request_head_branch", value)
	return b
}

// WithExportedEnvironmentVariableNames sets names of environment variables to export.
func (b *TriggerBitriseWorkflowBuilder) WithExportedEnvironmentVariableNames(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("exported_environment_variable_names", value)
	return b
}

// WithBranchRepoOwner sets pull Request source repo owner.
func (b *TriggerBitriseWorkflowBuilder) WithBranchRepoOwner(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("branch_repo_owner", value)
	return b
}

// WithBranchDestRepoOwner sets pull Request destination repo owner.
func (b *TriggerBitriseWorkflowBuilder) WithBranchDestRepoOwner(value string) *TriggerBitriseWorkflowBuilder {
	b.Builder.WithInput("branch_dest_repo_owner", value)
	return b
}
