// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: badgetizr (3.0.3)

package step

// BadgetizrBuilder builds a badgetizr step with typed input methods.
type BadgetizrBuilder struct{ *Builder }

// Badgetizr creates a badgetizr step builder (v3).
func Badgetizr(version ...string) *BadgetizrBuilder {
	v := "3"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &BadgetizrBuilder{Builder: From("badgetizr", v)}
}

// WithPrId sets pull/Merge Request ID.
func (b *BadgetizrBuilder) WithPrId(value string) *BadgetizrBuilder {
	b.Builder.WithInput("pr_id", value)
	return b
}

// WithConfiguration sets configuration file path.
func (b *BadgetizrBuilder) WithConfiguration(value string) *BadgetizrBuilder {
	b.Builder.WithInput("configuration", value)
	return b
}

// WithPrDestinationBranch sets pR destination branch.
func (b *BadgetizrBuilder) WithPrDestinationBranch(value string) *BadgetizrBuilder {
	b.Builder.WithInput("pr_destination_branch", value)
	return b
}

// WithPrBuildNumber sets build number.
func (b *BadgetizrBuilder) WithPrBuildNumber(value string) *BadgetizrBuilder {
	b.Builder.WithInput("pr_build_number", value)
	return b
}

// WithPrBuildUrl sets build URL.
func (b *BadgetizrBuilder) WithPrBuildUrl(value string) *BadgetizrBuilder {
	b.Builder.WithInput("pr_build_url", value)
	return b
}

// WithCiStatus sets cI Status.
func (b *BadgetizrBuilder) WithCiStatus(value string) *BadgetizrBuilder {
	b.Builder.WithInput("ci_status", value)
	return b
}

// WithCiText sets cI Badge Text.
func (b *BadgetizrBuilder) WithCiText(value string) *BadgetizrBuilder {
	b.Builder.WithInput("ci_text", value)
	return b
}

// WithProvider sets provider.
func (b *BadgetizrBuilder) WithProvider(value string) *BadgetizrBuilder {
	b.Builder.WithInput("provider", value)
	return b
}

// WithGithubToken sets gitHub Token.
func (b *BadgetizrBuilder) WithGithubToken(value string) *BadgetizrBuilder {
	b.Builder.WithInput("github_token", value)
	return b
}

// WithGitlabToken sets gitLab Token.
func (b *BadgetizrBuilder) WithGitlabToken(value string) *BadgetizrBuilder {
	b.Builder.WithInput("gitlab_token", value)
	return b
}

// WithGitlabHost sets gitLab Host.
func (b *BadgetizrBuilder) WithGitlabHost(value string) *BadgetizrBuilder {
	b.Builder.WithInput("gitlab_host", value)
	return b
}
