// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: dependency-installer (1.0.1)

package step

import "time"

// DependencyInstallerVerbose enumerates the valid values for the verbose input.
type DependencyInstallerVerbose string

const (
	DependencyInstallerVerboseTrue  DependencyInstallerVerbose = "true"
	DependencyInstallerVerboseFalse DependencyInstallerVerbose = "false"
)

// DependencyInstallerBuilder builds a dependency-installer step with typed input methods.
type DependencyInstallerBuilder struct{ *Builder }

// DependencyInstaller creates a dependency-installer step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.DependencyInstaller("1")  // explicit default
//	step.DependencyInstaller("1")                  // older major
func DependencyInstaller(version ...string) *DependencyInstallerBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &DependencyInstallerBuilder{Builder: From("dependency-installer", v)}
}

// WithToolVersionFile sets tool Version File Path.
func (b *DependencyInstallerBuilder) WithToolVersionFile(value string) *DependencyInstallerBuilder {
	b.Builder.WithInput("tool_version_file", value)
	return b
}

// WithVerbose sets verbose Output.
func (b *DependencyInstallerBuilder) WithVerbose(value DependencyInstallerVerbose) *DependencyInstallerBuilder {
	b.Builder.WithInput("verbose", string(value))
	return b
}

// WithBitriseWorkflowId sets bitrise Workflow ID.
func (b *DependencyInstallerBuilder) WithBitriseWorkflowId(value string) *DependencyInstallerBuilder {
	b.Builder.WithInput("bitrise_workflow_id", value)
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *DependencyInstallerBuilder) WithVersion(version string) *DependencyInstallerBuilder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *DependencyInstallerBuilder) WithInput(key, value string) *DependencyInstallerBuilder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *DependencyInstallerBuilder) WithRunIf(expr string) *DependencyInstallerBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *DependencyInstallerBuilder) WithIsAlwaysRun(v bool) *DependencyInstallerBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *DependencyInstallerBuilder) WithIsSkippable(v bool) *DependencyInstallerBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *DependencyInstallerBuilder) WithTitle(title string) *DependencyInstallerBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *DependencyInstallerBuilder) WithTimeout(seconds int) *DependencyInstallerBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *DependencyInstallerBuilder) WithNoOutputTimeout(seconds int) *DependencyInstallerBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *DependencyInstallerBuilder) WithTimeoutDuration(d time.Duration) *DependencyInstallerBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *DependencyInstallerBuilder) WithNoOutputTimeoutDuration(d time.Duration) *DependencyInstallerBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *DependencyInstallerBuilder) WithExecutionContainer(containerID string) *DependencyInstallerBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *DependencyInstallerBuilder) WithServiceContainers(containerIDs ...string) *DependencyInstallerBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
