// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: cache-pull (2.7.2)

package step

import "time"

// CachePullV2IsDebugMode enumerates the valid values for the is_debug_mode input.
type CachePullV2IsDebugMode string

const (
	CachePullV2IsDebugModeTrue  CachePullV2IsDebugMode = "true"
	CachePullV2IsDebugModeFalse CachePullV2IsDebugMode = "false"
)

// CachePullV2ExtractToRelativePath enumerates the valid values for the extract_to_relative_path input.
type CachePullV2ExtractToRelativePath string

const (
	CachePullV2ExtractToRelativePathTrue  CachePullV2ExtractToRelativePath = "true"
	CachePullV2ExtractToRelativePathFalse CachePullV2ExtractToRelativePath = "false"
)

// CachePullV2AllowFallback enumerates the valid values for the allow_fallback input.
type CachePullV2AllowFallback string

const (
	CachePullV2AllowFallbackTrue  CachePullV2AllowFallback = "true"
	CachePullV2AllowFallbackFalse CachePullV2AllowFallback = "false"
)

// CachePullV2IgnoreStackDifference enumerates the valid values for the ignore_stack_difference input.
type CachePullV2IgnoreStackDifference string

const (
	CachePullV2IgnoreStackDifferenceTrue  CachePullV2IgnoreStackDifference = "true"
	CachePullV2IgnoreStackDifferenceFalse CachePullV2IgnoreStackDifference = "false"
)

// CachePullV2Builder builds a cache-pull step with typed input methods.
//
// v1→v2: added `allow_fallback`, `extract_to_relative_path`, `ignore_stack_difference`
//
// Deprecated: The branch-based caching steps are deprecated and being replaced by key-based caching.  Check out our migration guide: [Migrating from branch-based caching to key-based caching](https://devcenter.bitrise.io/en/dependencies-and-caching/branch-based-caching/migrating-from-branch-based-caching-to-key-based-caching.html).
type CachePullV2Builder struct{ *Builder }

// CachePullV2 creates a cache-pull step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.CachePullV2("2")  // explicit default
//	step.CachePullV2("1")                  // older major
//
// v1→v2: added `allow_fallback`, `extract_to_relative_path`, `ignore_stack_difference`
//
// Deprecated: The branch-based caching steps are deprecated and being replaced by key-based caching.  Check out our migration guide: [Migrating from branch-based caching to key-based caching](https://devcenter.bitrise.io/en/dependencies-and-caching/branch-based-caching/migrating-from-branch-based-caching-to-key-based-caching.html).
func CachePullV2(version ...string) *CachePullV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &CachePullV2Builder{Builder: From("cache-pull", v)}
}

// WithWorkdir sets working directory path.
func (b *CachePullV2Builder) WithWorkdir(value string) *CachePullV2Builder {
	b.Builder.WithInput("workdir", value)
	return b
}

// WithCacheApiUrl sets cache API URL.
func (b *CachePullV2Builder) WithCacheApiUrl(value string) *CachePullV2Builder {
	b.Builder.WithInput("cache_api_url", value)
	return b
}

// WithIsDebugMode sets enable verbose logging.
func (b *CachePullV2Builder) WithIsDebugMode(value CachePullV2IsDebugMode) *CachePullV2Builder {
	b.Builder.WithInput("is_debug_mode", string(value))
	return b
}

// WithExtractToRelativePath sets extract to relative path?.
func (b *CachePullV2Builder) WithExtractToRelativePath(value CachePullV2ExtractToRelativePath) *CachePullV2Builder {
	b.Builder.WithInput("extract_to_relative_path", string(value))
	return b
}

// WithAllowFallback sets allow fallback cache extraction?.
func (b *CachePullV2Builder) WithAllowFallback(value CachePullV2AllowFallback) *CachePullV2Builder {
	b.Builder.WithInput("allow_fallback", string(value))
	return b
}

// WithIgnoreStackDifference sets ignore stack difference.
func (b *CachePullV2Builder) WithIgnoreStackDifference(value CachePullV2IgnoreStackDifference) *CachePullV2Builder {
	b.Builder.WithInput("ignore_stack_difference", string(value))
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *CachePullV2Builder) WithRunIf(expr string) *CachePullV2Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *CachePullV2Builder) WithIsAlwaysRun(v bool) *CachePullV2Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *CachePullV2Builder) WithIsSkippable(v bool) *CachePullV2Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *CachePullV2Builder) WithTitle(title string) *CachePullV2Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *CachePullV2Builder) WithTimeout(seconds int) *CachePullV2Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *CachePullV2Builder) WithNoOutputTimeout(seconds int) *CachePullV2Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *CachePullV2Builder) WithTimeoutDuration(d time.Duration) *CachePullV2Builder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *CachePullV2Builder) WithNoOutputTimeoutDuration(d time.Duration) *CachePullV2Builder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *CachePullV2Builder) WithExecutionContainer(containerID string) *CachePullV2Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *CachePullV2Builder) WithServiceContainers(containerIDs ...string) *CachePullV2Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
