// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: git-last-commit-date (1.0.0)

package step

// GitLastCommitDateBuilder builds a git-last-commit-date step with typed input methods.
type GitLastCommitDateBuilder struct{ *Builder }

// GitLastCommitDate creates a git-last-commit-date step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.GitLastCommitDate("1")  // explicit default
//	step.GitLastCommitDate("1")                  // older major
func GitLastCommitDate(version ...string) *GitLastCommitDateBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &GitLastCommitDateBuilder{Builder: From("git-last-commit-date", v)}
}

// gitLastCommitDateOutputs holds the names of environment variables published
// by the git-last-commit-date step (v1) at run time.
type gitLastCommitDateOutputs struct {
	// LastCommitDate is the "Last commit date" output env var.
	LastCommitDate string
	// LastCommitDateNumbers is the "Last commit date numbers" output env var.
	LastCommitDateNumbers string
}

// GitLastCommitDateOutputs provides typed access to the environment variable names
// that git-last-commit-date (v1) exports after a successful run.
var GitLastCommitDateOutputs = gitLastCommitDateOutputs{
	LastCommitDate:        "LAST_COMMIT_DATE",
	LastCommitDateNumbers: "LAST_COMMIT_DATE_NUMBERS",
}
