// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: export-xcarchive-mac (1.2.0)

package step

// ExportXcarchiveMacV1Builder builds a export-xcarchive-mac step with typed input methods.
type ExportXcarchiveMacV1Builder struct{ *Builder }

// ExportXcarchiveMacV1 creates a export-xcarchive-mac step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.ExportXcarchiveMacV1("1")  // explicit default
//	step.ExportXcarchiveMacV1("1")                  // older major
func ExportXcarchiveMacV1(version ...string) *ExportXcarchiveMacV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ExportXcarchiveMacV1Builder{Builder: From("export-xcarchive-mac", v)}
}

// WithArchivePath sets macOS archive path.
func (b *ExportXcarchiveMacV1Builder) WithArchivePath(value string) *ExportXcarchiveMacV1Builder {
	b.Builder.WithInput("archive_path", value)
	return b
}

// WithExportMethod sets select method for export.
func (b *ExportXcarchiveMacV1Builder) WithExportMethod(value string) *ExportXcarchiveMacV1Builder {
	b.Builder.WithInput("export_method", value)
	return b
}

// WithUploadBitcode sets include bitcode.
func (b *ExportXcarchiveMacV1Builder) WithUploadBitcode(value string) *ExportXcarchiveMacV1Builder {
	b.Builder.WithInput("upload_bitcode", value)
	return b
}

// WithCompileBitcode sets rebuild from bitcode.
func (b *ExportXcarchiveMacV1Builder) WithCompileBitcode(value string) *ExportXcarchiveMacV1Builder {
	b.Builder.WithInput("compile_bitcode", value)
	return b
}

// WithTeamId sets the Developer Portal team to use for this export.
func (b *ExportXcarchiveMacV1Builder) WithTeamId(value string) *ExportXcarchiveMacV1Builder {
	b.Builder.WithInput("team_id", value)
	return b
}

// WithCustomExportOptionsPlistContent sets custom export options plist content.
func (b *ExportXcarchiveMacV1Builder) WithCustomExportOptionsPlistContent(value string) *ExportXcarchiveMacV1Builder {
	b.Builder.WithInput("custom_export_options_plist_content", value)
	return b
}

// WithUseLegacyExport sets use legacy export method?.
func (b *ExportXcarchiveMacV1Builder) WithUseLegacyExport(value string) *ExportXcarchiveMacV1Builder {
	b.Builder.WithInput("use_legacy_export", value)
	return b
}

// WithLegacyExportProvisioningProfileName sets specify Provisioning Profile name to use by export.
func (b *ExportXcarchiveMacV1Builder) WithLegacyExportProvisioningProfileName(value string) *ExportXcarchiveMacV1Builder {
	b.Builder.WithInput("legacy_export_provisioning_profile_name", value)
	return b
}

// WithLegacyExportOutputFormat sets specify export format.
func (b *ExportXcarchiveMacV1Builder) WithLegacyExportOutputFormat(value string) *ExportXcarchiveMacV1Builder {
	b.Builder.WithInput("legacy_export_output_format", value)
	return b
}

// WithVerboseLog sets enable verbose logging?.
func (b *ExportXcarchiveMacV1Builder) WithVerboseLog(value string) *ExportXcarchiveMacV1Builder {
	b.Builder.WithInput("verbose_log", value)
	return b
}

// exportXcarchiveMacV1Outputs holds the names of environment variables published
// by the export-xcarchive-mac step (v1) at run time.
type exportXcarchiveMacV1Outputs struct {
	// BitriseAppPath is the "macOS .app path" output env var.
	BitriseAppPath string
	// BitrisePkgPath is the "macOS .pkg path" output env var.
	BitrisePkgPath string
	// BitriseIdedistributionLogsPath is the "`xcdistributionlogs` ZIP path" output env var.
	BitriseIdedistributionLogsPath string
}

// ExportXcarchiveMacV1Outputs provides typed access to the environment variable names
// that export-xcarchive-mac (v1) exports after a successful run.
var ExportXcarchiveMacV1Outputs = exportXcarchiveMacV1Outputs{
	BitriseAppPath:                 "BITRISE_APP_PATH",
	BitrisePkgPath:                 "BITRISE_PKG_PATH",
	BitriseIdedistributionLogsPath: "BITRISE_IDEDISTRIBUTION_LOGS_PATH",
}
