// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: set-ios-version (2.0.0)

package step

// SetIosVersionBuilder is a type alias for SetIosVersionV2Builder,
// always pointing to the latest supported major version.
// To target a specific major version use SetIosVersionV{N}() directly.
type SetIosVersionBuilder = SetIosVersionV2Builder

// SetIosVersion creates a set-ios-version step builder at the latest major version (v2).
// To target a specific major version use SetIosVersionV{N}() directly.
func SetIosVersion(version ...string) *SetIosVersionV2Builder {
	return SetIosVersionV2(version...)
}

// SetIosVersionOutputs provides typed access to the environment variable names
// published by set-ios-version at the latest major version (v2).
// For outputs of a specific major version use SetIosVersionV{N}Outputs directly.
var SetIosVersionOutputs = SetIosVersionV2Outputs
