// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: android-sdk-add-on-installer (0.0.1)

package step

// AndroidSdkAddOnInstallerBuilder builds a android-sdk-add-on-installer step with typed input methods.
type AndroidSdkAddOnInstallerBuilder struct{ *Builder }

// AndroidSdkAddOnInstaller creates a android-sdk-add-on-installer step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.AndroidSdkAddOnInstaller("0")  // explicit default
//	step.AndroidSdkAddOnInstaller("1")                  // older major
func AndroidSdkAddOnInstaller(version ...string) *AndroidSdkAddOnInstallerBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &AndroidSdkAddOnInstallerBuilder{Builder: From("android-sdk-add-on-installer", v)}
}

// WithAndroidSdkPath sets path to the Android SDK folders in the machine.
func (b *AndroidSdkAddOnInstallerBuilder) WithAndroidSdkPath(value string) *AndroidSdkAddOnInstallerBuilder {
	b.Builder.WithInput("android_sdk_path", value)
	return b
}

// WithAddOnUrl sets add-on URL.
func (b *AndroidSdkAddOnInstallerBuilder) WithAddOnUrl(value string) *AndroidSdkAddOnInstallerBuilder {
	b.Builder.WithInput("add_on_url", value)
	return b
}

// WithVerboseLog sets enable verbose logging?.
func (b *AndroidSdkAddOnInstallerBuilder) WithVerboseLog(value string) *AndroidSdkAddOnInstallerBuilder {
	b.Builder.WithInput("verbose_log", value)
	return b
}

// WithValidateChecksum sets validate downloaded file checksum?.
func (b *AndroidSdkAddOnInstallerBuilder) WithValidateChecksum(value string) *AndroidSdkAddOnInstallerBuilder {
	b.Builder.WithInput("validate_checksum", value)
	return b
}
