// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: microsoft-teams-integration (2.1.1)

package step

// MicrosoftTeamsIntegrationBuilder is a type alias for MicrosoftTeamsIntegrationV2Builder,
// always pointing to the latest supported major version.
// To target a specific major version use MicrosoftTeamsIntegrationV{N}() directly.
type MicrosoftTeamsIntegrationBuilder = MicrosoftTeamsIntegrationV2Builder

// MicrosoftTeamsIntegration creates a microsoft-teams-integration step builder at the latest major version (v2).
// To target a specific major version use MicrosoftTeamsIntegrationV{N}() directly.
func MicrosoftTeamsIntegration(version ...string) *MicrosoftTeamsIntegrationV2Builder {
	return MicrosoftTeamsIntegrationV2(version...)
}

// MicrosoftTeamsIntegrationEnableDebug is a type alias for MicrosoftTeamsIntegrationV2EnableDebug,
// pointing to the latest supported major version of the step's enum type.
type MicrosoftTeamsIntegrationEnableDebug = MicrosoftTeamsIntegrationV2EnableDebug

// MicrosoftTeamsIntegrationEnablePrimarySectionMarkdown is a type alias for MicrosoftTeamsIntegrationV2EnablePrimarySectionMarkdown,
// pointing to the latest supported major version of the step's enum type.
type MicrosoftTeamsIntegrationEnablePrimarySectionMarkdown = MicrosoftTeamsIntegrationV2EnablePrimarySectionMarkdown

// MicrosoftTeamsIntegrationEnableBuildStatusFactsMarkdown is a type alias for MicrosoftTeamsIntegrationV2EnableBuildStatusFactsMarkdown,
// pointing to the latest supported major version of the step's enum type.
type MicrosoftTeamsIntegrationEnableBuildStatusFactsMarkdown = MicrosoftTeamsIntegrationV2EnableBuildStatusFactsMarkdown

// MicrosoftTeamsIntegrationEnableDefaultActions is a type alias for MicrosoftTeamsIntegrationV2EnableDefaultActions,
// pointing to the latest supported major version of the step's enum type.
type MicrosoftTeamsIntegrationEnableDefaultActions = MicrosoftTeamsIntegrationV2EnableDefaultActions
