// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xcode-build-for-simulator (0.12.2)

package step

import "time"

// XcodeBuildForSimulatorV0SimulatorPlatform enumerates the valid values for the simulator_platform input.
type XcodeBuildForSimulatorV0SimulatorPlatform string

const (
	XcodeBuildForSimulatorV0SimulatorPlatformIOS  XcodeBuildForSimulatorV0SimulatorPlatform = "iOS"
	XcodeBuildForSimulatorV0SimulatorPlatformTvOS XcodeBuildForSimulatorV0SimulatorPlatform = "tvOS"
)

// XcodeBuildForSimulatorV0DisableIndexWhileBuilding enumerates the valid values for the disable_index_while_building input.
type XcodeBuildForSimulatorV0DisableIndexWhileBuilding string

const (
	XcodeBuildForSimulatorV0DisableIndexWhileBuildingYes XcodeBuildForSimulatorV0DisableIndexWhileBuilding = "yes"
	XcodeBuildForSimulatorV0DisableIndexWhileBuildingNo  XcodeBuildForSimulatorV0DisableIndexWhileBuilding = "no"
)

// XcodeBuildForSimulatorV0CodeSigningAllowed enumerates the valid values for the code_signing_allowed input.
type XcodeBuildForSimulatorV0CodeSigningAllowed string

const (
	XcodeBuildForSimulatorV0CodeSigningAllowedYes XcodeBuildForSimulatorV0CodeSigningAllowed = "yes"
	XcodeBuildForSimulatorV0CodeSigningAllowedNo  XcodeBuildForSimulatorV0CodeSigningAllowed = "no"
)

// XcodeBuildForSimulatorV0CacheLevel enumerates the valid values for the cache_level input.
type XcodeBuildForSimulatorV0CacheLevel string

const (
	XcodeBuildForSimulatorV0CacheLevelNone          XcodeBuildForSimulatorV0CacheLevel = "none"
	XcodeBuildForSimulatorV0CacheLevelSwiftPackages XcodeBuildForSimulatorV0CacheLevel = "swift_packages"
)

// XcodeBuildForSimulatorV0IsCleanBuild enumerates the valid values for the is_clean_build input.
type XcodeBuildForSimulatorV0IsCleanBuild string

const (
	XcodeBuildForSimulatorV0IsCleanBuildYes XcodeBuildForSimulatorV0IsCleanBuild = "yes"
	XcodeBuildForSimulatorV0IsCleanBuildNo  XcodeBuildForSimulatorV0IsCleanBuild = "no"
)

// XcodeBuildForSimulatorV0OutputTool enumerates the valid values for the output_tool input.
type XcodeBuildForSimulatorV0OutputTool string

const (
	XcodeBuildForSimulatorV0OutputToolXcpretty   XcodeBuildForSimulatorV0OutputTool = "xcpretty"
	XcodeBuildForSimulatorV0OutputToolXcodebuild XcodeBuildForSimulatorV0OutputTool = "xcodebuild"
)

// XcodeBuildForSimulatorV0VerboseLog enumerates the valid values for the verbose_log input.
type XcodeBuildForSimulatorV0VerboseLog string

const (
	XcodeBuildForSimulatorV0VerboseLogYes XcodeBuildForSimulatorV0VerboseLog = "yes"
	XcodeBuildForSimulatorV0VerboseLogNo  XcodeBuildForSimulatorV0VerboseLog = "no"
)

// XcodeBuildForSimulatorV0Builder builds a xcode-build-for-simulator step with typed input methods.
type XcodeBuildForSimulatorV0Builder struct{ *Builder }

// XcodeBuildForSimulatorV0 creates a xcode-build-for-simulator step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.XcodeBuildForSimulatorV0("0")  // explicit default
//	step.XcodeBuildForSimulatorV0("1")                  // older major
func XcodeBuildForSimulatorV0(version ...string) *XcodeBuildForSimulatorV0Builder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &XcodeBuildForSimulatorV0Builder{Builder: From("xcode-build-for-simulator", v)}
}

// WithProjectPath sets project path.
func (b *XcodeBuildForSimulatorV0Builder) WithProjectPath(value string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("project_path", value)
	return b
}

// WithScheme sets scheme.
func (b *XcodeBuildForSimulatorV0Builder) WithScheme(value string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("scheme", value)
	return b
}

// WithSimulatorDevice sets device Model.
func (b *XcodeBuildForSimulatorV0Builder) WithSimulatorDevice(value string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("simulator_device", value)
	return b
}

// WithSimulatorOsVersion sets oS Version.
func (b *XcodeBuildForSimulatorV0Builder) WithSimulatorOsVersion(value string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("simulator_os_version", value)
	return b
}

// WithSimulatorPlatform sets platform.
func (b *XcodeBuildForSimulatorV0Builder) WithSimulatorPlatform(value XcodeBuildForSimulatorV0SimulatorPlatform) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("simulator_platform", string(value))
	return b
}

// WithConfiguration sets configuration name.
func (b *XcodeBuildForSimulatorV0Builder) WithConfiguration(value string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("configuration", value)
	return b
}

// WithDisableIndexWhileBuilding sets disable indexing during the build.
func (b *XcodeBuildForSimulatorV0Builder) WithDisableIndexWhileBuilding(value XcodeBuildForSimulatorV0DisableIndexWhileBuilding) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("disable_index_while_building", string(value))
	return b
}

// WithCodeSigningAllowed sets code signing allowed.
func (b *XcodeBuildForSimulatorV0Builder) WithCodeSigningAllowed(value XcodeBuildForSimulatorV0CodeSigningAllowed) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("code_signing_allowed", string(value))
	return b
}

// WithCacheLevel sets enable collecting cache content.
func (b *XcodeBuildForSimulatorV0Builder) WithCacheLevel(value XcodeBuildForSimulatorV0CacheLevel) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("cache_level", string(value))
	return b
}

// WithXcodebuildOptions sets additional options for the xcodebuild command.
func (b *XcodeBuildForSimulatorV0Builder) WithXcodebuildOptions(value string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("xcodebuild_options", value)
	return b
}

// WithWorkdir sets working directory.
func (b *XcodeBuildForSimulatorV0Builder) WithWorkdir(value string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("workdir", value)
	return b
}

// WithOutputDir sets output directory path.
func (b *XcodeBuildForSimulatorV0Builder) WithOutputDir(value string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("output_dir", value)
	return b
}

// WithIsCleanBuild sets do a clean Xcode build before the build?.
func (b *XcodeBuildForSimulatorV0Builder) WithIsCleanBuild(value XcodeBuildForSimulatorV0IsCleanBuild) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("is_clean_build", string(value))
	return b
}

// WithOutputTool sets log formatter.
func (b *XcodeBuildForSimulatorV0Builder) WithOutputTool(value XcodeBuildForSimulatorV0OutputTool) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("output_tool", string(value))
	return b
}

// WithVerboseLog sets enable verbose logging.
func (b *XcodeBuildForSimulatorV0Builder) WithVerboseLog(value XcodeBuildForSimulatorV0VerboseLog) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput("verbose_log", string(value))
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *XcodeBuildForSimulatorV0Builder) WithVersion(version string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *XcodeBuildForSimulatorV0Builder) WithInput(key, value string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *XcodeBuildForSimulatorV0Builder) WithRunIf(expr string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *XcodeBuildForSimulatorV0Builder) WithIsAlwaysRun(v bool) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *XcodeBuildForSimulatorV0Builder) WithIsSkippable(v bool) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *XcodeBuildForSimulatorV0Builder) WithTitle(title string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *XcodeBuildForSimulatorV0Builder) WithTimeout(seconds int) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *XcodeBuildForSimulatorV0Builder) WithNoOutputTimeout(seconds int) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *XcodeBuildForSimulatorV0Builder) WithTimeoutDuration(d time.Duration) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *XcodeBuildForSimulatorV0Builder) WithNoOutputTimeoutDuration(d time.Duration) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *XcodeBuildForSimulatorV0Builder) WithExecutionContainer(containerID string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *XcodeBuildForSimulatorV0Builder) WithServiceContainers(containerIDs ...string) *XcodeBuildForSimulatorV0Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// xcodeBuildForSimulatorV0Outputs holds the names of environment variables published
// by the xcode-build-for-simulator step (v0) at run time.
type xcodeBuildForSimulatorV0Outputs struct {
	// BitriseAppDirPath is the "Generated (and copied) app directory" output env var.
	BitriseAppDirPath string
	// BitriseAppDirPathList is the "List of the generated app paths" output env var.
	BitriseAppDirPathList string
	// BitriseXcodeBuildRawResultTextPath is the "Full raw build output filepath" output env var.
	BitriseXcodeBuildRawResultTextPath string
}

// XcodeBuildForSimulatorV0Outputs provides typed access to the environment variable names
// that xcode-build-for-simulator (v0) exports after a successful run.
var XcodeBuildForSimulatorV0Outputs = xcodeBuildForSimulatorV0Outputs{
	BitriseAppDirPath:                  "BITRISE_APP_DIR_PATH",
	BitriseAppDirPathList:              "BITRISE_APP_DIR_PATH_LIST",
	BitriseXcodeBuildRawResultTextPath: "BITRISE_XCODE_BUILD_RAW_RESULT_TEXT_PATH",
}
