// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: hockeyapp-deploy-android (1.3.3)

package step

// HockeyappDeployAndroidV1Builder builds a hockeyapp-deploy-android step with typed input methods.
type HockeyappDeployAndroidV1Builder struct{ *Builder }

// HockeyappDeployAndroidV1 creates a hockeyapp-deploy-android step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.HockeyappDeployAndroidV1("1")  // explicit default
//	step.HockeyappDeployAndroidV1("1")                  // older major
func HockeyappDeployAndroidV1(version ...string) *HockeyappDeployAndroidV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &HockeyappDeployAndroidV1Builder{Builder: From("hockeyapp-deploy-android", v)}
}

// WithApkPath sets apk file path(s).
func (b *HockeyappDeployAndroidV1Builder) WithApkPath(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("apk_path", value)
	return b
}

// WithMappingPath sets mapping.txt file path.
func (b *HockeyappDeployAndroidV1Builder) WithMappingPath(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("mapping_path", value)
	return b
}

// WithApiToken sets aPI Token.
func (b *HockeyappDeployAndroidV1Builder) WithApiToken(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("api_token", value)
	return b
}

// WithAppId sets hockeyApp: App ID.
func (b *HockeyappDeployAndroidV1Builder) WithAppId(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("app_id", value)
	return b
}

// WithNotes sets notes attached to the deploy.
func (b *HockeyappDeployAndroidV1Builder) WithNotes(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("notes", value)
	return b
}

// WithNotesType sets notes type.
func (b *HockeyappDeployAndroidV1Builder) WithNotesType(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("notes_type", value)
	return b
}

// WithNotify sets notify Testers?.
func (b *HockeyappDeployAndroidV1Builder) WithNotify(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("notify", value)
	return b
}

// WithStatus sets allow Download?.
func (b *HockeyappDeployAndroidV1Builder) WithStatus(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("status", value)
	return b
}

// WithMandatory sets mandatory?.
func (b *HockeyappDeployAndroidV1Builder) WithMandatory(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("mandatory", value)
	return b
}

// WithTags sets (optional) Restrict download: Tags.
func (b *HockeyappDeployAndroidV1Builder) WithTags(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("tags", value)
	return b
}

// WithCommitSha sets (optional) Git commit sha for this build.
func (b *HockeyappDeployAndroidV1Builder) WithCommitSha(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("commit_sha", value)
	return b
}

// WithBuildServerUrl sets (optional) Build job URL (on your build server).
func (b *HockeyappDeployAndroidV1Builder) WithBuildServerUrl(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("build_server_url", value)
	return b
}

// WithRepositoryUrl sets (optional) Source Code Repository URL.
func (b *HockeyappDeployAndroidV1Builder) WithRepositoryUrl(value string) *HockeyappDeployAndroidV1Builder {
	b.Builder.WithInput("repository_url", value)
	return b
}

// hockeyappDeployAndroidV1Outputs holds the names of environment variables published
// by the hockeyapp-deploy-android step (v1) at run time.
type hockeyappDeployAndroidV1Outputs struct {
	// HockeyappDeployStatus is the "Deployment result: 'success' or 'failed'" output env var.
	HockeyappDeployStatus string
	// HockeyappDeployPublicUrl is the "Public URL of the newly deployed version" output env var.
	HockeyappDeployPublicUrl string
	// HockeyappDeployBuildUrl is the "URL of the HockeyApp build" output env var.
	HockeyappDeployBuildUrl string
	// HockeyappDeployConfigUrl is the "URL of the HockeyApp config view" output env var.
	HockeyappDeployConfigUrl string
	// HockeyappDeployPublicUrlList is the "List of Public URLs of the newly deployed version" output env var.
	HockeyappDeployPublicUrlList string
	// HockeyappDeployBuildUrlList is the "List of HockeyApp build URLs" output env var.
	HockeyappDeployBuildUrlList string
	// HockeyappDeployConfigUrlList is the "List of HockeyApp config view URLs" output env var.
	HockeyappDeployConfigUrlList string
}

// HockeyappDeployAndroidV1Outputs provides typed access to the environment variable names
// that hockeyapp-deploy-android (v1) exports after a successful run.
var HockeyappDeployAndroidV1Outputs = hockeyappDeployAndroidV1Outputs{
	HockeyappDeployStatus:        "HOCKEYAPP_DEPLOY_STATUS",
	HockeyappDeployPublicUrl:     "HOCKEYAPP_DEPLOY_PUBLIC_URL",
	HockeyappDeployBuildUrl:      "HOCKEYAPP_DEPLOY_BUILD_URL",
	HockeyappDeployConfigUrl:     "HOCKEYAPP_DEPLOY_CONFIG_URL",
	HockeyappDeployPublicUrlList: "HOCKEYAPP_DEPLOY_PUBLIC_URL_LIST",
	HockeyappDeployBuildUrlList:  "HOCKEYAPP_DEPLOY_BUILD_URL_LIST",
	HockeyappDeployConfigUrlList: "HOCKEYAPP_DEPLOY_CONFIG_URL_LIST",
}
