// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: applivery-android (1.0.1)

package step

import "time"

// AppliveryAndroidV1NotifyCollaborators enumerates the valid values for the notifyCollaborators input.
type AppliveryAndroidV1NotifyCollaborators string

const (
	AppliveryAndroidV1NotifyCollaboratorsTrue  AppliveryAndroidV1NotifyCollaborators = "true"
	AppliveryAndroidV1NotifyCollaboratorsFalse AppliveryAndroidV1NotifyCollaborators = "false"
)

// AppliveryAndroidV1NotifyEmployees enumerates the valid values for the notifyEmployees input.
type AppliveryAndroidV1NotifyEmployees string

const (
	AppliveryAndroidV1NotifyEmployeesTrue  AppliveryAndroidV1NotifyEmployees = "true"
	AppliveryAndroidV1NotifyEmployeesFalse AppliveryAndroidV1NotifyEmployees = "false"
)

// AppliveryAndroidV1Builder builds a applivery-android step with typed input methods.
//
// v0→v1: added `filter`
type AppliveryAndroidV1Builder struct{ *Builder }

// AppliveryAndroidV1 creates a applivery-android step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.AppliveryAndroidV1("1")  // explicit default
//	step.AppliveryAndroidV1("1")                  // older major
//
// v0→v1: added `filter`
func AppliveryAndroidV1(version ...string) *AppliveryAndroidV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &AppliveryAndroidV1Builder{Builder: From("applivery-android", v)}
}

// WithApkPath sets aPK file path.
func (b *AppliveryAndroidV1Builder) WithApkPath(value string) *AppliveryAndroidV1Builder {
	b.Builder.WithInput("apk_path", value)
	return b
}

// WithAabPath sets aAB file path.
func (b *AppliveryAndroidV1Builder) WithAabPath(value string) *AppliveryAndroidV1Builder {
	b.Builder.WithInput("aab_path", value)
	return b
}

// WithAppToken sets app Token.
func (b *AppliveryAndroidV1Builder) WithAppToken(value string) *AppliveryAndroidV1Builder {
	b.Builder.WithInput("appToken", value)
	return b
}

// WithChangelog sets (Optional) Changelog or release notes.
func (b *AppliveryAndroidV1Builder) WithChangelog(value string) *AppliveryAndroidV1Builder {
	b.Builder.WithInput("changelog", value)
	return b
}

// WithNotifyCollaborators sets notify Collaborators?.
func (b *AppliveryAndroidV1Builder) WithNotifyCollaborators(value AppliveryAndroidV1NotifyCollaborators) *AppliveryAndroidV1Builder {
	b.Builder.WithInput("notifyCollaborators", string(value))
	return b
}

// WithNotifyEmployees sets notify Employees?.
func (b *AppliveryAndroidV1Builder) WithNotifyEmployees(value AppliveryAndroidV1NotifyEmployees) *AppliveryAndroidV1Builder {
	b.Builder.WithInput("notifyEmployees", string(value))
	return b
}

// WithNotifyMessage sets (Optional) Notification message.
func (b *AppliveryAndroidV1Builder) WithNotifyMessage(value string) *AppliveryAndroidV1Builder {
	b.Builder.WithInput("notifyMessage", value)
	return b
}

// WithTags sets (Optional) Comma-separated list of tags.
func (b *AppliveryAndroidV1Builder) WithTags(value string) *AppliveryAndroidV1Builder {
	b.Builder.WithInput("tags", value)
	return b
}

// WithVersionName sets (Optional) Human readable version name.
func (b *AppliveryAndroidV1Builder) WithVersionName(value string) *AppliveryAndroidV1Builder {
	b.Builder.WithInput("versionName", value)
	return b
}

// WithFilter sets (Optional) Comma-separated list of groups that will be notified.
func (b *AppliveryAndroidV1Builder) WithFilter(value string) *AppliveryAndroidV1Builder {
	b.Builder.WithInput("filter", value)
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *AppliveryAndroidV1Builder) WithVersion(version string) *AppliveryAndroidV1Builder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *AppliveryAndroidV1Builder) WithInput(key, value string) *AppliveryAndroidV1Builder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *AppliveryAndroidV1Builder) WithRunIf(expr string) *AppliveryAndroidV1Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *AppliveryAndroidV1Builder) WithIsAlwaysRun(v bool) *AppliveryAndroidV1Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *AppliveryAndroidV1Builder) WithIsSkippable(v bool) *AppliveryAndroidV1Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *AppliveryAndroidV1Builder) WithTitle(title string) *AppliveryAndroidV1Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *AppliveryAndroidV1Builder) WithTimeout(seconds int) *AppliveryAndroidV1Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *AppliveryAndroidV1Builder) WithNoOutputTimeout(seconds int) *AppliveryAndroidV1Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *AppliveryAndroidV1Builder) WithTimeoutDuration(d time.Duration) *AppliveryAndroidV1Builder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *AppliveryAndroidV1Builder) WithNoOutputTimeoutDuration(d time.Duration) *AppliveryAndroidV1Builder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *AppliveryAndroidV1Builder) WithExecutionContainer(containerID string) *AppliveryAndroidV1Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *AppliveryAndroidV1Builder) WithServiceContainers(containerIDs ...string) *AppliveryAndroidV1Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// appliveryAndroidV1Outputs holds the names of environment variables published
// by the applivery-android step (v1) at run time.
type appliveryAndroidV1Outputs struct {
	// AppliveryDeployStatus is the "Deployment result: 'success' or 'failed'" output env var.
	AppliveryDeployStatus string
}

// AppliveryAndroidV1Outputs provides typed access to the environment variable names
// that applivery-android (v1) exports after a successful run.
var AppliveryAndroidV1Outputs = appliveryAndroidV1Outputs{
	AppliveryDeployStatus: "APPLIVERY_DEPLOY_STATUS",
}
