// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: github-release-downloader (0.0.3)

package step

// GithubReleaseDownloaderBuilder builds a github-release-downloader step with typed input methods.
type GithubReleaseDownloaderBuilder struct{ *Builder }

// GithubReleaseDownloader creates a github-release-downloader step builder (v0).
func GithubReleaseDownloader(version ...string) *GithubReleaseDownloaderBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &GithubReleaseDownloaderBuilder{Builder: From("github-release-downloader", v)}
}

// WithGithubAccessToken sets gitHub Access Token.
func (b *GithubReleaseDownloaderBuilder) WithGithubAccessToken(value string) *GithubReleaseDownloaderBuilder {
	b.Builder.WithInput("github_access_token", value)
	return b
}

// WithTag sets tag for download.
func (b *GithubReleaseDownloaderBuilder) WithTag(value string) *GithubReleaseDownloaderBuilder {
	b.Builder.WithInput("tag", value)
	return b
}

// WithSource sets download file names.
func (b *GithubReleaseDownloaderBuilder) WithSource(value string) *GithubReleaseDownloaderBuilder {
	b.Builder.WithInput("source", value)
	return b
}

// WithRepositoryUrl sets repository Url that you want to access.
func (b *GithubReleaseDownloaderBuilder) WithRepositoryUrl(value string) *GithubReleaseDownloaderBuilder {
	b.Builder.WithInput("repository_url", value)
	return b
}
