// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: version-pre-release-info (1.0.2)

package step

// VersionPreReleaseInfoBuilder builds a version-pre-release-info step with typed input methods.
type VersionPreReleaseInfoBuilder struct{ *Builder }

// VersionPreReleaseInfo creates a version-pre-release-info step builder (v1).
func VersionPreReleaseInfo() *VersionPreReleaseInfoBuilder {
	return &VersionPreReleaseInfoBuilder{Builder: From("version-pre-release-info", "1")}
}

// WithVersionNumber sets version number.
func (b *VersionPreReleaseInfoBuilder) WithVersionNumber(value string) *VersionPreReleaseInfoBuilder {
	b.Builder.WithInput("version_number", value)
	return b
}

// WithPreReleaseIdentifier sets pre-release identifier.
func (b *VersionPreReleaseInfoBuilder) WithPreReleaseIdentifier(value string) *VersionPreReleaseInfoBuilder {
	b.Builder.WithInput("pre_release_identifier", value)
	return b
}

// WithPreReleaseInitialValue sets pre-release initial value.
func (b *VersionPreReleaseInfoBuilder) WithPreReleaseInitialValue(value string) *VersionPreReleaseInfoBuilder {
	b.Builder.WithInput("pre_release_initial_value", value)
	return b
}

// WithVersionPrefix sets version prefix.
func (b *VersionPreReleaseInfoBuilder) WithVersionPrefix(value string) *VersionPreReleaseInfoBuilder {
	b.Builder.WithInput("version_prefix", value)
	return b
}

// WithPreReleaseIdentifierPrefix sets pre-release identifier prefix.
func (b *VersionPreReleaseInfoBuilder) WithPreReleaseIdentifierPrefix(value string) *VersionPreReleaseInfoBuilder {
	b.Builder.WithInput("pre_release_identifier_prefix", value)
	return b
}

// WithPreReleaseNumberPrefix sets pre-release number prefix.
func (b *VersionPreReleaseInfoBuilder) WithPreReleaseNumberPrefix(value string) *VersionPreReleaseInfoBuilder {
	b.Builder.WithInput("pre_release_number_prefix", value)
	return b
}
