// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: export-xcarchive-mac (1.2.0)

package step

// ExportXcarchiveMacBuilder is a type alias for ExportXcarchiveMacV1Builder,
// always pointing to the latest supported major version.
// To target a specific major version use ExportXcarchiveMacV{N}() directly.
type ExportXcarchiveMacBuilder = ExportXcarchiveMacV1Builder

// ExportXcarchiveMac creates a export-xcarchive-mac step builder at the latest major version (v1).
// To target a specific major version use ExportXcarchiveMacV{N}() directly.
func ExportXcarchiveMac(version ...string) *ExportXcarchiveMacV1Builder {
	return ExportXcarchiveMacV1(version...)
}

// ExportXcarchiveMacOutputs provides typed access to the environment variable names
// published by export-xcarchive-mac at the latest major version (v1).
// For outputs of a specific major version use ExportXcarchiveMacV{N}Outputs directly.
var ExportXcarchiveMacOutputs = ExportXcarchiveMacV1Outputs
