// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: gradle-coveralls (1.0.1)

package step

// GradleCoverallsBuilder builds a gradle-coveralls step with typed input methods.
type GradleCoverallsBuilder struct{ *Builder }

// GradleCoveralls creates a gradle-coveralls step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.GradleCoveralls("1")  // explicit default
//	step.GradleCoveralls("1")                  // older major
func GradleCoveralls(version ...string) *GradleCoverallsBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &GradleCoverallsBuilder{Builder: From("gradle-coveralls", v)}
}

// WithGradlewFilePath sets path for the gradlew file.
func (b *GradleCoverallsBuilder) WithGradlewFilePath(value string) *GradleCoverallsBuilder {
	b.Builder.WithInput("gradlew_file_path", value)
	return b
}

// WithCoverallsTask sets coveralls gradle task.
func (b *GradleCoverallsBuilder) WithCoverallsTask(value string) *GradleCoverallsBuilder {
	b.Builder.WithInput("coveralls_task", value)
	return b
}

// WithCoverallsRepoToken sets coveralls repo token.
func (b *GradleCoverallsBuilder) WithCoverallsRepoToken(value string) *GradleCoverallsBuilder {
	b.Builder.WithInput("coveralls_repo_token", value)
	return b
}
