// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: create-android-emulator (1.1.6)

package step

import "time"

// CreateAndroidEmulatorV1Abi enumerates the valid values for the abi input.
type CreateAndroidEmulatorV1Abi string

const (
	CreateAndroidEmulatorV1AbiArmeabiV7a CreateAndroidEmulatorV1Abi = "armeabi-v7a"
	CreateAndroidEmulatorV1AbiArm64V8a   CreateAndroidEmulatorV1Abi = "arm64-v8a"
	CreateAndroidEmulatorV1AbiX86        CreateAndroidEmulatorV1Abi = "x86"
	CreateAndroidEmulatorV1AbiX8664      CreateAndroidEmulatorV1Abi = "x86_64"
	CreateAndroidEmulatorV1AbiMips       CreateAndroidEmulatorV1Abi = "mips"
)

// CreateAndroidEmulatorV1Tag enumerates the valid values for the tag input.
type CreateAndroidEmulatorV1Tag string

const (
	CreateAndroidEmulatorV1TagDefault             CreateAndroidEmulatorV1Tag = "default"
	CreateAndroidEmulatorV1TagGoogleApis          CreateAndroidEmulatorV1Tag = "google_apis"
	CreateAndroidEmulatorV1TagAndroidTv           CreateAndroidEmulatorV1Tag = "android-tv"
	CreateAndroidEmulatorV1TagAndroidWear         CreateAndroidEmulatorV1Tag = "android-wear"
	CreateAndroidEmulatorV1TagGoogleApisPlaystore CreateAndroidEmulatorV1Tag = "google_apis_playstore"
)

// CreateAndroidEmulatorV1Builder builds a create-android-emulator step with typed input methods.
//
// v0→v1: added `custom_hardware_profile_content`, `options`, `tag`
//
// Deprecated: This step is deprecated, use [AVD Manager](https://github.com/bitrise-steplib/steps-avd-manager) Step instead.
type CreateAndroidEmulatorV1Builder struct{ *Builder }

// CreateAndroidEmulatorV1 creates a create-android-emulator step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.CreateAndroidEmulatorV1("1")  // explicit default
//	step.CreateAndroidEmulatorV1("1")                  // older major
//
// v0→v1: added `custom_hardware_profile_content`, `options`, `tag`
//
// Deprecated: This step is deprecated, use [AVD Manager](https://github.com/bitrise-steplib/steps-avd-manager) Step instead.
func CreateAndroidEmulatorV1(version ...string) *CreateAndroidEmulatorV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &CreateAndroidEmulatorV1Builder{Builder: From("create-android-emulator", v)}
}

// WithName sets name of the new AVD.
func (b *CreateAndroidEmulatorV1Builder) WithName(value string) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithInput("name", value)
	return b
}

// WithPlatform sets target platform of the new AVD.
func (b *CreateAndroidEmulatorV1Builder) WithPlatform(value string) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithInput("platform", value)
	return b
}

// WithAbi sets the ABI to use for the AVD.
func (b *CreateAndroidEmulatorV1Builder) WithAbi(value CreateAndroidEmulatorV1Abi) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithInput("abi", string(value))
	return b
}

// WithTag sets the sys-img tag to use for the AVD.
func (b *CreateAndroidEmulatorV1Builder) WithTag(value CreateAndroidEmulatorV1Tag) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithInput("tag", string(value))
	return b
}

// WithOptions sets additional options for `android create avd` call.
func (b *CreateAndroidEmulatorV1Builder) WithOptions(value string) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithInput("options", value)
	return b
}

// WithCustomHardwareProfileContent sets custom Hardware Profile Content.
func (b *CreateAndroidEmulatorV1Builder) WithCustomHardwareProfileContent(value string) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithInput("custom_hardware_profile_content", value)
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *CreateAndroidEmulatorV1Builder) WithVersion(version string) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *CreateAndroidEmulatorV1Builder) WithInput(key, value string) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *CreateAndroidEmulatorV1Builder) WithRunIf(expr string) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *CreateAndroidEmulatorV1Builder) WithIsAlwaysRun(v bool) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *CreateAndroidEmulatorV1Builder) WithIsSkippable(v bool) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *CreateAndroidEmulatorV1Builder) WithTitle(title string) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *CreateAndroidEmulatorV1Builder) WithTimeout(seconds int) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *CreateAndroidEmulatorV1Builder) WithNoOutputTimeout(seconds int) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *CreateAndroidEmulatorV1Builder) WithTimeoutDuration(d time.Duration) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *CreateAndroidEmulatorV1Builder) WithNoOutputTimeoutDuration(d time.Duration) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *CreateAndroidEmulatorV1Builder) WithExecutionContainer(containerID string) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *CreateAndroidEmulatorV1Builder) WithServiceContainers(containerIDs ...string) *CreateAndroidEmulatorV1Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// createAndroidEmulatorV1Outputs holds the names of environment variables published
// by the create-android-emulator step (v1) at run time.
type createAndroidEmulatorV1Outputs struct {
	// BitriseEmulatorName is the "Name of the new AVD" output env var.
	BitriseEmulatorName string
}

// CreateAndroidEmulatorV1Outputs provides typed access to the environment variable names
// that create-android-emulator (v1) exports after a successful run.
var CreateAndroidEmulatorV1Outputs = createAndroidEmulatorV1Outputs{
	BitriseEmulatorName: "BITRISE_EMULATOR_NAME",
}
