// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: set-ios-bundle-identifier (1.0.2)

package step

import "time"

// SetIosBundleIdentifierBuilder builds a set-ios-bundle-identifier step with typed input methods.
type SetIosBundleIdentifierBuilder struct{ *Builder }

// SetIosBundleIdentifier creates a set-ios-bundle-identifier step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.SetIosBundleIdentifier("1")  // explicit default
//	step.SetIosBundleIdentifier("1")                  // older major
func SetIosBundleIdentifier(version ...string) *SetIosBundleIdentifierBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &SetIosBundleIdentifierBuilder{Builder: From("set-ios-bundle-identifier", v)}
}

// WithInfoPlistFile sets info.plist file path.
func (b *SetIosBundleIdentifierBuilder) WithInfoPlistFile(value string) *SetIosBundleIdentifierBuilder {
	b.Builder.WithInput("info_plist_file", value)
	return b
}

// WithBundleIdentifier sets bundle Identifier to set.
func (b *SetIosBundleIdentifierBuilder) WithBundleIdentifier(value string) *SetIosBundleIdentifierBuilder {
	b.Builder.WithInput("bundle_identifier", value)
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *SetIosBundleIdentifierBuilder) WithVersion(version string) *SetIosBundleIdentifierBuilder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *SetIosBundleIdentifierBuilder) WithInput(key, value string) *SetIosBundleIdentifierBuilder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *SetIosBundleIdentifierBuilder) WithRunIf(expr string) *SetIosBundleIdentifierBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *SetIosBundleIdentifierBuilder) WithIsAlwaysRun(v bool) *SetIosBundleIdentifierBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *SetIosBundleIdentifierBuilder) WithIsSkippable(v bool) *SetIosBundleIdentifierBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *SetIosBundleIdentifierBuilder) WithTitle(title string) *SetIosBundleIdentifierBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *SetIosBundleIdentifierBuilder) WithTimeout(seconds int) *SetIosBundleIdentifierBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *SetIosBundleIdentifierBuilder) WithNoOutputTimeout(seconds int) *SetIosBundleIdentifierBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *SetIosBundleIdentifierBuilder) WithTimeoutDuration(d time.Duration) *SetIosBundleIdentifierBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *SetIosBundleIdentifierBuilder) WithNoOutputTimeoutDuration(d time.Duration) *SetIosBundleIdentifierBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *SetIosBundleIdentifierBuilder) WithExecutionContainer(containerID string) *SetIosBundleIdentifierBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *SetIosBundleIdentifierBuilder) WithServiceContainers(containerIDs ...string) *SetIosBundleIdentifierBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
