// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: genymotion-cloud-saas-stop (0.1.2)

package step

// GenymotionCloudSaasStopBuilder builds a genymotion-cloud-saas-stop step with typed input methods.
type GenymotionCloudSaasStopBuilder struct{ *Builder }

// GenymotionCloudSaasStop creates a genymotion-cloud-saas-stop step builder (v0).
func GenymotionCloudSaasStop() *GenymotionCloudSaasStopBuilder {
	return &GenymotionCloudSaasStopBuilder{Builder: From("genymotion-cloud-saas-stop", "0")}
}

// WithInstanceUuid sets instance UUID.
func (b *GenymotionCloudSaasStopBuilder) WithInstanceUuid(value string) *GenymotionCloudSaasStopBuilder {
	b.Builder.WithInput("instance_uuid", value)
	return b
}
