// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: update-gitops-repository (2.0.5)

package step

// UpdateGitopsRepositoryV2PullRequest enumerates the valid values for the pull_request input.
type UpdateGitopsRepositoryV2PullRequest string

const (
	UpdateGitopsRepositoryV2PullRequestTrue  UpdateGitopsRepositoryV2PullRequest = "true"
	UpdateGitopsRepositoryV2PullRequestFalse UpdateGitopsRepositoryV2PullRequest = "false"
)

// UpdateGitopsRepositoryV2ReplacerMode enumerates the valid values for the replacer_mode input.
type UpdateGitopsRepositoryV2ReplacerMode string

const (
	UpdateGitopsRepositoryV2ReplacerModeTrue  UpdateGitopsRepositoryV2ReplacerMode = "true"
	UpdateGitopsRepositoryV2ReplacerModeFalse UpdateGitopsRepositoryV2ReplacerMode = "false"
)

// UpdateGitopsRepositoryV2Builder builds a update-gitops-repository step with typed input methods.
type UpdateGitopsRepositoryV2Builder struct{ *Builder }

// UpdateGitopsRepositoryV2 creates a update-gitops-repository step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.UpdateGitopsRepositoryV2("2")  // explicit default
//	step.UpdateGitopsRepositoryV2("1")                  // older major
func UpdateGitopsRepositoryV2(version ...string) *UpdateGitopsRepositoryV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &UpdateGitopsRepositoryV2Builder{Builder: From("update-gitops-repository", v)}
}

// WithDeployRepositoryUrl sets github HTTPS URL of the repository to deploy to.
func (b *UpdateGitopsRepositoryV2Builder) WithDeployRepositoryUrl(value string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("deploy_repository_url", value)
	return b
}

// WithDeployPath sets path to place rendered templates inside the repository.
func (b *UpdateGitopsRepositoryV2Builder) WithDeployPath(value string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("deploy_path", value)
	return b
}

// WithDeployToken sets personal Access Token to interact with Github API.
func (b *UpdateGitopsRepositoryV2Builder) WithDeployToken(value string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("deploy_token", value)
	return b
}

// WithDeployUser sets github username associated with the Personal Access Token.
func (b *UpdateGitopsRepositoryV2Builder) WithDeployUser(value string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("deploy_user", value)
	return b
}

// WithDeployBranch sets branch of the repository to deploy to.
func (b *UpdateGitopsRepositoryV2Builder) WithDeployBranch(value string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("deploy_branch", value)
	return b
}

// WithCommitMessage sets commit message of pushed changes.
func (b *UpdateGitopsRepositoryV2Builder) WithCommitMessage(value string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("commit_message", value)
	return b
}

// WithTemplatesFolderPath sets path to Go templates folder.
func (b *UpdateGitopsRepositoryV2Builder) WithTemplatesFolderPath(value string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("templates_folder_path", value)
	return b
}

// WithValues sets input values for the Go template files in YAML format.
func (b *UpdateGitopsRepositoryV2Builder) WithValues(value string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("values", value)
	return b
}

// WithPullRequest sets open a pull request.
func (b *UpdateGitopsRepositoryV2Builder) WithPullRequest(value UpdateGitopsRepositoryV2PullRequest) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("pull_request", string(value))
	return b
}

// WithPullRequestTitle sets title of the opened pull request.
func (b *UpdateGitopsRepositoryV2Builder) WithPullRequestTitle(value string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("pull_request_title", value)
	return b
}

// WithPullRequestBody sets body of the opened pull request.
func (b *UpdateGitopsRepositoryV2Builder) WithPullRequestBody(value string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("pull_request_body", value)
	return b
}

// WithReplacerMode sets key-value matching mode.
func (b *UpdateGitopsRepositoryV2Builder) WithReplacerMode(value UpdateGitopsRepositoryV2ReplacerMode) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("replacer_mode", string(value))
	return b
}

// WithDelimiter sets delimiter.
func (b *UpdateGitopsRepositoryV2Builder) WithDelimiter(value string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("delimiter", value)
	return b
}

// WithFiles sets files.
func (b *UpdateGitopsRepositoryV2Builder) WithFiles(value string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithInput("files", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *UpdateGitopsRepositoryV2Builder) WithRunIf(expr string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *UpdateGitopsRepositoryV2Builder) WithIsAlwaysRun(v bool) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *UpdateGitopsRepositoryV2Builder) WithIsSkippable(v bool) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *UpdateGitopsRepositoryV2Builder) WithTitle(title string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *UpdateGitopsRepositoryV2Builder) WithTimeout(seconds int) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *UpdateGitopsRepositoryV2Builder) WithNoOutputTimeout(seconds int) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *UpdateGitopsRepositoryV2Builder) WithExecutionContainer(containerID string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *UpdateGitopsRepositoryV2Builder) WithServiceContainers(containerIDs ...string) *UpdateGitopsRepositoryV2Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// updateGitopsRepositoryV2Outputs holds the names of environment variables published
// by the update-gitops-repository step (v2) at run time.
type updateGitopsRepositoryV2Outputs struct {
	// PrUrl is the "URL of opened pull request" output env var.
	PrUrl string
}

// UpdateGitopsRepositoryV2Outputs provides typed access to the environment variable names
// that update-gitops-repository (v2) exports after a successful run.
var UpdateGitopsRepositoryV2Outputs = updateGitopsRepositoryV2Outputs{
	PrUrl: "PR_URL",
}
