// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: image-overlayer (1.0.7)

package step

import "time"

// ImageOverlayerCenterIcon enumerates the valid values for the center_icon input.
type ImageOverlayerCenterIcon string

const (
	ImageOverlayerCenterIconTrue  ImageOverlayerCenterIcon = "True"
	ImageOverlayerCenterIconFalse ImageOverlayerCenterIcon = "False"
)

// ImageOverlayerArchiveResult enumerates the valid values for the archive_result input.
type ImageOverlayerArchiveResult string

const (
	ImageOverlayerArchiveResultTrue  ImageOverlayerArchiveResult = "True"
	ImageOverlayerArchiveResultFalse ImageOverlayerArchiveResult = "False"
)

// ImageOverlayerExportResults enumerates the valid values for the export_results input.
type ImageOverlayerExportResults string

const (
	ImageOverlayerExportResultsTrue  ImageOverlayerExportResults = "True"
	ImageOverlayerExportResultsFalse ImageOverlayerExportResults = "False"
)

// ImageOverlayerBuilder builds a image-overlayer step with typed input methods.
type ImageOverlayerBuilder struct{ *Builder }

// ImageOverlayer creates a image-overlayer step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.ImageOverlayer("1")  // explicit default
//	step.ImageOverlayer("1")                  // older major
func ImageOverlayer(version ...string) *ImageOverlayerBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ImageOverlayerBuilder{Builder: From("image-overlayer", v)}
}

// WithSourceImage sets source image or folder path.
func (b *ImageOverlayerBuilder) WithSourceImage(value string) *ImageOverlayerBuilder {
	b.Builder.WithInput("source_image", value)
	return b
}

// WithLeftIcon sets left icon's path.
func (b *ImageOverlayerBuilder) WithLeftIcon(value string) *ImageOverlayerBuilder {
	b.Builder.WithInput("left_icon", value)
	return b
}

// WithRightIcon sets right icon's path.
func (b *ImageOverlayerBuilder) WithRightIcon(value string) *ImageOverlayerBuilder {
	b.Builder.WithInput("right_icon", value)
	return b
}

// WithOutputPath sets output file's path.
func (b *ImageOverlayerBuilder) WithOutputPath(value string) *ImageOverlayerBuilder {
	b.Builder.WithInput("output_path", value)
	return b
}

// WithTextColor sets text color (hexa color).
func (b *ImageOverlayerBuilder) WithTextColor(value string) *ImageOverlayerBuilder {
	b.Builder.WithInput("text_color", value)
	return b
}

// WithCenterIcon sets if you want center the icon in the background image.
func (b *ImageOverlayerBuilder) WithCenterIcon(value ImageOverlayerCenterIcon) *ImageOverlayerBuilder {
	b.Builder.WithInput("center_icon", string(value))
	return b
}

// WithArchiveResult sets if you want archive assets at the end.
func (b *ImageOverlayerBuilder) WithArchiveResult(value ImageOverlayerArchiveResult) *ImageOverlayerBuilder {
	b.Builder.WithInput("archive_result", string(value))
	return b
}

// WithExportResults sets if you want export assets at the end.
func (b *ImageOverlayerBuilder) WithExportResults(value ImageOverlayerExportResults) *ImageOverlayerBuilder {
	b.Builder.WithInput("export_results", string(value))
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *ImageOverlayerBuilder) WithVersion(version string) *ImageOverlayerBuilder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *ImageOverlayerBuilder) WithInput(key, value string) *ImageOverlayerBuilder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *ImageOverlayerBuilder) WithRunIf(expr string) *ImageOverlayerBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *ImageOverlayerBuilder) WithIsAlwaysRun(v bool) *ImageOverlayerBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *ImageOverlayerBuilder) WithIsSkippable(v bool) *ImageOverlayerBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *ImageOverlayerBuilder) WithTitle(title string) *ImageOverlayerBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *ImageOverlayerBuilder) WithTimeout(seconds int) *ImageOverlayerBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *ImageOverlayerBuilder) WithNoOutputTimeout(seconds int) *ImageOverlayerBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *ImageOverlayerBuilder) WithTimeoutDuration(d time.Duration) *ImageOverlayerBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *ImageOverlayerBuilder) WithNoOutputTimeoutDuration(d time.Duration) *ImageOverlayerBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *ImageOverlayerBuilder) WithExecutionContainer(containerID string) *ImageOverlayerBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *ImageOverlayerBuilder) WithServiceContainers(containerIDs ...string) *ImageOverlayerBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
