// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: restore-carthage-cache (3.0.0)

package step

// RestoreCarthageCacheBuilder builds a restore-carthage-cache step with typed input methods.
type RestoreCarthageCacheBuilder struct{ *Builder }

// RestoreCarthageCache creates a restore-carthage-cache step builder (v3).
func RestoreCarthageCache() *RestoreCarthageCacheBuilder {
	return &RestoreCarthageCacheBuilder{Builder: From("restore-carthage-cache", "3")}
}

// WithVerbose sets verbose logging.
func (b *RestoreCarthageCacheBuilder) WithVerbose(value string) *RestoreCarthageCacheBuilder {
	b.Builder.WithInput("verbose", value)
	return b
}

// WithRetries sets number of retries.
func (b *RestoreCarthageCacheBuilder) WithRetries(value string) *RestoreCarthageCacheBuilder {
	b.Builder.WithInput("retries", value)
	return b
}

// WithTimeout sets timeout.
func (b *RestoreCarthageCacheBuilder) WithTimeout(value string) *RestoreCarthageCacheBuilder {
	b.Builder.WithInput("timeout", value)
	return b
}
