// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: android-screenrecord-stop (0.9.0)

package step

// AndroidScreenrecordStopBuilder builds a android-screenrecord-stop step with typed input methods.
//
// Deprecated: This step is deprecated, android emulators no longer support screen recording
type AndroidScreenrecordStopBuilder struct{ *Builder }

// AndroidScreenrecordStop creates a android-screenrecord-stop step builder (v0).
//
// Deprecated: This step is deprecated, android emulators no longer support screen recording
func AndroidScreenrecordStop() *AndroidScreenrecordStopBuilder {
	return &AndroidScreenrecordStopBuilder{Builder: From("android-screenrecord-stop", "0")}
}

// WithRecordId sets record ID.
func (b *AndroidScreenrecordStopBuilder) WithRecordId(value string) *AndroidScreenrecordStopBuilder {
	b.Builder.WithInput("record_id", value)
	return b
}

// WithRemoveFrames sets remove Duplicate Frames.
func (b *AndroidScreenrecordStopBuilder) WithRemoveFrames(value string) *AndroidScreenrecordStopBuilder {
	b.Builder.WithInput("remove_frames", value)
	return b
}

// WithEmulatorSerial sets emulator serial.
func (b *AndroidScreenrecordStopBuilder) WithEmulatorSerial(value string) *AndroidScreenrecordStopBuilder {
	b.Builder.WithInput("emulator_serial", value)
	return b
}
