// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: deploy-react-native-update-to-appzung-codepush (1.0.0)

package step

// DeployReactNativeUpdateToAppzungCodepushBuilder builds a deploy-react-native-update-to-appzung-codepush step with typed input methods.
type DeployReactNativeUpdateToAppzungCodepushBuilder struct{ *Builder }

// DeployReactNativeUpdateToAppzungCodepush creates a deploy-react-native-update-to-appzung-codepush step builder (v1).
func DeployReactNativeUpdateToAppzungCodepush() *DeployReactNativeUpdateToAppzungCodepushBuilder {
	return &DeployReactNativeUpdateToAppzungCodepushBuilder{Builder: From("deploy-react-native-update-to-appzung-codepush", "1")}
}

// WithApiKey sets aPI Key.
func (b *DeployReactNativeUpdateToAppzungCodepushBuilder) WithApiKey(value string) *DeployReactNativeUpdateToAppzungCodepushBuilder {
	b.Builder.WithInput("api_key", value)
	return b
}

// WithReleaseChannel sets release channel.
func (b *DeployReactNativeUpdateToAppzungCodepushBuilder) WithReleaseChannel(value string) *DeployReactNativeUpdateToAppzungCodepushBuilder {
	b.Builder.WithInput("release_channel", value)
	return b
}

// WithMandatory sets mandatory update.
func (b *DeployReactNativeUpdateToAppzungCodepushBuilder) WithMandatory(value string) *DeployReactNativeUpdateToAppzungCodepushBuilder {
	b.Builder.WithInput("mandatory", value)
	return b
}

// WithRollout sets rollout percentage.
func (b *DeployReactNativeUpdateToAppzungCodepushBuilder) WithRollout(value string) *DeployReactNativeUpdateToAppzungCodepushBuilder {
	b.Builder.WithInput("rollout", value)
	return b
}

// WithTargetBinaryVersion sets target binary version.
func (b *DeployReactNativeUpdateToAppzungCodepushBuilder) WithTargetBinaryVersion(value string) *DeployReactNativeUpdateToAppzungCodepushBuilder {
	b.Builder.WithInput("target_binary_version", value)
	return b
}

// WithPrivateKeyPath sets code signing private key path.
func (b *DeployReactNativeUpdateToAppzungCodepushBuilder) WithPrivateKeyPath(value string) *DeployReactNativeUpdateToAppzungCodepushBuilder {
	b.Builder.WithInput("private_key_path", value)
	return b
}

// WithDescriptionFromGit sets use Git Commit Message.
func (b *DeployReactNativeUpdateToAppzungCodepushBuilder) WithDescriptionFromGit(value string) *DeployReactNativeUpdateToAppzungCodepushBuilder {
	b.Builder.WithInput("description_from_git", value)
	return b
}

// WithExtraFlags sets additional Flags.
func (b *DeployReactNativeUpdateToAppzungCodepushBuilder) WithExtraFlags(value string) *DeployReactNativeUpdateToAppzungCodepushBuilder {
	b.Builder.WithInput("extra_flags", value)
	return b
}
