// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: add-trace-sdk-android (0.1.0)

package step

// AddTraceSdkAndroidBuilder builds a add-trace-sdk-android step with typed input methods.
//
// Deprecated: This step is deprecated as it is not supported anymore.
type AddTraceSdkAndroidBuilder struct{ *Builder }

// AddTraceSdkAndroid creates a add-trace-sdk-android step builder (v0).
//
// Deprecated: This step is deprecated as it is not supported anymore.
func AddTraceSdkAndroid(version ...string) *AddTraceSdkAndroidBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &AddTraceSdkAndroidBuilder{Builder: From("add-trace-sdk-android", v)}
}

// WithProjectLocation sets path of the root project.
func (b *AddTraceSdkAndroidBuilder) WithProjectLocation(value string) *AddTraceSdkAndroidBuilder {
	b.Builder.WithInput("project_location", value)
	return b
}

// WithGradleOptions sets gradle Task Options.
func (b *AddTraceSdkAndroidBuilder) WithGradleOptions(value string) *AddTraceSdkAndroidBuilder {
	b.Builder.WithInput("gradle_options", value)
	return b
}
