// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: restore-cocoapods-cache (3.0.0)

package step

// RestoreCocoapodsCacheV3Verbose enumerates the valid values for the verbose input.
type RestoreCocoapodsCacheV3Verbose string

const (
	RestoreCocoapodsCacheV3VerboseTrue  RestoreCocoapodsCacheV3Verbose = "true"
	RestoreCocoapodsCacheV3VerboseFalse RestoreCocoapodsCacheV3Verbose = "false"
)

// RestoreCocoapodsCacheV3Builder builds a restore-cocoapods-cache step with typed input methods.
type RestoreCocoapodsCacheV3Builder struct{ *Builder }

// RestoreCocoapodsCacheV3 creates a restore-cocoapods-cache step builder (v3 by default).
// Pass an explicit major version to override the default:
//
//	step.RestoreCocoapodsCacheV3("3")  // explicit default
//	step.RestoreCocoapodsCacheV3("1")                  // older major
func RestoreCocoapodsCacheV3(version ...string) *RestoreCocoapodsCacheV3Builder {
	v := "3"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &RestoreCocoapodsCacheV3Builder{Builder: From("restore-cocoapods-cache", v)}
}

// WithVerbose sets verbose logging.
func (b *RestoreCocoapodsCacheV3Builder) WithVerbose(value RestoreCocoapodsCacheV3Verbose) *RestoreCocoapodsCacheV3Builder {
	b.Builder.WithInput("verbose", string(value))
	return b
}

// WithRetries sets number of retries.
func (b *RestoreCocoapodsCacheV3Builder) WithRetries(value string) *RestoreCocoapodsCacheV3Builder {
	b.Builder.WithInput("retries", value)
	return b
}

// WithTimeout sets timeout.
func (b *RestoreCocoapodsCacheV3Builder) WithTimeout(value string) *RestoreCocoapodsCacheV3Builder {
	b.Builder.WithInput("timeout", value)
	return b
}

// restoreCocoapodsCacheV3Outputs holds the names of environment variables published
// by the restore-cocoapods-cache step (v3) at run time.
type restoreCocoapodsCacheV3Outputs struct {
	// BitriseCacheHit is the "Cache hit" output env var.
	BitriseCacheHit string
}

// RestoreCocoapodsCacheV3Outputs provides typed access to the environment variable names
// that restore-cocoapods-cache (v3) exports after a successful run.
var RestoreCocoapodsCacheV3Outputs = restoreCocoapodsCacheV3Outputs{
	BitriseCacheHit: "BITRISE_CACHE_HIT",
}
