// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xcode-test (1.18.17)

package step

// XcodeTestV1Builder builds a xcode-test step with typed input methods.
type XcodeTestV1Builder struct{ *Builder }

// XcodeTestV1 creates a xcode-test step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.XcodeTestV1("1")  // explicit default
//	step.XcodeTestV1("1")                  // older major
func XcodeTestV1(version ...string) *XcodeTestV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &XcodeTestV1Builder{Builder: From("xcode-test", v)}
}

// WithProjectPath sets project (or Workspace) path.
func (b *XcodeTestV1Builder) WithProjectPath(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("project_path", value)
	return b
}

// WithScheme sets scheme name.
func (b *XcodeTestV1Builder) WithScheme(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("scheme", value)
	return b
}

// WithSimulatorDevice sets device.
func (b *XcodeTestV1Builder) WithSimulatorDevice(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("simulator_device", value)
	return b
}

// WithSimulatorOsVersion sets oS version.
func (b *XcodeTestV1Builder) WithSimulatorOsVersion(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("simulator_os_version", value)
	return b
}

// WithSimulatorPlatform sets platform.
func (b *XcodeTestV1Builder) WithSimulatorPlatform(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("simulator_platform", value)
	return b
}

// WithExportUitestArtifacts sets export UITest Artifacts.
func (b *XcodeTestV1Builder) WithExportUitestArtifacts(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("export_uitest_artifacts", value)
	return b
}

// WithGenerateCodeCoverageFiles sets generate code coverage files?.
func (b *XcodeTestV1Builder) WithGenerateCodeCoverageFiles(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("generate_code_coverage_files", value)
	return b
}

// WithVerbose sets enable verbose log?.
func (b *XcodeTestV1Builder) WithVerbose(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("verbose", value)
	return b
}

// WithWaitForSimulatorBoot sets (Experimental) Wait to simulator boot?.
func (b *XcodeTestV1Builder) WithWaitForSimulatorBoot(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("wait_for_simulator_boot", value)
	return b
}

// WithWorkdir sets working directory.
func (b *XcodeTestV1Builder) WithWorkdir(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("workdir", value)
	return b
}

// WithIsCleanBuild sets do a clean Xcode build before testing?.
func (b *XcodeTestV1Builder) WithIsCleanBuild(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("is_clean_build", value)
	return b
}

// WithOutputTool sets output tool.
func (b *XcodeTestV1Builder) WithOutputTool(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("output_tool", value)
	return b
}

// WithXcodebuildTestOptions sets additional options for `xcodebuild build test` call.
func (b *XcodeTestV1Builder) WithXcodebuildTestOptions(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("xcodebuild_test_options", value)
	return b
}

// WithSingleBuild sets run xcodebuild test only.
func (b *XcodeTestV1Builder) WithSingleBuild(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("single_build", value)
	return b
}

// WithShouldBuildBeforeTest sets (Experimental) Explicitly perform a build before testing?.
func (b *XcodeTestV1Builder) WithShouldBuildBeforeTest(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("should_build_before_test", value)
	return b
}

// WithShouldRetryTestOnFail sets (Experimental) Rerun test, when it fails?.
func (b *XcodeTestV1Builder) WithShouldRetryTestOnFail(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("should_retry_test_on_fail", value)
	return b
}

// WithXcprettyTestOptions sets additional options for `xcpretty` test call.
func (b *XcodeTestV1Builder) WithXcprettyTestOptions(value string) *XcodeTestV1Builder {
	b.Builder.WithInput("xcpretty_test_options", value)
	return b
}
