// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: data-theorem-mobile-secure (1.2.0)

package step

import "time"

// DataTheoremMobileSecureV1Builder builds a data-theorem-mobile-secure step with typed input methods.
//
// v0→v1: added `dt_upload_api_key`, `sourcemap`; removed `dt_api_upload_key`
type DataTheoremMobileSecureV1Builder struct{ *Builder }

// DataTheoremMobileSecureV1 creates a data-theorem-mobile-secure step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.DataTheoremMobileSecureV1("1")  // explicit default
//	step.DataTheoremMobileSecureV1("1")                  // older major
//
// v0→v1: added `dt_upload_api_key`, `sourcemap`; removed `dt_api_upload_key`
func DataTheoremMobileSecureV1(version ...string) *DataTheoremMobileSecureV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &DataTheoremMobileSecureV1Builder{Builder: From("data-theorem-mobile-secure", v)}
}

// WithFilePath sets file path to the APK or IPA to upload.
func (b *DataTheoremMobileSecureV1Builder) WithFilePath(value string) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithInput("file_path", value)
	return b
}

// WithDtUploadApiKey sets data Theorem Upload API Key.
func (b *DataTheoremMobileSecureV1Builder) WithDtUploadApiKey(value string) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithInput("dt_upload_api_key", value)
	return b
}

// WithSourcemap sets android mapping file.
func (b *DataTheoremMobileSecureV1Builder) WithSourcemap(value string) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithInput("sourcemap", value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *DataTheoremMobileSecureV1Builder) WithRunIf(expr string) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *DataTheoremMobileSecureV1Builder) WithIsAlwaysRun(v bool) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *DataTheoremMobileSecureV1Builder) WithIsSkippable(v bool) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *DataTheoremMobileSecureV1Builder) WithTitle(title string) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *DataTheoremMobileSecureV1Builder) WithTimeout(seconds int) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *DataTheoremMobileSecureV1Builder) WithNoOutputTimeout(seconds int) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *DataTheoremMobileSecureV1Builder) WithTimeoutDuration(d time.Duration) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *DataTheoremMobileSecureV1Builder) WithNoOutputTimeoutDuration(d time.Duration) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *DataTheoremMobileSecureV1Builder) WithExecutionContainer(containerID string) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *DataTheoremMobileSecureV1Builder) WithServiceContainers(containerIDs ...string) *DataTheoremMobileSecureV1Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
