// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: build-router-wait (0.12.4)

package step

// BuildRouterWaitAbortOnFail enumerates the valid values for the abort_on_fail input.
type BuildRouterWaitAbortOnFail string

const (
	BuildRouterWaitAbortOnFailYes BuildRouterWaitAbortOnFail = "yes"
	BuildRouterWaitAbortOnFailNo  BuildRouterWaitAbortOnFail = "no"
)

// BuildRouterWaitVerbose enumerates the valid values for the verbose input.
type BuildRouterWaitVerbose string

const (
	BuildRouterWaitVerboseYes BuildRouterWaitVerbose = "yes"
	BuildRouterWaitVerboseNo  BuildRouterWaitVerbose = "no"
)

// BuildRouterWaitBuilder builds a build-router-wait step with typed input methods.
type BuildRouterWaitBuilder struct{ *Builder }

// BuildRouterWait creates a build-router-wait step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.BuildRouterWait("0")  // explicit default
//	step.BuildRouterWait("1")                  // older major
func BuildRouterWait(version ...string) *BuildRouterWaitBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &BuildRouterWaitBuilder{Builder: From("build-router-wait", v)}
}

// WithAccessToken sets bitrise Access Token.
func (b *BuildRouterWaitBuilder) WithAccessToken(value string) *BuildRouterWaitBuilder {
	b.Builder.WithInput("access_token", value)
	return b
}

// WithBuildslugs sets build slugs.
func (b *BuildRouterWaitBuilder) WithBuildslugs(value string) *BuildRouterWaitBuilder {
	b.Builder.WithInput("buildslugs", value)
	return b
}

// WithBuildArtifactsSavePath sets the path of the build artifacts.
func (b *BuildRouterWaitBuilder) WithBuildArtifactsSavePath(value string) *BuildRouterWaitBuilder {
	b.Builder.WithInput("build_artifacts_save_path", value)
	return b
}

// WithAbortOnFail sets abort all builds if one fails.
func (b *BuildRouterWaitBuilder) WithAbortOnFail(value BuildRouterWaitAbortOnFail) *BuildRouterWaitBuilder {
	b.Builder.WithInput("abort_on_fail", string(value))
	return b
}

// WithVerbose sets enable verbose log?.
func (b *BuildRouterWaitBuilder) WithVerbose(value BuildRouterWaitVerbose) *BuildRouterWaitBuilder {
	b.Builder.WithInput("verbose", string(value))
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *BuildRouterWaitBuilder) WithRunIf(expr string) *BuildRouterWaitBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *BuildRouterWaitBuilder) WithIsAlwaysRun(v bool) *BuildRouterWaitBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *BuildRouterWaitBuilder) WithIsSkippable(v bool) *BuildRouterWaitBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *BuildRouterWaitBuilder) WithTitle(title string) *BuildRouterWaitBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *BuildRouterWaitBuilder) WithTimeout(seconds int) *BuildRouterWaitBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *BuildRouterWaitBuilder) WithNoOutputTimeout(seconds int) *BuildRouterWaitBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *BuildRouterWaitBuilder) WithExecutionContainer(containerID string) *BuildRouterWaitBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *BuildRouterWaitBuilder) WithServiceContainers(containerIDs ...string) *BuildRouterWaitBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
