// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: kotlin-script (1.0.2)

package step

// KotlinScriptBuilder builds a kotlin-script step with typed input methods.
type KotlinScriptBuilder struct{ *Builder }

// KotlinScript creates a kotlin-script step builder (v1).
func KotlinScript() *KotlinScriptBuilder {
	return &KotlinScriptBuilder{Builder: From("kotlin-script", "1")}
}

// WithKotlinContent sets the Kotlin script.
func (b *KotlinScriptBuilder) WithKotlinContent(value string) *KotlinScriptBuilder {
	b.Builder.WithInput("kotlin_content", value)
	return b
}

// WithWorkingDir sets run in directory.
func (b *KotlinScriptBuilder) WithWorkingDir(value string) *KotlinScriptBuilder {
	b.Builder.WithInput("working_dir", value)
	return b
}
