// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: appcenter-apk-upload (0.0.1)

package step

// AppcenterApkUploadBuilder builds a appcenter-apk-upload step with typed input methods.
type AppcenterApkUploadBuilder struct{ *Builder }

// AppcenterApkUpload creates a appcenter-apk-upload step builder (v0).
func AppcenterApkUpload(version ...string) *AppcenterApkUploadBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &AppcenterApkUploadBuilder{Builder: From("appcenter-apk-upload", v)}
}

// WithAppId sets appCenter Release Note.
func (b *AppcenterApkUploadBuilder) WithAppId(value string) *AppcenterApkUploadBuilder {
	b.Builder.WithInput("app_id", value)
	return b
}

// WithApiToken sets appCenter API Token.
func (b *AppcenterApkUploadBuilder) WithApiToken(value string) *AppcenterApkUploadBuilder {
	b.Builder.WithInput("api_token", value)
	return b
}

// WithDistributionGroup sets appCenter Distribution Group Name.
func (b *AppcenterApkUploadBuilder) WithDistributionGroup(value string) *AppcenterApkUploadBuilder {
	b.Builder.WithInput("distribution_group", value)
	return b
}
