// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: android-manifest-info (1.0.2)

package step

// AndroidManifestInfoBuilder builds a android-manifest-info step with typed input methods.
type AndroidManifestInfoBuilder struct{ *Builder }

// AndroidManifestInfo creates a android-manifest-info step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.AndroidManifestInfo("1")  // explicit default
//	step.AndroidManifestInfo("1")                  // older major
func AndroidManifestInfo(version ...string) *AndroidManifestInfoBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &AndroidManifestInfoBuilder{Builder: From("android-manifest-info", v)}
}

// WithManifestFile sets androidManifest.xml file path.
func (b *AndroidManifestInfoBuilder) WithManifestFile(value string) *AndroidManifestInfoBuilder {
	b.Builder.WithInput("manifest_file", value)
	return b
}
