// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: bitrise-step-icon-overlay (2.0.0)

package step

// BitriseStepIconOverlayBuilder is a type alias for BitriseStepIconOverlayV2Builder,
// always pointing to the latest supported major version.
// To target a specific major version use BitriseStepIconOverlayV{N}() directly.
type BitriseStepIconOverlayBuilder = BitriseStepIconOverlayV2Builder

// BitriseStepIconOverlay creates a bitrise-step-icon-overlay step builder at the latest major version (v2).
// To target a specific major version use BitriseStepIconOverlayV{N}() directly.
func BitriseStepIconOverlay(version ...string) *BitriseStepIconOverlayV2Builder {
	return BitriseStepIconOverlayV2(version...)
}
