// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: avd-manager (2.0.2)

package step

// AvdManagerBuilder is a type alias for AvdManagerV2Builder,
// always pointing to the latest supported major version.
// To target a specific major version use AvdManagerV{N}() directly.
type AvdManagerBuilder = AvdManagerV2Builder

// AvdManager creates a avd-manager step builder at the latest major version (v2).
// To target a specific major version use AvdManagerV{N}() directly.
func AvdManager(version ...string) *AvdManagerV2Builder {
	return AvdManagerV2(version...)
}
