// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: comment-on-github-pull-request (0.11.0)

package step

import "time"

// CommentOnGithubPullRequestBuilder builds a comment-on-github-pull-request step with typed input methods.
type CommentOnGithubPullRequestBuilder struct{ *Builder }

// CommentOnGithubPullRequest creates a comment-on-github-pull-request step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.CommentOnGithubPullRequest("0")  // explicit default
//	step.CommentOnGithubPullRequest("1")                  // older major
func CommentOnGithubPullRequest(version ...string) *CommentOnGithubPullRequestBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &CommentOnGithubPullRequestBuilder{Builder: From("comment-on-github-pull-request", v)}
}

// WithPersonalAccessToken sets gitHub personal access token.
func (b *CommentOnGithubPullRequestBuilder) WithPersonalAccessToken(value string) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithInput("personal_access_token", value)
	return b
}

// WithBody sets body.
func (b *CommentOnGithubPullRequestBuilder) WithBody(value string) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithInput("body", value)
	return b
}

// WithRepositoryUrl sets repository URL.
func (b *CommentOnGithubPullRequestBuilder) WithRepositoryUrl(value string) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithInput("repository_url", value)
	return b
}

// WithIssueNumber sets gitHub PullRequest or Issue number.
func (b *CommentOnGithubPullRequestBuilder) WithIssueNumber(value string) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithInput("issue_number", value)
	return b
}

// WithApiBaseUrl sets gitHub API Base URL.
func (b *CommentOnGithubPullRequestBuilder) WithApiBaseUrl(value string) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithInput("api_base_url", value)
	return b
}

// WithUpdateCommentTag sets update comment tag.
func (b *CommentOnGithubPullRequestBuilder) WithUpdateCommentTag(value string) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithInput("update_comment_tag", value)
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *CommentOnGithubPullRequestBuilder) WithVersion(version string) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *CommentOnGithubPullRequestBuilder) WithInput(key, value string) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *CommentOnGithubPullRequestBuilder) WithRunIf(expr string) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *CommentOnGithubPullRequestBuilder) WithIsAlwaysRun(v bool) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *CommentOnGithubPullRequestBuilder) WithIsSkippable(v bool) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *CommentOnGithubPullRequestBuilder) WithTitle(title string) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *CommentOnGithubPullRequestBuilder) WithTimeout(seconds int) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *CommentOnGithubPullRequestBuilder) WithNoOutputTimeout(seconds int) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *CommentOnGithubPullRequestBuilder) WithTimeoutDuration(d time.Duration) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *CommentOnGithubPullRequestBuilder) WithNoOutputTimeoutDuration(d time.Duration) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *CommentOnGithubPullRequestBuilder) WithExecutionContainer(containerID string) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *CommentOnGithubPullRequestBuilder) WithServiceContainers(containerIDs ...string) *CommentOnGithubPullRequestBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
