// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: zscan-upload-plugin (1.0.3)

package step

// ZscanUploadPluginBuilder builds a zscan-upload-plugin step with typed input methods.
type ZscanUploadPluginBuilder struct{ *Builder }

// ZscanUploadPlugin creates a zscan-upload-plugin step builder (v1).
func ZscanUploadPlugin(version ...string) *ZscanUploadPluginBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ZscanUploadPluginBuilder{Builder: From("zscan-upload-plugin", v)}
}

// WithEndpoint sets endpoint.
func (b *ZscanUploadPluginBuilder) WithEndpoint(value string) *ZscanUploadPluginBuilder {
	b.Builder.WithInput("endpoint", value)
	return b
}

// WithClientId sets client ID.
func (b *ZscanUploadPluginBuilder) WithClientId(value string) *ZscanUploadPluginBuilder {
	b.Builder.WithInput("client_id", value)
	return b
}

// WithClientSecret sets client Secret.
func (b *ZscanUploadPluginBuilder) WithClientSecret(value string) *ZscanUploadPluginBuilder {
	b.Builder.WithInput("client_secret", value)
	return b
}

// WithFilePath sets file Path.
func (b *ZscanUploadPluginBuilder) WithFilePath(value string) *ZscanUploadPluginBuilder {
	b.Builder.WithInput("file_path", value)
	return b
}

// WithWaitForReport sets wait for Report.
func (b *ZscanUploadPluginBuilder) WithWaitForReport(value string) *ZscanUploadPluginBuilder {
	b.Builder.WithInput("wait_for_report", value)
	return b
}

// WithReportFormat sets report Format.
func (b *ZscanUploadPluginBuilder) WithReportFormat(value string) *ZscanUploadPluginBuilder {
	b.Builder.WithInput("report_format", value)
	return b
}

// WithTeamName sets team Name.
func (b *ZscanUploadPluginBuilder) WithTeamName(value string) *ZscanUploadPluginBuilder {
	b.Builder.WithInput("team_name", value)
	return b
}
