// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: firebase-dsym-upload (2.0.1)

package step

// FirebaseDsymUploadBuilder builds a firebase-dsym-upload step with typed input methods.
type FirebaseDsymUploadBuilder struct{ *Builder }

// FirebaseDsymUpload creates a firebase-dsym-upload step builder (v2).
func FirebaseDsymUpload(version ...string) *FirebaseDsymUploadBuilder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &FirebaseDsymUploadBuilder{Builder: From("firebase-dsym-upload", v)}
}

// WithFduFabricLocation sets location of FirebaseCrashlytics.
func (b *FirebaseDsymUploadBuilder) WithFduFabricLocation(value string) *FirebaseDsymUploadBuilder {
	b.Builder.WithInput("fdu_fabric_location", value)
	return b
}

// WithFduGoogleServicesLocation sets location of your GoogleService-Info.plist.
func (b *FirebaseDsymUploadBuilder) WithFduGoogleServicesLocation(value string) *FirebaseDsymUploadBuilder {
	b.Builder.WithInput("fdu_google_services_location", value)
	return b
}

// WithFduDsymLocation sets location of the bitrise dSYMs.
func (b *FirebaseDsymUploadBuilder) WithFduDsymLocation(value string) *FirebaseDsymUploadBuilder {
	b.Builder.WithInput("fdu_dsym_location", value)
	return b
}

// WithFduLogging sets show additional logging.
func (b *FirebaseDsymUploadBuilder) WithFduLogging(value string) *FirebaseDsymUploadBuilder {
	b.Builder.WithInput("fdu_logging", value)
	return b
}
