// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: avd-manager (0.9.2)

package step

import "time"

// AvdManagerV0Profile enumerates the valid values for the profile input.
type AvdManagerV0Profile string

const (
	AvdManagerV0ProfileTv1080p              AvdManagerV0Profile = "tv_1080p"
	AvdManagerV0ProfileTv720p               AvdManagerV0Profile = "tv_720p"
	AvdManagerV0ProfileWearRound            AvdManagerV0Profile = "wear_round"
	AvdManagerV0ProfileWearRoundChin320290  AvdManagerV0Profile = "wear_round_chin_320_290"
	AvdManagerV0ProfileWearSquare           AvdManagerV0Profile = "wear_square"
	AvdManagerV0ProfileGalaxyNexus          AvdManagerV0Profile = "Galaxy Nexus"
	AvdManagerV0ProfileNexus10              AvdManagerV0Profile = "Nexus 10"
	AvdManagerV0ProfileNexus4               AvdManagerV0Profile = "Nexus 4"
	AvdManagerV0ProfileNexus5               AvdManagerV0Profile = "Nexus 5"
	AvdManagerV0ProfileNexus5X              AvdManagerV0Profile = "Nexus 5X"
	AvdManagerV0ProfileNexus6               AvdManagerV0Profile = "Nexus 6"
	AvdManagerV0ProfileNexus6P              AvdManagerV0Profile = "Nexus 6P"
	AvdManagerV0ProfileNexus72013           AvdManagerV0Profile = "Nexus 7 2013"
	AvdManagerV0ProfileNexus7               AvdManagerV0Profile = "Nexus 7"
	AvdManagerV0ProfileNexus9               AvdManagerV0Profile = "Nexus 9"
	AvdManagerV0ProfileNexusOne             AvdManagerV0Profile = "Nexus One"
	AvdManagerV0ProfileNexusS               AvdManagerV0Profile = "Nexus S"
	AvdManagerV0ProfilePixel                AvdManagerV0Profile = "pixel"
	AvdManagerV0ProfilePixelC               AvdManagerV0Profile = "pixel_c"
	AvdManagerV0ProfilePixelXl              AvdManagerV0Profile = "pixel_xl"
	AvdManagerV0Profile27inQVGA             AvdManagerV0Profile = "2.7in QVGA"
	AvdManagerV0Profile27inQVGASlider       AvdManagerV0Profile = "2.7in QVGA slider"
	AvdManagerV0Profile32inHVGASliderADP1   AvdManagerV0Profile = "3.2in HVGA slider (ADP1)"
	AvdManagerV0Profile32inQVGAADP2         AvdManagerV0Profile = "3.2in QVGA (ADP2)"
	AvdManagerV0Profile33inWQVGA            AvdManagerV0Profile = "3.3in WQVGA"
	AvdManagerV0Profile34inWQVGA            AvdManagerV0Profile = "3.4in WQVGA"
	AvdManagerV0Profile37FWVGASlider        AvdManagerV0Profile = "3.7 FWVGA slider"
	AvdManagerV0Profile37inWVGANexusOne     AvdManagerV0Profile = "3.7in WVGA (Nexus One)"
	AvdManagerV0Profile4inWVGANexusS        AvdManagerV0Profile = "4in WVGA (Nexus S)"
	AvdManagerV0Profile465in720pGalaxyNexus AvdManagerV0Profile = "4.65in 720p (Galaxy Nexus)"
	AvdManagerV0Profile47inWXGA             AvdManagerV0Profile = "4.7in WXGA"
	AvdManagerV0Profile51inWVGA             AvdManagerV0Profile = "5.1in WVGA"
	AvdManagerV0Profile54inFWVGA            AvdManagerV0Profile = "5.4in FWVGA"
	AvdManagerV0Profile7inWSVGATablet       AvdManagerV0Profile = "7in WSVGA (Tablet)"
	AvdManagerV0Profile101inWXGATablet      AvdManagerV0Profile = "10.1in WXGA (Tablet)"
)

// AvdManagerV0Tag enumerates the valid values for the tag input.
type AvdManagerV0Tag string

const (
	AvdManagerV0TagGoogleApis          AvdManagerV0Tag = "google_apis"
	AvdManagerV0TagGoogleApisPlaystore AvdManagerV0Tag = "google_apis_playstore"
	AvdManagerV0TagAndroidWear         AvdManagerV0Tag = "android-wear"
	AvdManagerV0TagAndroidTv           AvdManagerV0Tag = "android-tv"
	AvdManagerV0TagDefault             AvdManagerV0Tag = "default"
)

// AvdManagerV0VerboseMode enumerates the valid values for the verbose_mode input.
type AvdManagerV0VerboseMode string

const (
	AvdManagerV0VerboseModeTrue  AvdManagerV0VerboseMode = "true"
	AvdManagerV0VerboseModeFalse AvdManagerV0VerboseMode = "false"
)

// AvdManagerV0Orientation enumerates the valid values for the orientation input.
type AvdManagerV0Orientation string

const (
	AvdManagerV0OrientationPortrait  AvdManagerV0Orientation = "portrait"
	AvdManagerV0OrientationLandscape AvdManagerV0Orientation = "landscape"
)

// AvdManagerV0Overwrite enumerates the valid values for the overwrite input.
type AvdManagerV0Overwrite string

const (
	AvdManagerV0OverwriteTrue  AvdManagerV0Overwrite = "true"
	AvdManagerV0OverwriteFalse AvdManagerV0Overwrite = "false"
)

// AvdManagerV0EmulatorAbi enumerates the valid values for the emulator_abi input.
type AvdManagerV0EmulatorAbi string

const (
	AvdManagerV0EmulatorAbiX86        AvdManagerV0EmulatorAbi = "x86"
	AvdManagerV0EmulatorAbiArmeabiV7a AvdManagerV0EmulatorAbi = "armeabi-v7a"
	AvdManagerV0EmulatorAbiArm64V8a   AvdManagerV0EmulatorAbi = "arm64-v8a"
	AvdManagerV0EmulatorAbiX8664      AvdManagerV0EmulatorAbi = "x86_64"
	AvdManagerV0EmulatorAbiMips       AvdManagerV0EmulatorAbi = "mips"
)

// AvdManagerV0Builder builds a avd-manager step with typed input methods.
type AvdManagerV0Builder struct{ *Builder }

// AvdManagerV0 creates a avd-manager step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.AvdManagerV0("0")  // explicit default
//	step.AvdManagerV0("1")                  // older major
func AvdManagerV0(version ...string) *AvdManagerV0Builder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &AvdManagerV0Builder{Builder: From("avd-manager", v)}
}

// WithProfile sets device Profile.
func (b *AvdManagerV0Builder) WithProfile(value AvdManagerV0Profile) *AvdManagerV0Builder {
	b.Builder.WithInput("profile", string(value))
	return b
}

// WithVersion sets android API Level.
func (b *AvdManagerV0Builder) WithVersion(value string) *AvdManagerV0Builder {
	b.Builder.WithInput("version", value)
	return b
}

// WithTag sets oS Tag.
func (b *AvdManagerV0Builder) WithTag(value AvdManagerV0Tag) *AvdManagerV0Builder {
	b.Builder.WithInput("tag", string(value))
	return b
}

// WithVerboseMode sets verbose Mode.
func (b *AvdManagerV0Builder) WithVerboseMode(value AvdManagerV0VerboseMode) *AvdManagerV0Builder {
	b.Builder.WithInput("verbose_mode", string(value))
	return b
}

// WithOrientation sets orientation.
func (b *AvdManagerV0Builder) WithOrientation(value AvdManagerV0Orientation) *AvdManagerV0Builder {
	b.Builder.WithInput("orientation", string(value))
	return b
}

// WithResolution sets resolution.
func (b *AvdManagerV0Builder) WithResolution(value string) *AvdManagerV0Builder {
	b.Builder.WithInput("resolution", value)
	return b
}

// WithDensity sets density.
func (b *AvdManagerV0Builder) WithDensity(value string) *AvdManagerV0Builder {
	b.Builder.WithInput("density", value)
	return b
}

// WithEmulatorId sets iD.
func (b *AvdManagerV0Builder) WithEmulatorId(value string) *AvdManagerV0Builder {
	b.Builder.WithInput("emulator_id", value)
	return b
}

// WithCustomHwConfig sets custom hardware config.
func (b *AvdManagerV0Builder) WithCustomHwConfig(value string) *AvdManagerV0Builder {
	b.Builder.WithInput("custom_hw_config", value)
	return b
}

// WithOverwrite sets overwrite.
func (b *AvdManagerV0Builder) WithOverwrite(value AvdManagerV0Overwrite) *AvdManagerV0Builder {
	b.Builder.WithInput("overwrite", string(value))
	return b
}

// WithCustomCommandFlags sets start AVD command flags.
func (b *AvdManagerV0Builder) WithCustomCommandFlags(value string) *AvdManagerV0Builder {
	b.Builder.WithInput("custom_command_flags", value)
	return b
}

// WithEmulatorAbi sets emulator ABI.
func (b *AvdManagerV0Builder) WithEmulatorAbi(value AvdManagerV0EmulatorAbi) *AvdManagerV0Builder {
	b.Builder.WithInput("emulator_abi", string(value))
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *AvdManagerV0Builder) WithInput(key, value string) *AvdManagerV0Builder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *AvdManagerV0Builder) WithRunIf(expr string) *AvdManagerV0Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *AvdManagerV0Builder) WithIsAlwaysRun(v bool) *AvdManagerV0Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *AvdManagerV0Builder) WithIsSkippable(v bool) *AvdManagerV0Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *AvdManagerV0Builder) WithTitle(title string) *AvdManagerV0Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *AvdManagerV0Builder) WithTimeout(seconds int) *AvdManagerV0Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *AvdManagerV0Builder) WithNoOutputTimeout(seconds int) *AvdManagerV0Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *AvdManagerV0Builder) WithTimeoutDuration(d time.Duration) *AvdManagerV0Builder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *AvdManagerV0Builder) WithNoOutputTimeoutDuration(d time.Duration) *AvdManagerV0Builder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *AvdManagerV0Builder) WithExecutionContainer(containerID string) *AvdManagerV0Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *AvdManagerV0Builder) WithServiceContainers(containerIDs ...string) *AvdManagerV0Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// avdManagerV0Outputs holds the names of environment variables published
// by the avd-manager step (v0) at run time.
type avdManagerV0Outputs struct {
	// BitriseEmulatorSerial is the "Emulator serial" output env var.
	BitriseEmulatorSerial string
}

// AvdManagerV0Outputs provides typed access to the environment variable names
// that avd-manager (v0) exports after a successful run.
var AvdManagerV0Outputs = avdManagerV0Outputs{
	BitriseEmulatorSerial: "BITRISE_EMULATOR_SERIAL",
}
