// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: cordova-config (0.0.3)

package step

// CordovaConfigBuilder builds a cordova-config step with typed input methods.
type CordovaConfigBuilder struct{ *Builder }

// CordovaConfig creates a cordova-config step builder (v0).
func CordovaConfig(version ...string) *CordovaConfigBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &CordovaConfigBuilder{Builder: From("cordova-config", v)}
}

// WithName sets cordova application name.
func (b *CordovaConfigBuilder) WithName(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("name", value)
	return b
}

// WithId sets cordova ID.
func (b *CordovaConfigBuilder) WithId(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("id", value)
	return b
}

// WithAndroidVersionCode sets android version code.
func (b *CordovaConfigBuilder) WithAndroidVersionCode(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("android_version_code", value)
	return b
}

// WithAndroidPackageName sets android package name.
func (b *CordovaConfigBuilder) WithAndroidPackageName(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("android_package_name", value)
	return b
}

// WithIosBundleVersion sets iOS bundle version.
func (b *CordovaConfigBuilder) WithIosBundleVersion(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("ios_bundle_version", value)
	return b
}

// WithIosBundleIdentifier sets iOS bundle identifier.
func (b *CordovaConfigBuilder) WithIosBundleIdentifier(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("ios_bundle_identifier", value)
	return b
}

// WithConfigPath sets cordova config.xml file location.
func (b *CordovaConfigBuilder) WithConfigPath(value string) *CordovaConfigBuilder {
	b.Builder.WithInput("config_path", value)
	return b
}
