// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: change-value (2.0.0)

package step

import "time"

// ChangeValueV2ShowFile enumerates the valid values for the show_file input.
type ChangeValueV2ShowFile string

const (
	ChangeValueV2ShowFileTrue  ChangeValueV2ShowFile = "true"
	ChangeValueV2ShowFileFalse ChangeValueV2ShowFile = "false"
)

// ChangeValueV2NotfoundExit enumerates the valid values for the notfound_exit input.
type ChangeValueV2NotfoundExit string

const (
	ChangeValueV2NotfoundExitTrue  ChangeValueV2NotfoundExit = "true"
	ChangeValueV2NotfoundExitFalse ChangeValueV2NotfoundExit = "false"
)

// ChangeValueV2Builder builds a change-value step with typed input methods.
type ChangeValueV2Builder struct{ *Builder }

// ChangeValueV2 creates a change-value step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.ChangeValueV2("2")  // explicit default
//	step.ChangeValueV2("1")                  // older major
func ChangeValueV2(version ...string) *ChangeValueV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ChangeValueV2Builder{Builder: From("change-value", v)}
}

// WithFile sets file path.
func (b *ChangeValueV2Builder) WithFile(value string) *ChangeValueV2Builder {
	b.Builder.WithInput("file", value)
	return b
}

// WithOldValue sets current value.
func (b *ChangeValueV2Builder) WithOldValue(value string) *ChangeValueV2Builder {
	b.Builder.WithInput("old_value", value)
	return b
}

// WithNewValue sets new value.
func (b *ChangeValueV2Builder) WithNewValue(value string) *ChangeValueV2Builder {
	b.Builder.WithInput("new_value", value)
	return b
}

// WithShowFile sets print file content before and after the value change.
func (b *ChangeValueV2Builder) WithShowFile(value ChangeValueV2ShowFile) *ChangeValueV2Builder {
	b.Builder.WithInput("show_file", string(value))
	return b
}

// WithNotfoundExit sets mark the Step as "Failed" if the selected value isn't found.
func (b *ChangeValueV2Builder) WithNotfoundExit(value ChangeValueV2NotfoundExit) *ChangeValueV2Builder {
	b.Builder.WithInput("notfound_exit", string(value))
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *ChangeValueV2Builder) WithVersion(version string) *ChangeValueV2Builder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *ChangeValueV2Builder) WithInput(key, value string) *ChangeValueV2Builder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *ChangeValueV2Builder) WithRunIf(expr string) *ChangeValueV2Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *ChangeValueV2Builder) WithIsAlwaysRun(v bool) *ChangeValueV2Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *ChangeValueV2Builder) WithIsSkippable(v bool) *ChangeValueV2Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *ChangeValueV2Builder) WithTitle(title string) *ChangeValueV2Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *ChangeValueV2Builder) WithTimeout(seconds int) *ChangeValueV2Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *ChangeValueV2Builder) WithNoOutputTimeout(seconds int) *ChangeValueV2Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *ChangeValueV2Builder) WithTimeoutDuration(d time.Duration) *ChangeValueV2Builder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *ChangeValueV2Builder) WithNoOutputTimeoutDuration(d time.Duration) *ChangeValueV2Builder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *ChangeValueV2Builder) WithExecutionContainer(containerID string) *ChangeValueV2Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *ChangeValueV2Builder) WithServiceContainers(containerIDs ...string) *ChangeValueV2Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
