// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: script (1.2.1)

package step

// ScriptBuilder builds a script step with typed input methods.
type ScriptBuilder struct{ *Builder }

// Script creates a script step builder (v1).
func Script(version ...string) *ScriptBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ScriptBuilder{Builder: From("script", v)}
}

// WithContent sets script content.
func (b *ScriptBuilder) WithContent(value string) *ScriptBuilder {
	b.Builder.WithInput("content", value)
	return b
}

// WithRunnerBin sets execute with / runner binary.
func (b *ScriptBuilder) WithRunnerBin(value string) *ScriptBuilder {
	b.Builder.WithInput("runner_bin", value)
	return b
}

// WithWorkingDir sets working directory.
func (b *ScriptBuilder) WithWorkingDir(value string) *ScriptBuilder {
	b.Builder.WithInput("working_dir", value)
	return b
}

// WithScriptFilePath sets script file path.
func (b *ScriptBuilder) WithScriptFilePath(value string) *ScriptBuilder {
	b.Builder.WithInput("script_file_path", value)
	return b
}

// WithIsDebug sets debug print?.
func (b *ScriptBuilder) WithIsDebug(value string) *ScriptBuilder {
	b.Builder.WithInput("is_debug", value)
	return b
}
