// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xamarin-test-cloud-for-ios (2.4.0)

package step

// XamarinTestCloudForIosV2Builder builds a xamarin-test-cloud-for-ios step with typed input methods.
//
// Deprecated: This step is deprecated, please use [App Center upload and schedule tests](https://github.com/bitrise-steplib/steps-appcenter-test) Step instead.
type XamarinTestCloudForIosV2Builder struct{ *Builder }

// XamarinTestCloudForIosV2 creates a xamarin-test-cloud-for-ios step builder (v2 by default).
// Pass an explicit major version to override the default:
//
//	step.XamarinTestCloudForIosV2("2")  // explicit default
//	step.XamarinTestCloudForIosV2("1")                  // older major
//
// Deprecated: This step is deprecated, please use [App Center upload and schedule tests](https://github.com/bitrise-steplib/steps-appcenter-test) Step instead.
func XamarinTestCloudForIosV2(version ...string) *XamarinTestCloudForIosV2Builder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &XamarinTestCloudForIosV2Builder{Builder: From("xamarin-test-cloud-for-ios", v)}
}

// WithXamarinUser sets user email.
func (b *XamarinTestCloudForIosV2Builder) WithXamarinUser(value string) *XamarinTestCloudForIosV2Builder {
	b.Builder.WithInput("xamarin_user", value)
	return b
}

// WithTestCloudApiKey sets api key.
func (b *XamarinTestCloudForIosV2Builder) WithTestCloudApiKey(value string) *XamarinTestCloudForIosV2Builder {
	b.Builder.WithInput("test_cloud_api_key", value)
	return b
}

// WithTestCloudDevices sets device selection id.
func (b *XamarinTestCloudForIosV2Builder) WithTestCloudDevices(value string) *XamarinTestCloudForIosV2Builder {
	b.Builder.WithInput("test_cloud_devices", value)
	return b
}

// WithTestCloudSeries sets test series.
func (b *XamarinTestCloudForIosV2Builder) WithTestCloudSeries(value string) *XamarinTestCloudForIosV2Builder {
	b.Builder.WithInput("test_cloud_series", value)
	return b
}

// WithXamarinProject sets path to Xamarin Solution.
func (b *XamarinTestCloudForIosV2Builder) WithXamarinProject(value string) *XamarinTestCloudForIosV2Builder {
	b.Builder.WithInput("xamarin_project", value)
	return b
}

// WithXamarinConfiguration sets xamarin project configuration.
func (b *XamarinTestCloudForIosV2Builder) WithXamarinConfiguration(value string) *XamarinTestCloudForIosV2Builder {
	b.Builder.WithInput("xamarin_configuration", value)
	return b
}

// WithXamarinPlatform sets xamarin platform.
func (b *XamarinTestCloudForIosV2Builder) WithXamarinPlatform(value string) *XamarinTestCloudForIosV2Builder {
	b.Builder.WithInput("xamarin_platform", value)
	return b
}

// WithTestCloudIsAsync sets don't wait for cloud test run to complete.
func (b *XamarinTestCloudForIosV2Builder) WithTestCloudIsAsync(value string) *XamarinTestCloudForIosV2Builder {
	b.Builder.WithInput("test_cloud_is_async", value)
	return b
}

// WithTestCloudParallelization sets run tests in parallel by method/fixture.
func (b *XamarinTestCloudForIosV2Builder) WithTestCloudParallelization(value string) *XamarinTestCloudForIosV2Builder {
	b.Builder.WithInput("test_cloud_parallelization", value)
	return b
}

// WithOtherParameters sets other parameters.
func (b *XamarinTestCloudForIosV2Builder) WithOtherParameters(value string) *XamarinTestCloudForIosV2Builder {
	b.Builder.WithInput("other_parameters", value)
	return b
}

// WithBuildTool sets (Experimental) Which tool to use for building?.
func (b *XamarinTestCloudForIosV2Builder) WithBuildTool(value string) *XamarinTestCloudForIosV2Builder {
	b.Builder.WithInput("build_tool", value)
	return b
}
