// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: browserstack-upload (0.1.4)

package step

// BrowserstackUploadBuilder builds a browserstack-upload step with typed input methods.
type BrowserstackUploadBuilder struct{ *Builder }

// BrowserstackUpload creates a browserstack-upload step builder (v0).
func BrowserstackUpload() *BrowserstackUploadBuilder {
	return &BrowserstackUploadBuilder{Builder: From("browserstack-upload", "0")}
}

// WithUploadPath sets a Bitrise generated APK or IPA path.
func (b *BrowserstackUploadBuilder) WithUploadPath(value string) *BrowserstackUploadBuilder {
	b.Builder.WithInput("upload_path", value)
	return b
}

// WithBrowserstackUsername sets browserstack username.
func (b *BrowserstackUploadBuilder) WithBrowserstackUsername(value string) *BrowserstackUploadBuilder {
	b.Builder.WithInput("browserstack_username", value)
	return b
}

// WithBrowserstackAccessKey sets browserstack access key.
func (b *BrowserstackUploadBuilder) WithBrowserstackAccessKey(value string) *BrowserstackUploadBuilder {
	b.Builder.WithInput("browserstack_access_key", value)
	return b
}

// WithCustomId sets custom Id.
func (b *BrowserstackUploadBuilder) WithCustomId(value string) *BrowserstackUploadBuilder {
	b.Builder.WithInput("custom_id", value)
	return b
}
