// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: send-google-chat-message (1.1.1)

package step

// SendGoogleChatMessageBuilder builds a send-google-chat-message step with typed input methods.
type SendGoogleChatMessageBuilder struct{ *Builder }

// SendGoogleChatMessage creates a send-google-chat-message step builder (v1).
func SendGoogleChatMessage() *SendGoogleChatMessageBuilder {
	return &SendGoogleChatMessageBuilder{Builder: From("send-google-chat-message", "1")}
}

// WithGoogleChatWebhookUrl sets google Chat Webhook URL.
func (b *SendGoogleChatMessageBuilder) WithGoogleChatWebhookUrl(value string) *SendGoogleChatMessageBuilder {
	b.Builder.WithInput("google_chat_webhook_url", value)
	return b
}

// WithNotifyOnSuccess sets notify on Success.
func (b *SendGoogleChatMessageBuilder) WithNotifyOnSuccess(value string) *SendGoogleChatMessageBuilder {
	b.Builder.WithInput("notify_on_success", value)
	return b
}

// WithStateOverride sets set Specific Status.
func (b *SendGoogleChatMessageBuilder) WithStateOverride(value string) *SendGoogleChatMessageBuilder {
	b.Builder.WithInput("state_override", value)
	return b
}

// WithPipelineBuildStatus sets pipeline Build Status.
func (b *SendGoogleChatMessageBuilder) WithPipelineBuildStatus(value string) *SendGoogleChatMessageBuilder {
	b.Builder.WithInput("pipeline_build_status", value)
	return b
}

// WithBuildStatus sets build Status.
func (b *SendGoogleChatMessageBuilder) WithBuildStatus(value string) *SendGoogleChatMessageBuilder {
	b.Builder.WithInput("build_status", value)
	return b
}

// WithAppTitle sets app Title.
func (b *SendGoogleChatMessageBuilder) WithAppTitle(value string) *SendGoogleChatMessageBuilder {
	b.Builder.WithInput("app_title", value)
	return b
}

// WithBuildNumber sets build Number.
func (b *SendGoogleChatMessageBuilder) WithBuildNumber(value string) *SendGoogleChatMessageBuilder {
	b.Builder.WithInput("build_number", value)
	return b
}

// WithWorkflowId sets workflow ID.
func (b *SendGoogleChatMessageBuilder) WithWorkflowId(value string) *SendGoogleChatMessageBuilder {
	b.Builder.WithInput("workflow_id", value)
	return b
}

// WithBuildUrl sets build URL.
func (b *SendGoogleChatMessageBuilder) WithBuildUrl(value string) *SendGoogleChatMessageBuilder {
	b.Builder.WithInput("build_url", value)
	return b
}
