// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: carthage (1.0.8)

package step

// CarthageV1Builder builds a carthage step with typed input methods.
type CarthageV1Builder struct{ *Builder }

// CarthageV1 creates a carthage step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.CarthageV1("1")  // explicit default
//	step.CarthageV1("1")                  // older major
func CarthageV1(version ...string) *CarthageV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &CarthageV1Builder{Builder: From("carthage", v)}
}

// WithCarthageCommand sets carthage command to run.
func (b *CarthageV1Builder) WithCarthageCommand(value string) *CarthageV1Builder {
	b.Builder.WithInput("carthage_command", value)
	return b
}

// WithNoUseBinaries sets set no use binaries flag.
func (b *CarthageV1Builder) WithNoUseBinaries(value string) *CarthageV1Builder {
	b.Builder.WithInput("no_use_binaries", value)
	return b
}

// WithVerboseOutput sets set verbose output flag.
func (b *CarthageV1Builder) WithVerboseOutput(value string) *CarthageV1Builder {
	b.Builder.WithInput("verbose_output", value)
	return b
}

// WithSshOutput sets set ssh flag.
func (b *CarthageV1Builder) WithSshOutput(value string) *CarthageV1Builder {
	b.Builder.WithInput("ssh_output", value)
	return b
}

// WithWorkingDir sets working directory.
func (b *CarthageV1Builder) WithWorkingDir(value string) *CarthageV1Builder {
	b.Builder.WithInput("working_dir", value)
	return b
}

// WithPlatform sets platform.
func (b *CarthageV1Builder) WithPlatform(value string) *CarthageV1Builder {
	b.Builder.WithInput("platform", value)
	return b
}

// WithCarthageOptions sets additional options for `carthage` command.
func (b *CarthageV1Builder) WithCarthageOptions(value string) *CarthageV1Builder {
	b.Builder.WithInput("carthage_options", value)
	return b
}
