// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: xamarin-ios-test (2.4.0)

package step

// XamarinIosTestBuilder builds a xamarin-ios-test step with typed input methods.
type XamarinIosTestBuilder struct{ *Builder }

// XamarinIosTest creates a xamarin-ios-test step builder (v2).
func XamarinIosTest(version ...string) *XamarinIosTestBuilder {
	v := "2"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &XamarinIosTestBuilder{Builder: From("xamarin-ios-test", v)}
}

// WithSimulatorDevice sets device.
func (b *XamarinIosTestBuilder) WithSimulatorDevice(value string) *XamarinIosTestBuilder {
	b.Builder.WithInput("simulator_device", value)
	return b
}

// WithSimulatorOsVersion sets oS version.
func (b *XamarinIosTestBuilder) WithSimulatorOsVersion(value string) *XamarinIosTestBuilder {
	b.Builder.WithInput("simulator_os_version", value)
	return b
}

// WithTestToRun sets test name to run.
func (b *XamarinIosTestBuilder) WithTestToRun(value string) *XamarinIosTestBuilder {
	b.Builder.WithInput("test_to_run", value)
	return b
}

// WithXamarinProject sets path to Xamarin Solution.
func (b *XamarinIosTestBuilder) WithXamarinProject(value string) *XamarinIosTestBuilder {
	b.Builder.WithInput("xamarin_project", value)
	return b
}

// WithXamarinConfiguration sets xamarin solution configuration.
func (b *XamarinIosTestBuilder) WithXamarinConfiguration(value string) *XamarinIosTestBuilder {
	b.Builder.WithInput("xamarin_configuration", value)
	return b
}

// WithXamarinPlatform sets xamarin solution platform.
func (b *XamarinIosTestBuilder) WithXamarinPlatform(value string) *XamarinIosTestBuilder {
	b.Builder.WithInput("xamarin_platform", value)
	return b
}

// WithBuildTool sets which tool to use for building?.
func (b *XamarinIosTestBuilder) WithBuildTool(value string) *XamarinIosTestBuilder {
	b.Builder.WithInput("build_tool", value)
	return b
}
