// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: google-play-rollout-update (0.0.2)

package step

// GooglePlayRolloutUpdateBuilder builds a google-play-rollout-update step with typed input methods.
type GooglePlayRolloutUpdateBuilder struct{ *Builder }

// GooglePlayRolloutUpdate creates a google-play-rollout-update step builder (v0).
func GooglePlayRolloutUpdate() *GooglePlayRolloutUpdateBuilder {
	return &GooglePlayRolloutUpdateBuilder{Builder: From("google-play-rollout-update", "0")}
}

// WithServiceAccountJsonKeyPath sets service Account JSON key file path.
func (b *GooglePlayRolloutUpdateBuilder) WithServiceAccountJsonKeyPath(value string) *GooglePlayRolloutUpdateBuilder {
	b.Builder.WithInput("service_account_json_key_path", value)
	return b
}

// WithServiceAccountJsonKeyContent sets service Account JSON key content.
func (b *GooglePlayRolloutUpdateBuilder) WithServiceAccountJsonKeyContent(value string) *GooglePlayRolloutUpdateBuilder {
	b.Builder.WithInput("service_account_json_key_content", value)
	return b
}

// WithPackageName sets package name.
func (b *GooglePlayRolloutUpdateBuilder) WithPackageName(value string) *GooglePlayRolloutUpdateBuilder {
	b.Builder.WithInput("package_name", value)
	return b
}
