// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: change-android-applicationid (1.0.0)

package step

// ChangeAndroidApplicationidBuilder builds a change-android-applicationid step with typed input methods.
type ChangeAndroidApplicationidBuilder struct{ *Builder }

// ChangeAndroidApplicationid creates a change-android-applicationid step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.ChangeAndroidApplicationid("1")  // explicit default
//	step.ChangeAndroidApplicationid("1")                  // older major
func ChangeAndroidApplicationid(version ...string) *ChangeAndroidApplicationidBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &ChangeAndroidApplicationidBuilder{Builder: From("change-android-applicationid", v)}
}

// WithBuildGradlePath sets path to the build.gradle file.
func (b *ChangeAndroidApplicationidBuilder) WithBuildGradlePath(value string) *ChangeAndroidApplicationidBuilder {
	b.Builder.WithInput("build_gradle_path", value)
	return b
}

// WithNewApplicationId sets new applicationId.
func (b *ChangeAndroidApplicationidBuilder) WithNewApplicationId(value string) *ChangeAndroidApplicationidBuilder {
	b.Builder.WithInput("new_application_id", value)
	return b
}

// changeAndroidApplicationidOutputs holds the names of environment variables published
// by the change-android-applicationid step (v1) at run time.
type changeAndroidApplicationidOutputs struct {
	// AndroidApplicationId is the "Final Android applicationId in build.gradle file" output env var.
	AndroidApplicationId string
}

// ChangeAndroidApplicationidOutputs provides typed access to the environment variable names
// that change-android-applicationid (v1) exports after a successful run.
var ChangeAndroidApplicationidOutputs = changeAndroidApplicationidOutputs{
	AndroidApplicationId: "ANDROID_APPLICATION_ID",
}
