// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: restore-spm-cache (1.1.1)

package step

import "time"

// RestoreSpmCacheV1Verbose enumerates the valid values for the verbose input.
type RestoreSpmCacheV1Verbose string

const (
	RestoreSpmCacheV1VerboseTrue  RestoreSpmCacheV1Verbose = "true"
	RestoreSpmCacheV1VerboseFalse RestoreSpmCacheV1Verbose = "false"
)

// RestoreSpmCacheV1Builder builds a restore-spm-cache step with typed input methods.
type RestoreSpmCacheV1Builder struct{ *Builder }

// RestoreSpmCacheV1 creates a restore-spm-cache step builder (v1 by default).
// Pass an explicit major version to override the default:
//
//	step.RestoreSpmCacheV1("1")  // explicit default
//	step.RestoreSpmCacheV1("1")                  // older major
func RestoreSpmCacheV1(version ...string) *RestoreSpmCacheV1Builder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &RestoreSpmCacheV1Builder{Builder: From("restore-spm-cache", v)}
}

// WithVerbose sets verbose logging.
func (b *RestoreSpmCacheV1Builder) WithVerbose(value RestoreSpmCacheV1Verbose) *RestoreSpmCacheV1Builder {
	b.Builder.WithInput("verbose", string(value))
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *RestoreSpmCacheV1Builder) WithVersion(version string) *RestoreSpmCacheV1Builder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *RestoreSpmCacheV1Builder) WithInput(key, value string) *RestoreSpmCacheV1Builder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *RestoreSpmCacheV1Builder) WithRunIf(expr string) *RestoreSpmCacheV1Builder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *RestoreSpmCacheV1Builder) WithIsAlwaysRun(v bool) *RestoreSpmCacheV1Builder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *RestoreSpmCacheV1Builder) WithIsSkippable(v bool) *RestoreSpmCacheV1Builder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *RestoreSpmCacheV1Builder) WithTitle(title string) *RestoreSpmCacheV1Builder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *RestoreSpmCacheV1Builder) WithTimeout(seconds int) *RestoreSpmCacheV1Builder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *RestoreSpmCacheV1Builder) WithNoOutputTimeout(seconds int) *RestoreSpmCacheV1Builder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *RestoreSpmCacheV1Builder) WithTimeoutDuration(d time.Duration) *RestoreSpmCacheV1Builder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *RestoreSpmCacheV1Builder) WithNoOutputTimeoutDuration(d time.Duration) *RestoreSpmCacheV1Builder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *RestoreSpmCacheV1Builder) WithExecutionContainer(containerID string) *RestoreSpmCacheV1Builder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *RestoreSpmCacheV1Builder) WithServiceContainers(containerIDs ...string) *RestoreSpmCacheV1Builder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}

// restoreSpmCacheV1Outputs holds the names of environment variables published
// by the restore-spm-cache step (v1) at run time.
type restoreSpmCacheV1Outputs struct {
	// BitriseCacheHit is the "Cache hit" output env var.
	BitriseCacheHit string
}

// RestoreSpmCacheV1Outputs provides typed access to the environment variable names
// that restore-spm-cache (v1) exports after a successful run.
var RestoreSpmCacheV1Outputs = restoreSpmCacheV1Outputs{
	BitriseCacheHit: "BITRISE_CACHE_HIT",
}
