// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: flutter-analyze (0.3.2)

package step

// FlutterAnalyzeBuilder builds a flutter-analyze step with typed input methods.
type FlutterAnalyzeBuilder struct{ *Builder }

// FlutterAnalyze creates a flutter-analyze step builder (v0).
func FlutterAnalyze() *FlutterAnalyzeBuilder {
	return &FlutterAnalyzeBuilder{Builder: From("flutter-analyze", "0")}
}

// WithProjectLocation sets project Location.
func (b *FlutterAnalyzeBuilder) WithProjectLocation(value string) *FlutterAnalyzeBuilder {
	b.Builder.WithInput("project_location", value)
	return b
}

// WithFailSeverity sets fail Severity.
func (b *FlutterAnalyzeBuilder) WithFailSeverity(value string) *FlutterAnalyzeBuilder {
	b.Builder.WithInput("fail_severity", value)
	return b
}

// WithAdditionalParams sets additional Parameters.
func (b *FlutterAnalyzeBuilder) WithAdditionalParams(value string) *FlutterAnalyzeBuilder {
	b.Builder.WithInput("additional_params", value)
	return b
}
