// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: set-env-var (0.9.1)

package step

// SetEnvVarBuilder builds a set-env-var step with typed input methods.
type SetEnvVarBuilder struct{ *Builder }

// SetEnvVar creates a set-env-var step builder (v0).
func SetEnvVar() *SetEnvVarBuilder {
	return &SetEnvVarBuilder{Builder: From("set-env-var", "0")}
}

// WithValue sets value for copy into Environment variables.
func (b *SetEnvVarBuilder) WithValue(value string) *SetEnvVarBuilder {
	b.Builder.WithInput("value", value)
	return b
}

// WithDestinationKeys sets destination Environment variables.
func (b *SetEnvVarBuilder) WithDestinationKeys(value string) *SetEnvVarBuilder {
	b.Builder.WithInput("destination_keys", value)
	return b
}
