// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: ionic-prepare (1.2.1)

package step

// IonicPrepareBuilder builds a ionic-prepare step with typed input methods.
type IonicPrepareBuilder struct{ *Builder }

// IonicPrepare creates a ionic-prepare step builder (v1).
func IonicPrepare(version ...string) *IonicPrepareBuilder {
	v := "1"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &IonicPrepareBuilder{Builder: From("ionic-prepare", v)}
}

// WithPlatform sets platform.
func (b *IonicPrepareBuilder) WithPlatform(value string) *IonicPrepareBuilder {
	b.Builder.WithInput("platform", value)
	return b
}

// WithIonicVersion sets ionic version.
func (b *IonicPrepareBuilder) WithIonicVersion(value string) *IonicPrepareBuilder {
	b.Builder.WithInput("ionic_version", value)
	return b
}

// WithCordovaVersion sets cordova version.
func (b *IonicPrepareBuilder) WithCordovaVersion(value string) *IonicPrepareBuilder {
	b.Builder.WithInput("cordova_version", value)
	return b
}

// WithWorkdir sets working directory.
func (b *IonicPrepareBuilder) WithWorkdir(value string) *IonicPrepareBuilder {
	b.Builder.WithInput("workdir", value)
	return b
}

// WithIonicUsername sets ionic username.
func (b *IonicPrepareBuilder) WithIonicUsername(value string) *IonicPrepareBuilder {
	b.Builder.WithInput("ionic_username", value)
	return b
}

// WithIonicPassword sets ionic password.
func (b *IonicPrepareBuilder) WithIonicPassword(value string) *IonicPrepareBuilder {
	b.Builder.WithInput("ionic_password", value)
	return b
}

// WithCacheLocalDeps sets cache enabled.
func (b *IonicPrepareBuilder) WithCacheLocalDeps(value string) *IonicPrepareBuilder {
	b.Builder.WithInput("cache_local_deps", value)
	return b
}
