// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: save-spm-cache (1.3.2)

package step

// SaveSpmCacheBuilder builds a save-spm-cache step with typed input methods.
type SaveSpmCacheBuilder struct{ *Builder }

// SaveSpmCache creates a save-spm-cache step builder (v1).
func SaveSpmCache() *SaveSpmCacheBuilder {
	return &SaveSpmCacheBuilder{Builder: From("save-spm-cache", "1")}
}

// WithDerivedDataPath sets derived Data Path.
func (b *SaveSpmCacheBuilder) WithDerivedDataPath(value string) *SaveSpmCacheBuilder {
	b.Builder.WithInput("derived_data_path", value)
	return b
}

// WithProjectPath sets xcode Project path. Used to automatically find Derived Data path, only when `Derived Data Path` is empty (not provided)..
func (b *SaveSpmCacheBuilder) WithProjectPath(value string) *SaveSpmCacheBuilder {
	b.Builder.WithInput("project_path", value)
	return b
}

// WithVerbose sets verbose logging.
func (b *SaveSpmCacheBuilder) WithVerbose(value string) *SaveSpmCacheBuilder {
	b.Builder.WithInput("verbose", value)
	return b
}

// WithCompressionLevel sets compression level.
func (b *SaveSpmCacheBuilder) WithCompressionLevel(value string) *SaveSpmCacheBuilder {
	b.Builder.WithInput("compression_level", value)
	return b
}
