// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: gitlab-status (0.12.6)

package step

import "time"

// GitlabStatusPresetStatus enumerates the valid values for the preset_status input.
type GitlabStatusPresetStatus string

const (
	GitlabStatusPresetStatusAuto     GitlabStatusPresetStatus = "auto"
	GitlabStatusPresetStatusPending  GitlabStatusPresetStatus = "pending"
	GitlabStatusPresetStatusRunning  GitlabStatusPresetStatus = "running"
	GitlabStatusPresetStatusSuccess  GitlabStatusPresetStatus = "success"
	GitlabStatusPresetStatusFailed   GitlabStatusPresetStatus = "failed"
	GitlabStatusPresetStatusCanceled GitlabStatusPresetStatus = "canceled"
)

// GitlabStatusBuilder builds a gitlab-status step with typed input methods.
type GitlabStatusBuilder struct{ *Builder }

// GitlabStatus creates a gitlab-status step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.GitlabStatus("0")  // explicit default
//	step.GitlabStatus("1")                  // older major
func GitlabStatus(version ...string) *GitlabStatusBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &GitlabStatusBuilder{Builder: From("gitlab-status", v)}
}

// WithApiBaseUrl sets gitLab API base url.
func (b *GitlabStatusBuilder) WithApiBaseUrl(value string) *GitlabStatusBuilder {
	b.Builder.WithInput("api_base_url", value)
	return b
}

// WithPrivateToken sets gitLab private token.
func (b *GitlabStatusBuilder) WithPrivateToken(value string) *GitlabStatusBuilder {
	b.Builder.WithInput("private_token", value)
	return b
}

// WithRepositoryUrl sets repository URL.
func (b *GitlabStatusBuilder) WithRepositoryUrl(value string) *GitlabStatusBuilder {
	b.Builder.WithInput("repository_url", value)
	return b
}

// WithGitRef sets the name of a repository branch or tag or, if not given, the default branch.
func (b *GitlabStatusBuilder) WithGitRef(value string) *GitlabStatusBuilder {
	b.Builder.WithInput("git_ref", value)
	return b
}

// WithCommitHash sets commit hash.
func (b *GitlabStatusBuilder) WithCommitHash(value string) *GitlabStatusBuilder {
	b.Builder.WithInput("commit_hash", value)
	return b
}

// WithTargetUrl sets target URL.
func (b *GitlabStatusBuilder) WithTargetUrl(value string) *GitlabStatusBuilder {
	b.Builder.WithInput("target_url", value)
	return b
}

// WithContext sets context.
func (b *GitlabStatusBuilder) WithContext(value string) *GitlabStatusBuilder {
	b.Builder.WithInput("context", value)
	return b
}

// WithPresetStatus sets set Specific Status.
func (b *GitlabStatusBuilder) WithPresetStatus(value GitlabStatusPresetStatus) *GitlabStatusBuilder {
	b.Builder.WithInput("preset_status", string(value))
	return b
}

// WithDescription sets description.
func (b *GitlabStatusBuilder) WithDescription(value string) *GitlabStatusBuilder {
	b.Builder.WithInput("description", value)
	return b
}

// WithCoverage sets coverage.
func (b *GitlabStatusBuilder) WithCoverage(value string) *GitlabStatusBuilder {
	b.Builder.WithInput("coverage", value)
	return b
}

// WithVersion overrides the step version after construction. Prefer passing the version to the constructor instead.
func (b *GitlabStatusBuilder) WithVersion(version string) *GitlabStatusBuilder {
	b.Builder.WithVersion(version)
	return b
}

// WithInput sets a step input by raw key/value. Use this as an escape hatch for inputs not yet exposed as typed methods.
func (b *GitlabStatusBuilder) WithInput(key, value string) *GitlabStatusBuilder {
	b.Builder.WithInput(key, value)
	return b
}

// WithRunIf overrides the run_if expression for this step.
func (b *GitlabStatusBuilder) WithRunIf(expr string) *GitlabStatusBuilder {
	b.Builder.WithRunIf(expr)
	return b
}

// WithIsAlwaysRun configures whether this step runs even when a previous step failed.
func (b *GitlabStatusBuilder) WithIsAlwaysRun(v bool) *GitlabStatusBuilder {
	b.Builder.WithIsAlwaysRun(v)
	return b
}

// WithIsSkippable marks this step as skippable so a failure does not fail the build.
func (b *GitlabStatusBuilder) WithIsSkippable(v bool) *GitlabStatusBuilder {
	b.Builder.WithIsSkippable(v)
	return b
}

// WithTitle overrides the step title shown in the build log.
func (b *GitlabStatusBuilder) WithTitle(title string) *GitlabStatusBuilder {
	b.Builder.WithTitle(title)
	return b
}

// WithTimeout sets the maximum execution time in seconds. 0 disables the timeout.
func (b *GitlabStatusBuilder) WithTimeout(seconds int) *GitlabStatusBuilder {
	b.Builder.WithTimeout(seconds)
	return b
}

// WithNoOutputTimeout sets the maximum time the step may run without producing output.
func (b *GitlabStatusBuilder) WithNoOutputTimeout(seconds int) *GitlabStatusBuilder {
	b.Builder.WithNoOutputTimeout(seconds)
	return b
}

// WithTimeoutDuration sets the maximum execution time using a time.Duration.
func (b *GitlabStatusBuilder) WithTimeoutDuration(d time.Duration) *GitlabStatusBuilder {
	b.Builder.WithTimeoutDuration(d)
	return b
}

// WithNoOutputTimeoutDuration sets the no-output timeout using a time.Duration.
func (b *GitlabStatusBuilder) WithNoOutputTimeoutDuration(d time.Duration) *GitlabStatusBuilder {
	b.Builder.WithNoOutputTimeoutDuration(d)
	return b
}

// WithExecutionContainer pins this step to run inside the named container.
func (b *GitlabStatusBuilder) WithExecutionContainer(containerID string) *GitlabStatusBuilder {
	b.Builder.WithExecutionContainer(containerID)
	return b
}

// WithServiceContainers attaches one or more named service containers to this step.
func (b *GitlabStatusBuilder) WithServiceContainers(containerIDs ...string) *GitlabStatusBuilder {
	b.Builder.WithServiceContainers(containerIDs...)
	return b
}
