// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: danger (2.0.3)

package step

// DangerBuilder is a type alias for DangerV2Builder,
// always pointing to the latest supported major version.
// To target a specific major version use DangerV{N}() directly.
type DangerBuilder = DangerV2Builder

// Danger creates a danger step builder at the latest major version (v2).
// To target a specific major version use DangerV{N}() directly.
func Danger(version ...string) *DangerV2Builder {
	return DangerV2(version...)
}
