// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: start-android-emulator (1.3.2)

package step

// StartAndroidEmulatorBuilder is a type alias for StartAndroidEmulatorV1Builder,
// always pointing to the latest supported major version.
// To target a specific major version use StartAndroidEmulatorV{N}() directly.
//
// Deprecated: This step is deprecated, use [AVD Manager](https://github.com/bitrise-steplib/steps-avd-manager) Step instead.
type StartAndroidEmulatorBuilder = StartAndroidEmulatorV1Builder

// StartAndroidEmulator creates a start-android-emulator step builder at the latest major version (v1).
// To target a specific major version use StartAndroidEmulatorV{N}() directly.
//
// Deprecated: This step is deprecated, use [AVD Manager](https://github.com/bitrise-steplib/steps-avd-manager) Step instead.
func StartAndroidEmulator(version ...string) *StartAndroidEmulatorV1Builder {
	return StartAndroidEmulatorV1(version...)
}
