// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: bitrise-step-eschecker (0.0.1)

package step

// BitriseStepEscheckerBuilder builds a bitrise-step-eschecker step with typed input methods.
type BitriseStepEscheckerBuilder struct{ *Builder }

// BitriseStepEschecker creates a bitrise-step-eschecker step builder (v0 by default).
// Pass an explicit major version to override the default:
//
//	step.BitriseStepEschecker("0")  // explicit default
//	step.BitriseStepEschecker("1")                  // older major
func BitriseStepEschecker(version ...string) *BitriseStepEscheckerBuilder {
	v := "0"
	if len(version) > 0 && version[0] != "" {
		v = version[0]
	}
	return &BitriseStepEscheckerBuilder{Builder: From("bitrise-step-eschecker", v)}
}

// WithUploadPath sets a Bitrise generated APK or IPA path.
func (b *BitriseStepEscheckerBuilder) WithUploadPath(value string) *BitriseStepEscheckerBuilder {
	b.Builder.WithInput("upload_path", value)
	return b
}

// WithEscheckerToken sets esChecker API token.
func (b *BitriseStepEscheckerBuilder) WithEscheckerToken(value string) *BitriseStepEscheckerBuilder {
	b.Builder.WithInput("eschecker_token", value)
	return b
}

// WithEscheckerAppId sets application ID.
func (b *BitriseStepEscheckerBuilder) WithEscheckerAppId(value string) *BitriseStepEscheckerBuilder {
	b.Builder.WithInput("eschecker_app_id", value)
	return b
}

// WithEscheckerCampaignId sets campaign ID.
func (b *BitriseStepEscheckerBuilder) WithEscheckerCampaignId(value string) *BitriseStepEscheckerBuilder {
	b.Builder.WithInput("eschecker_campaign_id", value)
	return b
}
