// stepgen generates typed Go builder files for Bitrise steps sourced from
// the official Bitrise steplib.
//
// For each step ID it fetches the latest step.yml, extracts the inputs, and
// writes a typed builder file (gen_<step_id>.go) into the output directory.
//
// Two source modes are supported:
//
//  1. GitHub API (default) — fetches step metadata on demand using a worker
//     pool (--jobs, default 10). Requires a GITHUB_TOKEN env var to stay
//     within the 5,000 req/hour authenticated rate limit for large runs.
//
//  2. Local steplib clone (--steplib-dir) — reads from a local git clone of
//     the steplib; no network calls, no rate limits. Recommended when
//     generating builders for many steps at once.
//     Clone example:
//       git clone --depth 1 --filter=blob:none --sparse \
//         https://github.com/bitrise-io/bitrise-steplib.git /tmp/steplib
//       cd /tmp/steplib && git sparse-checkout set steps
//
// Usage (standalone):
//
//	go run ./cmd/stepgen [--output=step] [--config=stepgen.json] [step-id...]
//	go run ./cmd/stepgen --steplib-dir=/tmp/steplib [step-id...]
//
// Usage (via go generate from the step/ directory):
//
//	go generate ./step/
package main

import (
	"bufio"
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"text/template"
	"time"
	"unicode"

	"gopkg.in/yaml.v2"
)

// handcraftedSteps are step IDs that already have hand-written builders in
// the step package. The generator skips these to avoid duplicate declarations.
var handcraftedSteps = map[string]bool{}

// ---- config ----------------------------------------------------------------

type genConfig struct {
	Steps []string `json:"steps"`
	Skip  []string `json:"skip,omitempty"`
}

func loadConfig(path string) (genConfig, error) {
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return genConfig{}, nil
	}
	if err != nil {
		return genConfig{}, err
	}
	var cfg genConfig
	return cfg, json.Unmarshal(data, &cfg)
}

// ---- domain types ----------------------------------------------------------

type inputDef struct {
	Key        string
	MethodName string
	Comment    string
}

type stepDef struct {
	StepID         string
	Version        string
	MajorVersion   string
	Title          string
	TypeName       string
	DeprecateNotes string // non-empty when the step is deprecated
	Inputs         []inputDef
}

// ---- code generation template ----------------------------------------------

const builderTmpl = `// Code generated by cmd/stepgen. DO NOT EDIT.
// Step: {{.StepID}} ({{.Version}})

package step

// {{.TypeName}}Builder builds a {{.StepID}} step with typed input methods.{{if .DeprecateNotes}}
//
// Deprecated: {{.DeprecateNotes}}{{end}}
type {{.TypeName}}Builder struct{ *Builder }

// {{.TypeName}} creates a {{.StepID}} step builder (v{{.MajorVersion}}).{{if .DeprecateNotes}}
//
// Deprecated: {{.DeprecateNotes}}{{end}}
func {{.TypeName}}() *{{.TypeName}}Builder {
	return &{{.TypeName}}Builder{Builder: From("{{.StepID}}", "{{.MajorVersion}}")}
}
{{range .Inputs}}
// {{.Comment}}
func (b *{{$.TypeName}}Builder) With{{.MethodName}}(value string) *{{$.TypeName}}Builder {
	b.Builder.WithInput("{{.Key}}", value)
	return b
}
{{end}}`

// ---- main ------------------------------------------------------------------

func main() {
	outputDir := flag.String("output", "step", "directory to write generated files into")
	configFile := flag.String("config", "stepgen.json", "path to stepgen.json")
	steplibDir := flag.String("steplib-dir", "", "path to a local clone of bitrise-steplib (skips GitHub API)")
	prune := flag.Bool("prune", false, "remove skipped (removed) and deprecated steps from the config file after generation")
	deleteFiles := flag.Bool("delete", false, "delete generated files for deprecated steps (intended to be used with --prune)")
	jobs := flag.Int("jobs", 10, "number of steps to process in parallel (applies to both GitHub and local sources)")
	force := flag.Bool("force", false, "regenerate all builders even if the cached version matches the latest steplib version")
	flag.Parse()

	// Track whether step IDs came from the config file so --prune knows
	// whether it has a file to rewrite.
	stepIDs := flag.Args()
	usingConfig := len(stepIDs) == 0
	var cfg genConfig
	if usingConfig {
		var err error
		cfg, err = loadConfig(*configFile)
		if err != nil {
			fatalf("reading %s: %v", *configFile, err)
		}
		stepIDs = cfg.Steps
	}
	if len(stepIDs) == 0 {
		fatalf("no step IDs — pass them as arguments or add them to %s", *configFile)
	}

	// Build a set from the skip list so lookups are O(1).
	skipSet := make(map[string]bool, len(cfg.Skip))
	for _, id := range cfg.Skip {
		skipSet[id] = true
	}

	var src stepSource
	if *steplibDir != "" {
		src = localSource{dir: *steplibDir}
	} else {
		src = githubSource{}
	}

	tmpl := template.Must(template.New("builder").Parse(builderTmpl))

	// stepResult holds the outcome of processing one step ID.
	type stepResult struct {
		id      string
		outcome stepOutcome
		err     error
		ran     bool // false for entries that were skipped before the goroutine launched
	}

	// Pre-allocate a result slot for every step ID so we can write by index
	// from goroutines without needing a mutex on the slice itself.
	results := make([]stepResult, len(stepIDs))

	var (
		printMu sync.Mutex // serialises all console output across workers
		wg      sync.WaitGroup
		sem     = make(chan struct{}, *jobs) // semaphore limiting concurrency
	)

	ok, uptodate, skip, fail := 0, 0, 0, 0
	for i, id := range stepIDs {
		if handcraftedSteps[id] {
			printMu.Lock()
			fmt.Printf("skip %-40s (hand-crafted builder exists)\n", id)
			printMu.Unlock()
			skip++
			continue
		}
		if skipSet[id] {
			printMu.Lock()
			fmt.Printf("skip %-40s (in skip list)\n", id)
			printMu.Unlock()
			skip++
			continue
		}

		wg.Add(1)
		go func(i int, id string) {
			defer wg.Done()
			sem <- struct{}{}         // acquire
			defer func() { <-sem }() // release

			out, err := generateStep(id, *outputDir, tmpl, src, &printMu, *force)
			results[i] = stepResult{id: id, outcome: out, err: err, ran: true}
		}(i, id)
	}
	wg.Wait()

	var removedIDs []string
	var deprecated []deprecationInfo
	for _, r := range results {
		if !r.ran {
			continue
		}
		if r.err != nil {
			fail++
		} else if r.outcome.removed {
			skip++
			removedIDs = append(removedIDs, r.id)
		} else if r.outcome.upToDate {
			uptodate++
		} else {
			ok++
			if r.outcome.dep != nil {
				r.outcome.dep.StepID = r.id
				deprecated = append(deprecated, *r.outcome.dep)
			}
		}
	}
	fmt.Printf("\ndone: %d generated, %d up to date, %d skipped, %d errors\n", ok, uptodate, skip, fail)

	if len(deprecated) > 0 {
		fmt.Fprintf(os.Stderr, "\n⚠️  WARNING: %d deprecated step(s) were generated:\n", len(deprecated))
		for _, d := range deprecated {
			fmt.Fprintf(os.Stderr, "\n  • %s\n", d.StepID)
			if d.RemovalDate != "" {
				fmt.Fprintf(os.Stderr, "    removal date: %s\n", d.RemovalDate)
			}
			fmt.Fprintf(os.Stderr, "    %s\n", strings.ReplaceAll(d.Notes, "\n", "\n    "))
		}
		if !*prune {
			fmt.Fprintln(os.Stderr, "\nConsider removing these steps from stepgen.json or re-running with --prune.")
		}
	}

	if *prune {
		if !usingConfig {
			fmt.Fprintln(os.Stderr, "\nwarning: --prune has no effect when step IDs are passed as arguments (no config file to rewrite)")
		} else {
			// Removed steps (no versions in steplib) move into the skip list so
			// they are intentionally excluded on future runs without being lost.
			// Deprecated steps are removed from steps entirely.
			if err := pruneConfig(*configFile, removedIDs, deprecatedIDs(deprecated)); err != nil {
				fatalf("pruning config: %v", err)
			}
		}
	}

	if *deleteFiles {
		if err := deleteDeprecatedFiles(*outputDir, deprecated); err != nil {
			fatalf("deleting deprecated files: %v", err)
		}
	}
}

// deprecatedIDs returns just the step ID strings from a slice of deprecationInfo.
func deprecatedIDs(deps []deprecationInfo) []string {
	ids := make([]string, len(deps))
	for i, d := range deps {
		ids[i] = d.StepID
	}
	return ids
}

// pruneConfig rewrites the config file at path:
//   - removedIDs (no versions in steplib) are moved from steps into the skip list
//   - deprecatedIDs are removed from steps entirely (their // Deprecated: godoc
//     already warns users; keeping them in skip would be noise)
func pruneConfig(path string, removedIDs, deprecatedIDs []string) error {
	if len(removedIDs) == 0 && len(deprecatedIDs) == 0 {
		fmt.Fprintln(os.Stderr, "\nnothing to prune")
		return nil
	}

	cfg, err := loadConfig(path)
	if err != nil {
		return err
	}

	// Build removal sets.
	moveToSkip := make(map[string]bool, len(removedIDs))
	for _, id := range removedIDs {
		moveToSkip[id] = true
	}
	dropEntirely := make(map[string]bool, len(deprecatedIDs))
	for _, id := range deprecatedIDs {
		dropEntirely[id] = true
	}

	// Filter steps: keep anything not being pruned.
	kept := cfg.Steps[:0]
	for _, id := range cfg.Steps {
		if !moveToSkip[id] && !dropEntirely[id] {
			kept = append(kept, id)
		}
	}
	cfg.Steps = kept

	// Merge removed IDs into the skip list, avoiding duplicates.
	existing := make(map[string]bool, len(cfg.Skip))
	for _, id := range cfg.Skip {
		existing[id] = true
	}
	for _, id := range removedIDs {
		if !existing[id] {
			cfg.Skip = append(cfg.Skip, id)
			existing[id] = true
		}
	}
	sort.Strings(cfg.Skip)

	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	data = append(data, '\n')
	if err := os.WriteFile(path, data, 0644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}

	if len(removedIDs) > 0 {
		fmt.Fprintf(os.Stderr, "\n🧹 moved %d removed step(s) to skip list in %s:\n", len(removedIDs), path)
		for _, id := range removedIDs {
			fmt.Fprintf(os.Stderr, "  - %s\n", id)
		}
	}
	if len(deprecatedIDs) > 0 {
		fmt.Fprintf(os.Stderr, "\n🧹 removed %d deprecated step(s) from %s:\n", len(deprecatedIDs), path)
		for _, id := range deprecatedIDs {
			fmt.Fprintf(os.Stderr, "  - %s\n", id)
		}
	}
	return nil
}

// deleteDeprecatedFiles removes the generated .go file for each deprecated step.
func deleteDeprecatedFiles(outputDir string, deps []deprecationInfo) error {
	if len(deps) == 0 {
		return nil
	}
	fmt.Fprintf(os.Stderr, "\n🗑️  deleting %d deprecated generated file(s):\n", len(deps))
	for _, d := range deps {
		base := "gen_" + normalizeID(d.StepID)
		if strings.HasSuffix(base, "_test") {
			base += "_builder"
		}
		path := filepath.Join(outputDir, base+".go")
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove %s: %w", path, err)
		}
		fmt.Fprintf(os.Stderr, "  - %s\n", path)
	}
	return nil
}

// ---- step source abstraction -----------------------------------------------

type stepSource interface {
	listVersions(stepID string) ([]string, error)
	readStepYML(stepID, version string) ([]byte, error)
	readStepInfo(stepID string) ([]byte, error)
}

// localSource reads from a local clone of the steplib.
type localSource struct{ dir string }

func (s localSource) listVersions(stepID string) ([]string, error) {
	entries, err := os.ReadDir(filepath.Join(s.dir, "steps", stepID))
	if err != nil {
		return nil, fmt.Errorf("read dir: %w", err)
	}
	var versions []string
	for _, e := range entries {
		if e.IsDir() {
			versions = append(versions, e.Name())
		}
	}
	return versions, nil
}

func (s localSource) readStepYML(stepID, version string) ([]byte, error) {
	path := filepath.Join(s.dir, "steps", stepID, version, "step.yml")
	return os.ReadFile(path)
}

func (s localSource) readStepInfo(stepID string) ([]byte, error) {
	path := filepath.Join(s.dir, "steps", stepID, "step-info.yml")
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	return data, err
}

// githubSource fetches from the GitHub API / raw content endpoint.
type githubSource struct{}

func (githubSource) listVersions(stepID string) ([]string, error) {
	return fetchVersionsGitHub(stepID)
}

func (githubSource) readStepYML(stepID, version string) ([]byte, error) {
	return fetchStepYMLGitHub(stepID, version)
}

func (githubSource) readStepInfo(stepID string) ([]byte, error) {
	return fetchStepInfoGitHub(stepID)
}

// ---- per-step generation ---------------------------------------------------

// stepOutcome carries the result of a generateStep call.
type stepOutcome struct {
	dep      *deprecationInfo // non-nil when the step is deprecated
	removed  bool             // true when the step has no versions in the steplib (tombstone)
	upToDate bool             // true when the cached file already has the latest version
}

// generateStep generates a typed builder file for stepID.
//
// mu serialises all console output so lines from concurrent workers never
// interleave — all expensive work is done before mu is locked.
//
// When force is false the function reads the existing output file's version
// header and skips full regeneration if the latest steplib version matches.
func generateStep(stepID, outputDir string, tmpl *template.Template, src stepSource, mu *sync.Mutex, force bool) (stepOutcome, error) {
	// Compute the output path up front so we can check the cached version
	// before making any further network calls.
	base := "gen_" + normalizeID(stepID)
	if strings.HasSuffix(base, "_test") {
		// Files ending in "_test.go" are excluded from normal builds by the Go
		// build system. Append "_builder" for steps whose IDs end in "-test"
		// (e.g. xcode-test → gen_xcode_test_builder.go).
		base += "_builder"
	}
	outPath := filepath.Join(outputDir, base+".go")

	versions, err := src.listVersions(stepID)
	if err != nil {
		mu.Lock()
		fmt.Fprintf(os.Stderr, "ERROR %-40s list versions: %v\n", stepID, err)
		mu.Unlock()
		return stepOutcome{}, fmt.Errorf("list versions: %w", err)
	}
	if len(versions) == 0 {
		mu.Lock()
		fmt.Printf("skip %-40s (no versions — removed from steplib)\n", stepID)
		mu.Unlock()
		return stepOutcome{removed: true}, nil
	}

	latest := latestVersion(versions)

	// Version fingerprinting: if the existing file already encodes the latest
	// version and --force is not set, skip all remaining fetches.
	if !force && readCachedVersion(outPath) == latest {
		mu.Lock()
		fmt.Printf("ok   %-40s → %-10s (up to date)\n", stepID, latest)
		mu.Unlock()
		return stepOutcome{upToDate: true}, nil
	}

	ymlData, err := src.readStepYML(stepID, latest)
	if err != nil {
		mu.Lock()
		fmt.Fprintf(os.Stderr, "ERROR %-40s read step.yml: %v\n", stepID, err)
		mu.Unlock()
		return stepOutcome{}, fmt.Errorf("read step.yml: %w", err)
	}

	def, err := parseStepYML(stepID, latest, ymlData)
	if err != nil {
		mu.Lock()
		fmt.Fprintf(os.Stderr, "ERROR %-40s parse step.yml: %v\n", stepID, err)
		mu.Unlock()
		return stepOutcome{}, fmt.Errorf("parse step.yml: %w", err)
	}

	// Check deprecation before rendering so the // Deprecated: godoc comment
	// is embedded directly in the generated source file.
	infoData, err := src.readStepInfo(stepID)
	if err != nil {
		mu.Lock()
		fmt.Fprintf(os.Stderr, "ERROR %-40s read step-info.yml: %v\n", stepID, err)
		mu.Unlock()
		return stepOutcome{}, fmt.Errorf("read step-info.yml: %w", err)
	}
	dep, err := parseStepInfo(infoData)
	if err != nil {
		mu.Lock()
		fmt.Fprintf(os.Stderr, "ERROR %-40s parse step-info.yml: %v\n", stepID, err)
		mu.Unlock()
		return stepOutcome{}, fmt.Errorf("parse step-info.yml: %w", err)
	}
	if dep != nil {
		def.DeprecateNotes = dep.Notes
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, def); err != nil {
		mu.Lock()
		fmt.Fprintf(os.Stderr, "ERROR %-40s render template: %v\n", stepID, err)
		mu.Unlock()
		return stepOutcome{}, fmt.Errorf("render template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		mu.Lock()
		fmt.Fprintf(os.Stderr, "ERROR %-40s gofmt: %v\n---\n%s", stepID, err, buf.String())
		mu.Unlock()
		return stepOutcome{}, fmt.Errorf("gofmt: %w\n---\n%s", err, buf.String())
	}

	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		mu.Lock()
		fmt.Fprintf(os.Stderr, "ERROR %-40s write %s: %v\n", stepID, outPath, err)
		mu.Unlock()
		return stepOutcome{}, fmt.Errorf("write %s: %w", outPath, err)
	}

	// All work done — print one complete, uninterruptible line.
	mu.Lock()
	if dep != nil {
		fmt.Printf("gen  %-40s → %-10s wrote %s ⚠️  DEPRECATED\n", stepID, latest, outPath)
	} else {
		fmt.Printf("gen  %-40s → %-10s wrote %s\n", stepID, latest, outPath)
	}
	mu.Unlock()

	return stepOutcome{dep: dep}, nil
}

// readCachedVersion reads the version embedded in the header of a previously
// generated builder file. It returns the empty string if the file does not
// exist or the header cannot be parsed.
//
// The expected header format (line 2 of every generated file) is:
//
//	// Step: <step-id> (<version>)
func readCachedVersion(path string) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()

	sc := bufio.NewScanner(f)
	sc.Scan() // line 1: // Code generated by cmd/stepgen. DO NOT EDIT.
	if !sc.Scan() {
		return "" // line 2 missing
	}
	line := sc.Text() // e.g. "// Step: activate-ssh-key (4.1.1)"
	i := strings.LastIndex(line, "(")
	j := strings.LastIndex(line, ")")
	if i < 0 || j <= i {
		return ""
	}
	return line[i+1 : j]
}

// ---- GitHub fetching -------------------------------------------------------

var httpClient = &http.Client{Timeout: 30 * time.Second}

func httpGet(url string) (*http.Response, error) {
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("User-Agent", "bitrise-pipeline-sdk/stepgen")
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	if tok := os.Getenv("GITHUB_TOKEN"); tok != "" {
		req.Header.Set("Authorization", "Bearer "+tok)
	}
	return httpClient.Do(req)
}

type ghDirEntry struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

func fetchVersionsGitHub(stepID string) ([]string, error) {
	url := "https://api.github.com/repos/bitrise-io/bitrise-steplib/contents/steps/" + stepID
	resp, err := httpGet(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode == 404 {
		return nil, fmt.Errorf("step %q not found in steplib", stepID)
	}
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("GitHub API %d: %s", resp.StatusCode, body)
	}
	var entries []ghDirEntry
	if err := json.Unmarshal(body, &entries); err != nil {
		return nil, fmt.Errorf("decode directory listing: %w", err)
	}
	var versions []string
	for _, e := range entries {
		if e.Type == "dir" {
			versions = append(versions, e.Name)
		}
	}
	return versions, nil
}

func fetchStepYMLGitHub(stepID, version string) ([]byte, error) {
	url := fmt.Sprintf(
		"https://raw.githubusercontent.com/bitrise-io/bitrise-steplib/master/steps/%s/%s/step.yml",
		stepID, version,
	)
	resp, err := httpGet(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("HTTP %d", resp.StatusCode)
	}
	return body, nil
}

func fetchStepInfoGitHub(stepID string) ([]byte, error) {
	url := fmt.Sprintf(
		"https://raw.githubusercontent.com/bitrise-io/bitrise-steplib/master/steps/%s/step-info.yml",
		stepID,
	)
	resp, err := httpGet(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode == 404 {
		return nil, nil // no step-info.yml is normal for non-deprecated steps
	}
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("HTTP %d", resp.StatusCode)
	}
	return body, nil
}

// ---- step-info.yml parsing -------------------------------------------------

type rawStepInfo struct {
	DeprecateNotes string `yaml:"deprecate_notes"`
	RemovalDate    string `yaml:"removal_date"`
}

// deprecationInfo holds deprecation metadata for a step.
type deprecationInfo struct {
	StepID      string
	Notes       string
	RemovalDate string
}

func parseStepInfo(data []byte) (*deprecationInfo, error) {
	if len(data) == 0 {
		return nil, nil
	}
	var raw rawStepInfo
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("unmarshal step-info.yml: %w", err)
	}
	if raw.DeprecateNotes == "" {
		return nil, nil
	}
	return &deprecationInfo{
		Notes:       strings.TrimSpace(raw.DeprecateNotes),
		RemovalDate: raw.RemovalDate,
	}, nil
}

// ---- step.yml parsing ------------------------------------------------------

type rawStepYML struct {
	Title  string                   `yaml:"title"`
	Inputs []map[string]interface{} `yaml:"inputs"`
}

func parseStepYML(stepID, version string, data []byte) (*stepDef, error) {
	var raw rawStepYML
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("unmarshal YAML: %w", err)
	}

	def := &stepDef{
		StepID:       stepID,
		Version:      version,
		MajorVersion: majorVersion(version),
		Title:        raw.Title,
		TypeName:     toTypeName(stepID),
	}

	seen := map[string]bool{}
	for _, rawInput := range raw.Inputs {
		var key string
		var rawOpts interface{}
		for k, v := range rawInput {
			if k == "opts" {
				rawOpts = v
			} else {
				key = k
			}
		}
		if key == "" || !isValidIdentifier(key) {
			continue
		}

		in := inputDef{
			Key:        key,
			MethodName: toMethodName(key),
		}
		// Skip duplicate method names (can happen when a step.yml has the
		// same key listed multiple times with different default values).
		if seen[in.MethodName] {
			continue
		}
		seen[in.MethodName] = true

		if opts, ok := rawOpts.(map[interface{}]interface{}); ok {
			if title, _ := opts["title"].(string); title != "" {
				in.Comment = fmt.Sprintf("With%s sets %s.", in.MethodName, sanitizeComment(lcFirst(title)))
			}
		}
		if in.Comment == "" {
			in.Comment = fmt.Sprintf("With%s sets the %s input.", in.MethodName, key)
		}
		def.Inputs = append(def.Inputs, in)
	}
	return def, nil
}

// ---- helpers ---------------------------------------------------------------

func latestVersion(versions []string) string {
	sort.Slice(versions, func(i, j int) bool {
		return cmpVer(versions[i], versions[j]) < 0
	})
	return versions[len(versions)-1]
}

func cmpVer(a, b string) int {
	pa, pb := splitVer(a), splitVer(b)
	for i := range pa {
		if pa[i] != pb[i] {
			if pa[i] < pb[i] {
				return -1
			}
			return 1
		}
	}
	return 0
}

func splitVer(v string) [3]int {
	parts := strings.SplitN(v, ".", 3)
	var r [3]int
	for i, p := range parts {
		if i >= 3 {
			break
		}
		r[i], _ = strconv.Atoi(p)
	}
	return r
}

func majorVersion(v string) string {
	if idx := strings.IndexByte(v, '.'); idx >= 0 {
		return v[:idx]
	}
	return v
}

func normalizeID(id string) string {
	return strings.ReplaceAll(id, "-", "_")
}

func toTypeName(id string) string {
	var b strings.Builder
	for _, part := range strings.Split(id, "-") {
		if len(part) > 0 {
			b.WriteRune(unicode.ToUpper(rune(part[0])))
			b.WriteString(part[1:])
		}
	}
	return b.String()
}

func toMethodName(key string) string {
	var b strings.Builder
	for _, part := range strings.Split(key, "_") {
		if len(part) > 0 {
			b.WriteRune(unicode.ToUpper(rune(part[0])))
			b.WriteString(part[1:])
		}
	}
	return b.String()
}

func isValidIdentifier(key string) bool {
	if key == "" {
		return false
	}
	for _, r := range key {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_' {
			return false
		}
	}
	return !unicode.IsDigit(rune(key[0]))
}

func lcFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

func sanitizeComment(s string) string {
	return strings.ReplaceAll(strings.TrimSpace(s), "\n", " ")
}

func fatalf(format string, args ...interface{}) {
	fmt.Fprintf(os.Stderr, "stepgen: "+format+"\n", args...)
	os.Exit(1)
}
